### ISSUE TITLE
Web on 0.0.0.0:6687 say "Requested page not found"

### ISSUE THREAD

**Issue by web-premier** [werwolfby/monitorrent#103]
Hello!
I download v 1.0.0, install by typing pip install -r requirements.txt (all dependencies has been installed).
Next I run "python server.py" - Server started on 0.0.0.0:6687.

But if open in browser - I found "Requested page not found". 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10157331/16799809/f83ccb54-490b-11e6-908d-c1d934ed92ac.png)

Help me please.

**Comment by DSilence** [comment]
Hey, make sure you correctly build the frontend as well. To do that, execute the following commands:
1) npm install
2) gulp
Note that you need node.js installed for that to work.

**Comment by web-premier** [comment]
I install nodejs - now in console:
TypeError('process_resource() takes exactly 4 arguments (5 given)',)
Traceback (most recent call last):
  File "/home/gtr/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1360, in communicate
    req.respond()
  File "/home/gtr/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 875, in respond
    self.server.gateway(self).respond()
  File "/home/gtr/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2255, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/home/gtr/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2465, in __call__
    return app(environ, start_response)
  File "/home/gtr/.local/lib/python2.7/site-packages/falcon/api.py", line 187, in __call__
    params)
  File "/home/gtr/.local/lib/python2.7/site-packages/falcon/api.py", line 561, in _call_rsrc_mw
    process_resource(req, resp, resource, params)
TypeError: process_resource() takes exactly 4 arguments (5 given)

**Comment by web-premier** [comment]
I install nodejs, now in console:
`TypeError('process_resource() takes exactly 4 arguments (5 given)',)
Traceback (most recent call last):
  File "/home/gtr/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1360, in communicate
    req.respond()
  File "/home/gtr/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 875, in respond
    self.server.gateway(self).respond()
  File "/home/gtr/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2255, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/home/gtr/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2465, in __call__
    return app(environ, start_response)
  File "/home/gtr/.local/lib/python2.7/site-packages/falcon/api.py", line 187, in __call__
    params)
  File "/home/gtr/.local/lib/python2.7/site-packages/falcon/api.py", line 561, in _call_rsrc_mw
    process_resource(req, resp, resource, params)
TypeError: process_resource() takes exactly 4 arguments (5 given)`

**Comment by DSilence** [comment]
This seems related to #96 which was fixed recently.
2 options from here: 
1) Use falcon 0.3.x.
2) Use our develop branch.
Thanks!

**Comment by werwolfby** [comment]
It is because falcon version is less than 1.0.0
Did you dowload v 1.0.0 from releases? Or did you clone repository?
Could you please share ```pip install -r requirements.txt``` output?

**Comment by web-premier** [comment]
I download v 1.0.0.
`pip install -r requirements.txt` output:

gtr@home-server:~/monitorrent$ pip install -r requirements.txt
Collecting pytz (from -r requirements.txt (line 1))
  Using cached pytz-2016.4-py2.py3-none-any.whl
Collecting CherryPy>=3.8.0 (from -r requirements.txt (line 2))
Collecting requests>=2.7.0 (from -r requirements.txt (line 3))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting SQLAlchemy>=1.0.6 (from -r requirements.txt (line 4))
Collecting SQLAlchemy-Enum34 (from -r requirements.txt (line 5))
  Using cached SQLAlchemy_Enum34-1.0.1-py2.py3-none-any.whl
Collecting transmissionrpc>=0.11 (from -r requirements.txt (line 6))
Collecting beautifulsoup4>=4.4.0 (from -r requirements.txt (line 7))
  Using cached beautifulsoup4-4.4.1-py2-none-any.whl
Collecting deluge-client>=1.0.2 (from -r requirements.txt (line 8))
Collecting feedparser>=5.2.1 (from -r requirements.txt (line 9))
Collecting alembic>=0.7.6 (from -r requirements.txt (line 10))
Collecting falcon (from -r requirements.txt (line 11))
  Using cached falcon-1.0.0-py2.py3-none-any.whl
Collecting itsdangerous (from -r requirements.txt (line 12))
Collecting html5lib (from -r requirements.txt (line 13))
Collecting dateutils (from -r requirements.txt (line 14))
Collecting six (from -r requirements.txt (line 17))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting enum34>=1.0.4 (from -r requirements.txt (line 18))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting future (from -r requirements.txt (line 19))
Collecting setuptools (from SQLAlchemy-Enum34->-r requirements.txt (line 5))
  Using cached setuptools-24.0.2-py2.py3-none-any.whl
Collecting python-editor>=0.3 (from alembic>=0.7.6->-r requirements.txt (line 10))
Collecting Mako (from alembic>=0.7.6->-r requirements.txt (line 10))
Collecting python-mimeparse (from falcon->-r requirements.txt (line 11))
Collecting argparse (from dateutils->-r requirements.txt (line 14))
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting python-dateutil (from dateutils->-r requirements.txt (line 14))
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting MarkupSafe>=0.9.2 (from Mako->alembic>=0.7.6->-r requirements.txt (line 10))
Installing collected packages: pytz, six, CherryPy, requests, SQLAlchemy, enum34, setuptools, SQLAlchemy-Enum34, transmissionrpc, beautifulsoup4, deluge-client, feedparser, python-editor, MarkupSafe, Mako, alembic, python-mimeparse, falcon, itsdangerous, html5lib, argparse, python-dateutil, dateutils, future
Successfully installed CherryPy-6.0.2 Mako-1.0.4 MarkupSafe-0.23 SQLAlchemy-1.0.14 SQLAlchemy-Enum34-1.0.1 alembic-0.8.6 argparse-1.2.1 beautifulsoup4-4.4.1 dateutils-0.6.6 deluge-client-1.0.4 enum34-1.1.6 falcon-1.0.0 feedparser-5.2.1 future-0.15.2 html5lib-0.9999999 itsdangerous-0.24 python-dateutil-2.5.3 python-editor-1.0.1 python-mimeparse-1.5.2 pytz-2016.4 requests-2.10.0 setuptools-24.0.2 six-1.10.0 transmissionrpc-0.11
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by werwolfby** [comment]
The easiest way for now it to update to [1.1.0-rc](https://github.com/werwolfby/monitorrent/releases/tag/1.1.0-rc)

**Comment by werwolfby** [comment]
Or you have to downgrade falcon to 0.3 version:
```
pip uninstall falcon
pip install -Iv falcon==0.3
```

**Comment by web-premier** [comment]
Thank you! With falcon 0.3 all work.

**Comment by werwolfby** [comment]
Issue solved
