### ISSUE TITLE
Sometimes on first open page looks strange

### ISSUE THREAD

**Issue by werwolfby** [werwolfby/monitorrent#110]
![issue](http://image.prntscr.com/image/831b075a5e9e4de09f83b684b6e06ac9.png)

**Comment by BatyaMedic** [comment]
R E C U R S I O N

**Comment by werwolfby** [comment]
Steps to reproduce:
  1. start monitorrent: ```python server.py``` (note: without ```--debug``` flag)
  2. open monitorrent in browser
  3. login to monitorrent
  4. close page
  5. stop monitorrent
  6. start monitorrent
  7. open monitorrent ```http://localhost:6687/#/torrents```
