### ISSUE TITLE
rutor and unionpeer support

### ISSUE THREAD

**Issue by andrewt82** [werwolfby/monitorrent#111]
i install latest build monitorrent from https://github.com/werwolfby/monitorrent/releases/download/1.0.1/monitorrent-1.0.1.zip

go into web interface and can't see this trackers:
www.rutor.org
www.unionpeer.org

![trackers](https://cloud.githubusercontent.com/assets/15378087/16837807/de05fdfe-49c5-11e6-9258-9cc64337b09c.png)

what could be the problem?

**Comment by andrewt82** [comment]
update

**Comment by DSilence** [comment]
Since those plugins do not require authentication, we didn't add dedicated settings pages for them. They will work without additional configuration.

**Comment by andrewt82** [comment]
ok thank's now i understand!

**Comment by andrewt82** [comment]
Why i add rutor url (http://rutor.info/torrent/501106/) nothing happens?
Strip runs but add button becomes active :(
In the console there are no errors.

in what could be the problem here?

**Comment by DSilence** [comment]
Most likely - rutor.info is inaccessible by your device. Try pinging it.

**Comment by andrewt82** [comment]
ping work
![2016-07-16 12 11 24](https://cloud.githubusercontent.com/assets/15378087/16893903/a5ae866c-4b4e-11e6-9de6-49d8cf41f53a.png)

**Comment by DSilence** [comment]
What version of python are you running? (python --version)

**Comment by andrewt82** [comment]
Python 2.7.9

**Comment by andrewt82** [comment]
I think this happens because of Rostelecom locks
it would be good proxy to work Rutor

**Comment by DSilence** [comment]
Could be. We've discussed possible solutions to ISP locks like build-in proxy support or customizable mirrors. Meanwhile, could you try it with proxy? Thanks for investigating btw.

**Comment by andrewt82** [comment]
I can check with the proxy, just do not know where in the code to enter the proxy server

**Comment by DSilence** [comment]
We're using requests package. To add proxy to rutor, find the plugin file (/monitorrent/plugins/trackers/rutor.py) and find all places where http request is being sent (there are 2 of them). 
Then add proxy url to each request as specified here:
http://docs.python-requests.org/en/master/user/advanced/#proxies

**Comment by andrewt82** [comment]
it's too hard for me, I'm still in python does not understand so much to do it :(

I understand that it is necessary to add to the file (rutor.py) after importing the top

proxies = {
    'http': 'http://login:passwrd@ip:port/'
}

and
change line in function def parse_url on this:
r = requests.get(url, proxies=proxies, allow_redirects=False, timeout=self.tracker_settings.requests_timeout)

change line in function def get_hash on this:
r = requests.get(download_url, proxies=proxies, allow_redirects=False, timeout=self.tracker_settings.requests_timeout)
?

**Comment by DSilence** [comment]
If it's possible, you could send me the proxy info, and I'll update it for you. Or, I could just send you the modified file and you will just change the proxy ip and port.

**Comment by andrewt82** [comment]
please send modified file and i change the proxy ip and port ant check it

**Comment by DSilence** [comment]
Uploaded zip with updated file. At the top is the list of proxies. No need to change https, just modify the http one.
[rutor.zip](https://github.com/werwolfby/monitorrent/files/367205/rutor.zip)

**Comment by andrewt82** [comment]
ok thank's, but when i try run python server.py i get error:

```
root@Server:/ffp/var/monitorrent-1.0.1# python server.py
Traceback (most recent call last):
  File "server.py", line 170, in <module>
    main()
  File "server.py", line 134, in main
    load_plugins()
  File "/mnt/HD/HD_a2/ffp/var/monitorrent-1.0.1/monitorrent/plugin_managers.py", line 21, in load_plugins
    __import__(module_name)
  File "/mnt/HD/HD_a2/ffp/var/monitorrent-1.0.1/monitorrent/plugins/trackers/_rutor.py", line 20, in <module>
    class RutorOrgTopic(Topic):
  File "/ffp/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 55, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/ffp/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/ffp/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/ffp/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in __init__
    self._setup_table()
  File "/ffp/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 395, in _setup_table
    **table_kw)
  File "/ffp/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 422, in __new__
    "existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 'rutororg_topics' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```

**Comment by werwolfby** [comment]
Looks like you have two files of rutor plugin.

**Comment by andrewt82** [comment]
you'l right!
i am just rename original rutor.py in _rutor.py :) my error plugins with .py extension automaticly loads, i rename original file to rutor.py_ and now all ok, rutor.info work perfect via proxy!
thank's for you help!

**Comment by werwolfby** [comment]
You are welcome, and thank you for investigation.

**Comment by andrewt82** [comment]
strangely, when I perform the Execute rutor.info i get error
![2016-07-16 20 27 44](https://cloud.githubusercontent.com/assets/15378087/16896145/2130bf7c-4b94-11e6-88f3-f255e9b98253.png)

**Comment by werwolfby** [comment]
Can you please click on particular report and for additional details?

**Comment by andrewt82** [comment]
i attach additional details in post upward

**Comment by werwolfby** [comment]
Do you have any logs in std output?

**Comment by andrewt82** [comment]
in std output no errors

**Comment by werwolfby** [comment]
Yep, I've checked there shouldn't be any output.
According to code, the Error status can be in case if the status code of downloaded file hasn't status 200.
Could you please try download it manually?

**Comment by werwolfby** [comment]
And thx for news that Mr. Robot started :+1: 
Will wait when **Monitorrent** download it automatically from **lostfilm.tv**

**Comment by andrewt82** [comment]
manually downloading ok, this trouble with any torrents on rutor :(
Mr. Robot - good movie, I'm also waiting for translation from lostfilm.tv ;)

**Comment by werwolfby** [comment]
We need more logging, will do this, not in nearest release, but soon.
For now we can try to insert output in rutor plugin, let me update rutor plugin for you.

**Comment by andrewt82** [comment]
ok, thank's!
I have noticed when edit rutor and unionpeer torrents no choice of series and seasons like lostfilm.tv
![2016-07-16 22 42 28](https://cloud.githubusercontent.com/assets/15378087/16896799/de7d8b7a-4ba6-11e6-89ba-0ca464c8b72d.png)
this is normal?

**Comment by werwolfby** [comment]
Yes, this is ok, because we download whole torrent, and not update info what download, and what not.
For lostfilm.tv we can select which torrent we should download

Try use this [rutor.zip](https://github.com/werwolfby/monitorrent/files/367496/rutor.zip) plugin, and send output.

**Comment by andrewt82** [comment]
i get this error:
```
301
{'Date': 'Mon, 18 Jul 2016 18:21:53 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Location': 'http://ru-tor.net/download/513492'}
```
what could be the problem?

**Comment by andrewt82** [comment]
i change in function

    def get_download_url(self, url):
        if not self.can_parse_url(url):
            return None
        parsed_url = urlparse(url)
        match = self._regex.match(parsed_url.path)
        if match is None:
            return None

        return "http://d.rutor.info/download/" + match.group(1)
row 155 with this url:
        return "http://ru-tor.net/download/" + match.group(1)

and all everything was ok :)

**Comment by werwolfby** [comment]
Got it, i think I know what to do with this issue :)

**Comment by werwolfby** [comment]
I want to know, why it is not redirecting me by http://d.rutor.info/download/513492
Looks like strange behavior of Russian Federation blocking system

**Comment by andrewt82** [comment]
Rostelecom is very bad Provider...
I think that it is necessary setup TOR or VPN on my NAS ))), in browser i use Economy Traffic on Google Chrome.

thank's I also put download s4 Ray Donavan :))

**Comment by werwolfby** [comment]
Could you please revert your changes, and update rutor.py:
Replace in this code (line 195) ```False``` on ```True```:
```
    def _prepare_request(self, topic):
        return self.tracker.get_download_url(topic.url), {'allow_redirects': False}
```
And I try to investigate why I disabled redirects for rutor, this should solve your issues as well.

**Comment by andrewt82** [comment]
ok i revert url and enable redirects on def _prepare_request
and in this functions
```
def parse_url
...
r = requests.get(url, allow_redirects=True,
```
and in this
```
def get_hash
...
r = requests.get(download_url, allow_redirects=True,
```
without redirects in this functions torrents also don't add in monitortorrent :(

**Comment by werwolfby** [comment]
Yep, make sense, we will update working with mirrors, to simplify this process.

**Comment by andrewt82** [comment]
ok thank's you VERY MUCH for you help and this cool programm!

**Comment by werwolfby** [comment]
You are welcome, and thx for issues investigation
