### ISSUE TITLE
Installing on NAS Trouble

### ISSUE THREAD

**Issue by andrewt82** [werwolfby/monitorrent#116]
I try to install monitorrent on NAS DNS 320L
first i install Python 2.7.2  and GCC 4.5.4
after i do: pip install -r requirements.txt , all requirements were successfully installed
when i try start monitorrent with command: python server.py
i get an error:
```
root@Server:/ffp/var/monitorrent-1.0.1# python server.py

python: symbol 'posix_fallocate64': can't resolve symbol
Traceback (most recent call last):
  File "server.py", line 170, in <module>
    main()
  File "server.py", line 133, in main
    init_db_engine(db_connection_string, False)
  File "/mnt/HD/HD_a2/ffp/var/monitorrent-1.0.1/monitorrent/db.py", line 61, in init_db_engine
    engine = create_engine(connection_string, echo=echo, **kwargs)
  File "/ffp/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/ffp/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/ffp/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
```

what could be the problem? what else need to install?

**Comment by werwolfby** [comment]
@andrewt82 could you please describe the solution?

**Comment by andrewt82** [comment]
when i install sqlite3 i get this error
when i install sqlite error go away :)
comand to install slacker -i sqlite and in this list need to choose **sqlite** bun not sqlite3

**Comment by werwolfby** [comment]
Thank you for installing on NAS we will update our readme, or add this info to the wiki.

**Comment by andrewt82** [comment]
thank's for you great programm!

**Comment by Neustradamus** [comment]
@andrewt82: For information:

Note that D-Link DNS-320L and DNS-325 are supported in OpenWrt:
- https://github.com/openwrt/openwrt/pull/17924
- https://github.com/openwrt/openwrt/pull/16803
- https://github.com/openwrt/openwrt/pull/15433
