### ISSUE TITLE
Список трекеров. rutor

### ISSUE THREAD

**Issue by evgsd** [werwolfby/monitorrent#123]
Отображаются не все трекеры в списке

![2016-07-16_22-28-02](https://cloud.githubusercontent.com/assets/19301158/16896743/5ac04686-4bad-11e6-9900-fe165d6f1e2f.png)

**Comment by werwolfby** [comment]
rutor.info и www.unionpeer.org не требуют авторизации потому и нет настроек ([#111](https://github.com/werwolfby/monitorrent/issues/111)).

**Comment by evgsd** [comment]
понятно. спасибо
