### ISSUE TITLE
Add all tracker plugins to the list in configuration to avoid confusion

### ISSUE THREAD

**Issue by werwolfby** [werwolfby/monitorrent#124]
Some people confused about not existing rutor and unionpeer, we need to show it in list of plugins, but without settings.

**Comment by evgsd** [comment]
Можно их и не показывать, но где то сообщить юзеру, что отображаются только трекеры в которых можно что то настраивать. А так первое впечатление "что то пошло не так и не все плагины-трекеры подгрузились"
