### ISSUE TITLE
Test gevent on router

### ISSUE THREAD

**Issue by werwolfby** [werwolfby/monitorrent#129]
```
cd /opt
wget http://pkg.entware.net/binaries/mipsel_test/python-gevent_1.1.1-1_mipselsf.ipk
opkg install python-gevent_1.1.1-1_mipselsf.ipk
```

**Comment by rk4n** [comment]
Just tested on MyBook Live NAS.

```
(venv)(chroot-debian)/opt/monitorrent# cat /proc/cpuinfo 
processor	: 0
cpu		: APM82181
clock		: 800.000008MHz
revision	: 28.131 (pvr 12c4 1c83)
bogomips	: 1600.00
timebase	: 800000008
platform	: PowerPC 44x Platform
model		: amcc,apollo3g
Memory		: 256 MB
(venv)(chroot-debian)/opt/monitorrent# uname -a
Linux MyBookLiveDuo 2.6.32.11-svn70860 #1 Thu May 17 13:32:51 PDT 2012 ppc GNU/Linux
(venv)(chroot-debian)/opt/monitorrent# pip install gevent
Requirement already satisfied (use --upgrade to upgrade): gevent in ./venv/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.9 in ./venv/lib/python2.7/site-packages (from gevent)
Cleaning up...
(venv)(chroot-debian)/opt/monitorrent# head -n 10 server.py
from gevent import monkey
monkey.patch_all()

from builtins import range
import os
import sys
import six
import random
import string
import argparse
(venv)(chroot-debian)/opt/monitorrent# python ./server.py
Server started on 0.0.0.0:6687
```

**Comment by werwolfby** [comment]
Thanks for the info.

But MyBook Live is more powerfull than router CPU. And you can install ```gevent``` by ```pip```. While on routers it fails. Script in header should fix the issue but I didn't try it because I don't host Monitorrent on my router.

**Comment by MercuryV** [comment]
Works like a charm on Entware-ng powered mipsel router (MT7621A, 256 RAM)
python - 2.7.13-4
python-gevent - 1.1.2-1
python3 - 3.6.0-4a
pip & pip3 is functional too
Note: needs `pip3 install --upgrade setuptools` before using `pip3 install -r requirements.txt`
RAM consumption is about 40-50 MiB

**Comment by werwolfby** [comment]
Thanks for the testing!
I've just realized that **gevent** > 1.0 already part of public repository.
I'll try to test on my **ASUS RT-N16**

**Comment by werwolfby** [comment]
I've tested, but anyway no more plans to support old MIPS routers :(
