### ISSUE TITLE
Попытка запустить на роутере RT-N14 от Padavana

### ISSUE THREAD

**Issue by RazielMalah** [werwolfby/monitorrent#130]
Добрый день, при установке 

`pip install -r requirements.txt
`

Ответило вот чем

Successfully built CherryPy SQLAlchemy transmissionrpc deluge-client feedparser alembic itsdangerous html5lib dateutils future Mako python-editor python-mimeparse webencodings MarkupSafe
Installing collected packages: pytz, CherryPy, SQLAlchemy, enum34, SQLAlchemy-Enum34, transmissionrpc, beautifulsoup4, deluge-client, feedparser, MarkupSafe, Mako, python-editor, alembic, python-mimeparse, falcon, itsdangerous, webencodings, html5lib, python-dateutil, dateutils, future
Successfully installed CherryPy-6.2.0 Mako-1.0.4 MarkupSafe-0.23 SQLAlchemy-1.0.14 SQLAlchemy-Enum34-1.0.1 alembic-0.8.6 beautifulsoup4-4.4.1 dateutils-0.6.6 deluge-client-1.0.4 enum34-1.1.6 falcon-1.0.0 feedparser-5.2.1 future-0.15.2 html5lib-0.999999999 itsdangerous-0.24 python-dateutil-2.5.3 python-editor-1.0.1 python-mimeparse-1.5.2 pytz-2016.6.1 transmissionrpc-0.11 webencodings-0.5

Т.е. все нужны пакеты на месте?

Однако при попытке запустить сервер выругнулось на отсутствие неких библиотек, куда копнуть? 

/opt/home/admin/monitorrent # python server.py
Traceback (most recent call last):
  File "server.py", line 12, in <module>
    from monitorrent.plugin_managers import load_plugins, get_plugins, TrackersManager, DbClientsManager
  File "/opt/home/admin/monitorrent/monitorrent/plugin_managers.py", line 7, in <module>
    from monitorrent.plugins.trackers import TrackerPluginBase, WithCredentialsMixin, TrackerSettings
  File "/opt/home/admin/monitorrent/monitorrent/plugins/trackers/__init__.py", line 8, in <module>
    from monitorrent.utils.bittorrent import Torrent
  File "/opt/home/admin/monitorrent/monitorrent/utils/bittorrent.py", line 12, in <module>
    from past.builtins import long as oldlong
  File "/opt/lib/python2.7/site-packages/past/__init__.py", line 88, in <module>
    from past.translation import install_hooks as autotranslate
  File "/opt/lib/python2.7/site-packages/past/translation/__init__.py", line 41, in <module>
    from lib2to3.pgen2.parse import ParseError
ImportError: No module named lib2to3.pgen2.parse

Спасибо заранее.

**Comment by werwolfby** [comment]
Если прошивка от Padavana - в себе содержит пакеты от entware, то всё должно работать.
Вечером попробую поставить на Asus RT-N16.

**Comment by MercuryV** [comment]
У меня тоже не взлетело.
Похоже, что через pip некоторым пакетам требуется пересборка на устройстве, чего по факту не происходит. А полного набора нужных пакетов вида python-something в Entware нет.

**Comment by werwolfby** [comment]
Ну дополнительно я ставил только python-lxml всё остальное должно и так работать.

**Comment by ryzhovau** [comment]
Если опубликуете хотя бы приблизительный HOW-TO, то будет здорово. Коллеге по репозиторию это сделать не удалось. Я, в свою очередь, [проверил](http://forum.keenetic.net/topic/458-debian-stable-%D0%BD%D0%B0-%D0%BA%D0%B8%D0%BD%D0%B5%D1%82%D0%B8%D0%BA%D0%B5/#comment-7035) работу лишь в chroot-Debian'е.

**Comment by ryzhovau** [comment]
@MercuryV опередил:)

**Comment by ryzhovau** [comment]
@RazielMalah, на RT-N14U установка зависимостей будет тошнить примерно полчаса, причём без свопа упадёт.
```
# cd /opt/tmp
# wget https://github.com/werwolfby/monitorrent/releases/download/1.0.1/monitorrent-1.0.1.zip
# unzip -d mt ./monitorrent-1.0.1.zip
# cd mt
# opkg install python3-pip
# pip3 install -r requirements.txt
...
Installing collected packages: pytz, six, CherryPy, requests, SQLAlchemy, SQLAlchemy-Enum34, transmissionrpc, beautifulsoup4, deluge-client, feedparser, MarkupSafe, Mako, python-editor, alembic, python-mimeparse, falcon, itsdangerous, webencodings, html5lib, argparse, python-dateutil, dateutils, enum34, future
...
Successfully installed CherryPy-6.2.0 Mako-1.0.4 MarkupSafe-0.23 SQLAlchemy-1.0.14 SQLAlchemy-Enum34-1.0.1 alembic-0.8.6 argparse-1.4.0 beautifulsoup4-4.5.0 dateutils-0.6.6 deluge-client-1.0.4 enum34-1.1.6 falcon-1.0.0 feedparser-5.2.1 future-0.15.2 html5lib-0.999999999 itsdangerous-0.24 python-dateutil-2.5.3 python-editor-1.0.1 python-mimeparse-1.5.2 pytz-2016.6.1 requests-2.10.0 six-1.10.0 transmissionrpc-0.11 webencodings-0.5
...
# python3 server.py
```

**Comment by werwolfby** [comment]
Смог запустить на своём RT-N16 только под 3-м питоном, собственно поддержка 3-го и сломала запуск monitorrent'а под 2-ым. Устанавливался около 30 минут, что тоже многовато конечно. Первый запуск около 30 секунд, второй быстрее. Я так понимаю компилит все **\*.py** в **\*.pyc**.

Да памяти ест не мало, но это особенность питона в принципе, **flexget** тоже ел много памяти.

**Comment by RazielMalah** [comment]
Спасибо, так завелось.
Только вот в настройках к трансмишну не подключается (Connection failed). Надо в поля те же параметры что и в виндовом клиенте указывать? Например 
http://192.168.1.1:9091 login/password
К рутрекеру тоже не подключается, а к лостфильму подключается.

Ну и самое главное, если я закрою терминал, в котором питоновский скрипт открыт, программа отключается, т.е. комп не отключить и по своим делам не уйти. Как то можно создать задачу чтобы он работал?

**Comment by werwolfby** [comment]
![transmission](https://cloud.githubusercontent.com/assets/705754/16707729/978939c8-45e1-11e6-98b2-3608784e627b.png)
В вашем случае host: 192.168.1.1
А порт: 9091

**Comment by evgsd** [comment]
> Ну и самое главное, если я закрою терминал, в котором питоновский скрипт открыт, программа отключается, т.е. комп не отключить и по своим делам не уйти. Как то можно создать задачу чтобы он работал?

Тут несколько вариантов, можно запускать в screen, можно уводить в фон, добавив '&' в конец файла через пробел или можно написать скрипт запуска для init.d/upstart/systemd и пусть система сама его стартует

**Comment by werwolfby** [comment]
@evgsd: Спасибо :+1:

**Comment by RazielMalah** [comment]
@evgsd
![default](https://cloud.githubusercontent.com/assets/15436094/17014523/54b8148a-4f68-11e6-9d27-2e5394c425ce.PNG)
Так и есть, клиент то работает как то...

**Comment by evgsd** [comment]
http:// тут лишнее

**Comment by RazielMalah** [comment]
Спасибо, немного погодя подключилось. Но есть ещё одна проблема :(
![default](https://cloud.githubusercontent.com/assets/15436094/17014933/a6caed40-4f6a-11e6-887d-9f5e7402f764.PNG)

**Comment by werwolfby** [comment]
Какая версия приложения?

**Comment by RazielMalah** [comment]
С главной брал 1.0.1
https://github.com/werwolfby/monitorrent/releases/download/1.0.1/monitorrent-1.0.1.zip

**Comment by werwolfby** [comment]
Понятно,
@RazielMalah  - заводите новый ишью, в 1.1.0 поправим

**Comment by werwolfby** [comment]
А эту пора закрывать
