### ISSUE TITLE
Не отключается аутентификация v.1.1.0-rc.1.1 

### ISSUE THREAD

**Issue by lastbyte32** [werwolfby/monitorrent#131]
safari 9.1.1 (11601.6.17)
я.браузер 16.7.0.3348 (64-bit)
docker x86
Не отключается аутентификация. 
Выключаю. ВЫхожу из настроек. снова захожу а там опять 
`is_authentication_enabled:true`

**Comment by werwolfby** [comment]
was broken by #101
