### ISSUE TITLE
Failed update

### ISSUE THREAD

**Issue by RazielMalah** [werwolfby/monitorrent#134]
![default](https://cloud.githubusercontent.com/assets/15436094/17015255/75d934a6-4f6c-11e6-91b4-e1b9a49aec87.PNG)
Ошибка при попытке обновить торрент

**Comment by MercuryV** [comment]
Подтверждаю ошибку с третьим питоном из Entware.

**Comment by werwolfby** [comment]
Да, я тоже подтверждаю. Скоро исправлю.

**Comment by werwolfby** [comment]
This is issue in [transmissionrpc](https://bitbucket.org/blueluna/transmissionrpc/issues/81/py3-typeerror-endswith-first-arg-must-be)
**add_torrent** method expect **base64** *str*, not **base64** *bytes*

I've applied workaround for Python 3.

**Comment by werwolfby** [comment]
@RazielMalah, @MercuryV можете проверить, что всё работает? Было исправлено в [1.0.2](https://github.com/werwolfby/monitorrent/releases/tag/1.0.2).
Можно заменить только вот этот файл: 
https://github.com/werwolfby/monitorrent/blob/10515f0e5687705425baf34e360792ea6d49658b/monitorrent/plugins/clients/transmission.py

**Comment by RazielMalah** [comment]
К сожалению ток через 2 недели, отпуск :)

**Comment by MercuryV** [comment]
Подтверждаю, 1.0.2
