### ISSUE TITLE
Manual execute single topic/tracker shouldn't reset timeout for whole execute

### ISSUE THREAD

**Issue by werwolfby** [werwolfby/monitorrent#137]
Currently, after you make manual execute of particular topic or tracker next execute for the all topics will be scheduled in 2 hours after this execute. It is better to not reset the execute timer for this two kinds of execute.

Manual full execute shouldn't reset the timer.

**Comment by rk4n** [comment]
@werwolfby is it in-progress already? I wanted to participate in this project, so mb I can do a PR for this issue?

**Comment by werwolfby** [comment]
@rk4n I think it was in progress, but any pull request is always welcome!

So, please make a pull request.

**Comment by werwolfby** [comment]
This task is not so easy, and I didn't do any changes for it yet.

**Comment by rk4n** [comment]
@werwolfby thanks, I'll try to do that
