### ISSUE TITLE
Add tracker kinozal.tv

### ISSUE THREAD

**Issue by djudev** [werwolfby/monitorrent#138]
Пожалуйста  / Please

**Comment by werwolfby** [comment]
All tracker scheduled on post 1.1.0 release.
1.1.0 release is scheduled on [7 Aug](https://github.com/werwolfby/monitorrent/milestone/9)

**Comment by djudev** [comment]
Супер

**Comment by Shooshka** [comment]
Now you can support this Wish from https://beerpay.io/werwolfby/monitorrent/wishes/585237ff30edb1940c42ba26

🍻 Cheers!

**Comment by Shooshka** [comment]
Wish granted successfully on Beerpay! https://beerpay.io/werwolfby/monitorrent/wishes/585237ff30edb1940c42ba26
This issue will be closed.

🍻 Cheers!
