### ISSUE TITLE
Reason: 'ascii' codec can't decode byte 0xce in position 14: ordinal not in range(128)

### ISSUE THREAD

**Issue by Meffulka** [werwolfby/monitorrent#139]
Приветствую.
Первый раз натолкнулся при попытке поставить на мониторинг раздачу с тапочек (библиотека либрусек). Выдает ошибку: 

FAILED

Failed update lib.rus.ec. Reason: 'ascii' codec can't decode byte 0xce in position 14: ordinal not in range(128)
![monitorrent](https://cloud.githubusercontent.com/assets/18629744/18062298/eb4e5db6-6e2e-11e6-9fee-dae7223ceb5e.png)

**Comment by werwolfby** [comment]
А где запускаете мониторрент? Компьютер (x86/x64), Роутер или Распбери?

**Comment by Meffulka** [comment]
Rpi3. В докере. А основная ось raspbian.

**Comment by werwolfby** [comment]
Обязано пофиксаеться переездом на 3-й питон.
