### ISSUE TITLE
ubuntu install ?

### ISSUE THREAD

**Issue by sers88** [werwolfby/monitorrent#142]
Добрый день! как собственно запустить в фоне ? собсно по инструкции запускаю " python server.py" , процесс висит в терминале (работает как надо) .Но при выходе из терминала или из процесса он умирает , как запускать в фоне ?

**Comment by evgsd** [comment]
Гуглите друг мой, вы же в линуксе. Можно ещё здесь вопросы почитать, я на такой уже отвечал.

**Comment by werwolfby** [comment]
Собственно вот ответ @evgsd : https://github.com/werwolfby/monitorrent/issues/130#issuecomment-234176454

У нас есть в планах добавление init.d скрипта, но попозже.

**Comment by werwolfby** [comment]
@sers88, я надеюсь у вас получилось и мы можем закрыть эту ишью?

**Comment by sers88** [comment]
да огромное спасибо все получилось, извините что так долго отписывал =) единственное пожелание может добавите данное в ридми по установки ?

**Comment by werwolfby** [comment]
Лучше init.d скрипт потом добавим.
Но все равно советую лучше воспользоваться Docker'ом
