### ISSUE TITLE
Connection failed (Clients Settings - qbittorrent)

### ISSUE THREAD

**Issue by VIBondarenko** [werwolfby/monitorrent#143]
**Информация о системе:**
Windows 10 Pro 64bit
Python 2.7
Chrome 53.0.2785.143
qBittorent 3.3.7
Monitorrent v.1.1.0-rc.1.1
 
Все перечисленное программное обеспечение установлено на одном компьютере.
В qBittorent 3.3.7 включен веб-интерфейс (по умолчанию порт 8080).
**В Monitorrent для qBittorrent указаны такие настройки:**
    Host: 192.168.1.3 (Адрес компьютера, пробовал так же localhost)      Port: 8080
    Username: admin      Password: <******>.
При нажатии кнопки "Check" выскакивает ошибка "Connection failed".
В чем может быть причина?

**Comment by amorskoj** [comment]
Вместо IP попробовать localhost?
Проверить 'telnet 192.168.1.3' ?

**Comment by werwolfby** [comment]
Сначала нужно сделать Save после этого Check.
Совсем не логично, понимаем :) будем исправлять, а пока нужно обязательно сначала сделать Save, потом Check.

**Comment by VIBondarenko** [comment]
Пробовал и localhost. При чем тут Telnet, не совсем понял?
Естественно сначала нажимал "Save",  а потом "Check".

**Comment by amorskoj** [comment]
@VIBondarenko telnet, чтобы проверить действительно ли открыт порт 8080 на этой IP
Немного неправильно сказал
`telnet 192.168.1.3 8080`

**Comment by werwolfby** [comment]
В 1.0.2 закралась ошибка с qbittorrent, сейчас проверю 1.1.0

**Comment by werwolfby** [comment]
У меня локально тоже не работает, но я и в вебморду зайти не могу: все время редиректит на форму логина.

Так же не работает и qbittorrent, сейчас продебажусь более аккуратно.

**Comment by werwolfby** [comment]
А когда открыл по IP взяло и залогинело.
Monitorrent все ещё не работает, пару минут и проверю.

**Comment by werwolfby** [comment]
ВОТ ДЕРЬМО!

@VIBondarenko попробуйте в качестве **Host** указать **http://192.168.1.3**

Это просто дикий косяк, в версии 1.1 постараемся исправить.

**Comment by VIBondarenko** [comment]
Отлично, заработало :) Спасибо :)

**Comment by werwolfby** [comment]
Мы получили хорошие уроки с разделением адреса на хост и порт, будем переделывать.

**Comment by Shooshka** [comment]
Тыкался, тыкался, failed и failed, настройки qbittorent'a измучал, хвала поиску по issue, хоть комментом бы каким или всплывающим текстом или exampl'ом бы в веб-морде в 1.1.0-rc.3 вписали ;)
