### ISSUE TITLE
HTTPS links don't work when adding new torrent

### ISSUE THREAD

**Issue by XBeg9** [werwolfby/monitorrent#146]
![monitorrent 2016-10-18 10-10-23](https://cloud.githubusercontent.com/assets/872907/19467682/1a7f862e-951b-11e6-97fe-0beb9c01e1ff.jpg)

**Comment by werwolfby** [comment]
Yes, it doesn't support it right now, will fix it soon (here is the [issue](https://github.com/werwolfby/monitorrent/blob/develop/monitorrent/plugins/trackers/lostfilm.py#L133)). I didn't know that lostfilm supports https.
If it's is critical you can fix it here (**path/to/monitorrent/plugins/trackers/lostfilm.py** line **133**):
replace
```
_regex = re.compile(u'http://www\.lostfilm\.tv/browse\.php\?cat=(?P<cat>\d+)')
```
with
```
_regex = re.compile(u'https?://www\.lostfilm\.tv/browse\.php\?cat=(?P<cat>\d+)')
```

**Comment by XBeg9** [comment]
@werwolfby here you are. Thanks ;)
