### ISSUE TITLE
Watcher / RSS feed parser

### ISSUE THREAD

**Issue by XBeg9** [werwolfby/monitorrent#148]
Just want to verify if it's done or at least you have planned to implement watcher. 
It's a bit hard to add all these torrents, for TV shows series it works great... but what about movies? 
If I want to add all movies to my transmission that IMDB rating > 7.0 and year > 2000 ?

**Comment by werwolfby** [comment]
Yes it is in plans, partially some code for newstudio.tv will be reused for this. 

If you read original article on habrahabr.ru, I describe this feature in comments (in future it definitely will be implemented).

First part will be search of some movies by some criteria's, and second one some complex rules like yours.

We have group issue (#59) for such discussions.
