### ISSUE TITLE
Reason: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

### ISSUE THREAD

**Issue by nightmare04** [werwolfby/monitorrent#153]
Запускаю в докере на DSM 6, запущенной на Microserver Gen8 выдает следующее:
INFO 
Start checking for lostfilm.tv

INFO 
Credentials/Settings are valid

DOWNLOADED 
Download new series: Ходячие мертвецы / The Walking Dead (7, 3)

FAILED 
Failed update lostfilm series: The Walking Dead. Reason: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

INFO 
End checking for lostfilm.tv

Да, и еще при запуске контейнера предложил прокинуть порт 6688 вместо 6687.

**Comment by werwolfby** [comment]
А что выдаёт
```
docker logs monitorrent
```
где monitorrent это имя контейнера

странно, в докере таких проблем ещё не было.
но и я его на **x86** машине не тестировал.

**Comment by nightmare04** [comment]
Ок, с более подробным изучением логов выяснилось, что ругался он на русское имя пользователя для transmission, извиняюсь за беспокойство.

**Comment by werwolfby** [comment]
Это в любом случае бага, так что нужно будет новую ишью сделать
