### ISSUE TITLE
Reason: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

### ISSUE THREAD

**Issue by nightmare04** [werwolfby/monitorrent#154]
Ошибка появляется при выборе имени пользователя клиента (transmission, deluge и т.д.) на русском языке.

**Comment by werwolfby** [comment]
Пофиксил для transmission, но для deluge всё равно не работает, беда во втором питоне с unicode, большая беда.

Фиксается переездом на 3-й питон.
