### ISSUE TITLE
Create additional repo for docker build with Docker file

### ISSUE THREAD

**Issue by AlDemion** [werwolfby/monitorrent#162]
For today docker image hard to modify, because Dockerfile is not included to any repo, also as documentation. If you interested - i can help to organize it.

**Comment by werwolfby** [comment]
Pushed: https://github.com/werwolfby/docker-armhf-alpine-monitorrent
If you want to add something, PRs are welcome

**Comment by werwolfby** [comment]
Partially intersected with #108
