### ISSUE TITLE
Notifier telegram 

### ISSUE THREAD

**Issue by abaistov** [werwolfby/monitorrent#164]
Хотелось бы увидеть во вкладке telegram, возможность добавить второй chatID (чтобы сообщения приходили в два чата) и , соответственно получать уведомления о добавлении раздач (насколько я понимаю, на данный момент реализовано не до конца, получаю только тестовые сообщения) :)

**Comment by werwolfby** [comment]
Да пока не доконца, но я всё ещё верю, что до нового года будет :)

**Comment by abaistov** [comment]
спасибо!
