### ISSUE TITLE
Torrent wasn't added

### ISSUE THREAD

**Issue by Shooshka** [werwolfby/monitorrent#165]
Windows 10 64bit
Python 2.7
qBittorent 3.3.8
Monitorrent v.1.1.0-rc.3

```
Start checking for nnmclub.to
Credentials/Settings are valid
Check for changes Библиотекари / The Librarians (2016) WEB-DLRip [H.264/1080p-LQ] (сезон 3, серии 1-4 из 10) LostFilm (обновляемая)
Downloading [NNMClub.to]_The.Librarians.S03.1080p.LostFilm.torrent torrent
Torrent Библиотекари / The Librarians (2016) WEB-DLRip [H.264/1080p-LQ] (сезон 3, серии 1-4 из 10) LostFilm (обновляемая) was changed
Add new [NNMClub.to]_The.Librarians.S03.1080p.LostFilm.torrent
Failed update Библиотекари / The Librarians (2016) WEB-DLRip [H.264/1080p-LQ] (сезон 3, серии 1-4 из 10) LostFilm (обновляемая). Reason: Torrent [NNMClub.to]_The.Librarians.S03.1080p.LostFilm.torrent wasn't added
End checking for nnmclub.to
```

При этом торрент успешно добавился в клиент.
Удалил из клиента, заново Execute, тоже самое.
Удалил из клиента, удалил из Monitorrent, заново добавил, тоже самое, в логах failed, на деле всё отлично.

**Comment by werwolfby** [comment]
Т.е. всё работает как надо, но в логах пишет ошибку, и статус соответсвенно с ошибкой?
А если ещё раз запустить (не удаляя из qbittorrent), то изменения не найдены и всё ок?

Думаю стоит подождать rc.4 (это будет последний rc скорее всего), и посмотреть там.
Но если всё работает и просто появляется ошибка, то я думаю, что это не критично.

**Comment by Shooshka** [comment]
Да, всё работает, баг "косметический", если ничего не удалять и сразу запустить ещё раз, то всё равно всё тоже самое.

`Torrent Библиотекари / The Librarians (2016) WEB-DLRip [H.264/1080p-LQ] (сезон 3, серии 1-4 из 10) LostFilm (обновляемая) was changed
Failed update Библиотекари / The Librarians (2016) WEB-DLRip [H.264/1080p-LQ] (сезон 3, серии 1-4 из 10) LostFilm (обновляемая). Reason: Torrent [NNMClub.to]_The.Librarians.S03.1080p.LostFilm.torrent wasn't added
`

**Comment by werwolfby** [comment]
Мне кажеться я нашел проблему, но очень странно все равно

**Comment by Shooshka** [comment]
Всегда готов помочь в тестировании и т.п. ;)

**Comment by werwolfby** [comment]
А можете попробовать внести изменения в файл ```monitorrent/plugins/clients/qbittorrent.py```:
Строка [115](https://github.com/werwolfby/monitorrent/blob/9a318431116345344c999dca17c4a23b1dc8d3d9/monitorrent/plugins/clients/qbittorrent.py#L115):
Заменить
```
torrent = next(torrent for torrent in array if torrent['hash'] == torrent_hash)
```
На
```
torrent = next(torrent for torrent in array if torrent['hash'].lower() == torrent_hash)
```

**Comment by Shooshka** [comment]
Сделал, затем cleanup и рестарт, не помогло, без изменений.

**Comment by werwolfby** [comment]
Вот теперь совсем станно

**Comment by Shooshka** [comment]
Дабы исключить проблемы с конкретным трекером проверил и на другом, всё аналогично, всё работает, добавляет, но в логах ерроры.

> Download new series: Элементарно / Elementary (5, 9)
> Add new Elementary.S05E09.1080p.rus.LostFilm.TV.mkv.torrent
> Failed update lostfilm series: Elementary. Reason: Torrent Elementary.S05E09.1080p.rus.LostFilm.TV.mkv.torrent wasn't added

qBittorent 3.3.8 --> qBittorent 3.3.9, но тоже не имеет отношения :)

**Comment by werwolfby** [comment]
Что проблема не с трекером - это факт
Ошибка в том месте, где торрент файл уже скачан и добавлен в клиент, но найти добавленный в клиент **monitorrent** уже почему-то не может.
Это явно проблема с **qbittorrent** плагином.

**Comment by Shooshka** [comment]
Пофиксил.

>                 time = torrent.get('addition_date', None)

Из доки по API:

> addition_date API4	integer	When this torrent was added (unix timestamp)

**Comment by werwolfby** [comment]
Блин, а как мы это тестили тогда. 
Сможете пул реквест формить?

**Comment by werwolfby** [comment]
И согласно доке **addition_date** не у этого эндпоинта возвращается

**Comment by Shooshka** [comment]
Сделал пулл реквест, не уверен, что всё верно, но было интересно :)
Ну тем не менее после замены на addition_date проверил уже по всякому, всё работает, добавляется и т.п.

Единственное ещё что:

> Last update: not specified

Так и должно быть при начальном добавлении отслеживаемой раздачи или даже после самого первого обновления должна быть тут верная дата?

**Comment by werwolfby** [comment]
Вот в этом собственно и проблема :)
Вы таки не прочитали дату добавления :)

**Comment by werwolfby** [comment]
Проблема в строке [120](https://github.com/werwolfby/monitorrent/blob/9a318431116345344c999dca17c4a23b1dc8d3d9/monitorrent/plugins/clients/qbittorrent.py#L120), а вы читаете поле которого нет (```addition_date``` отсутствует зато присутствует таки ```added_on```), и строчка 120 скипается строкой 119.

**Comment by werwolfby** [comment]
Все ещё более сложно :)
```added_on``` не документированное свойство, ни в 3.1 ни в 3.3 не могу найти его описание.
И у нас в тестах ожидается, что это строка, наверное так когда-то и было, сейчас это unix timestamp.

**Comment by werwolfby** [comment]
Да, так и есть:
https://github.com/qbittorrent/qBittorrent/commit/2cef805ab67ab126050e5c1413e5d569ae6858b4
Они поменяли поведение этого поля 28 Апреля, в какой релиз это вошло, хз

**Comment by Shooshka** [comment]
Угу, принято, понятно, пулл реквест убрал :)

**Comment by Shooshka** [comment]
Да, отлично, теперь всё парсит как надо, ну и ерроров естественно нет.
Большие спасибы! ;)

**Comment by werwolfby** [comment]
Не за что.
Но нас всегда можно поддержать, на главной есть ссылка :)

**Comment by Shooshka** [comment]
Хе-хе, сначала поддержал, потом уже прочитал данное сообщение, но не суть.
Творческих узбеков, развития Вам и прочего-прочего!

**Comment by werwolfby** [comment]
Огромное спасибо, теперь точно придется кинозал добавлять :)
