### ISSUE TITLE
Проблемы с nnmclub через прокси

### ISSUE THREAD

**Issue by Shooshka** [werwolfby/monitorrent#167]
Собственно обсуждалось уже, дублирую скрины сюда.

![](http://ishoo.ru/pic/16-12-2016_09-01-08.png)
![](http://ishoo.ru/pic/16-12-2016_09-03-32.png)

**Comment by werwolfby** [comment]
@Shooshka поставил локально себе tinyproxy в контейнере для тестирования.
Как http так и https отработало без проблем и всё скачалось:
```
CONNECT   Dec 18 21:41:27 [38]: Connect (file descriptor 6): 172.17.0.1 [172.17.0.1]
CONNECT   Dec 18 21:41:27 [38]: Request (file descriptor 6): GET http://nnmclub.to/forum/profile.php?mode=viewprofile&u=xxxxxxx HTTP/1.1
INFO      Dec 18 21:41:27 [38]: No upstream proxy for nnmclub.to
CONNECT   Dec 18 21:41:27 [38]: Established connection to host "nnmclub.to" using file descriptor 7.
INFO      Dec 18 21:41:28 [38]: Closed connection between local client (fd:6) and remote client (fd:7)
CONNECT   Dec 18 21:41:28 [39]: Connect (file descriptor 6): 172.17.0.1 [172.17.0.1]
CONNECT   Dec 18 21:41:28 [39]: Request (file descriptor 6): CONNECT nnmclub.to:443 HTTP/1.0
INFO      Dec 18 21:41:28 [39]: No upstream proxy for nnmclub.to
CONNECT   Dec 18 21:41:28 [39]: Established connection to host "nnmclub.to" using file descriptor 7.
INFO      Dec 18 21:41:28 [39]: Not sending client headers to remote machine
INFO      Dec 18 21:41:29 [39]: Closed connection between local client (fd:6) and remote client (fd:7)
```
Как видно по логам, все отработало даже для https

**Comment by werwolfby** [comment]
Ну и по ошибке похоже, что при попытке скачать получаем html, а не torrent файл, нужно будет этот момент тоже правильнее обработать.

**Comment by Shooshka** [comment]
Логи прокси идентичные.
Сегодня попробовал переставить ОС на vps с нуля, сменив дистриб + переставить с нуля monitorrent на винде с читой БД, без изменений, такие же ошибки. :(

**Comment by werwolfby** [comment]
Проблема не была обнаружена при **free**шных раздачах, на закрытых был воспроизведена очень быстро.
Прокси настройки не передаются при скачивании торрент файла, т.е. логин верификации и всё остальное работает через прокси, а торрен скачивается без.
Проблема есть у всех треккеров кроме **lostfilm**.

**Comment by werwolfby** [comment]
@Shooshka как подтвердите что всё работает, релизну новый rc.4

**Comment by Shooshka** [comment]
@werwolfby Поставил, всё прекрасно работает.
