### ISSUE TITLE
Проблемы с rutracker.org

### ISSUE THREAD

**Issue by abaistov** [werwolfby/monitorrent#168]
Обнаружилась следующая проблема, спустя 2-3 дня после добавление учетной записи rutracker - перестали парситься раздачи. Ошибка : 

> FAILED
> Failed update Бруклин 9-9 / Brooklyn Nine-Nine / Сезон: 4. Reason: Can't download url. Status: 404

(аналогичная ошибка и на других раздачах)
ОС - `Ubuntu 16.04.1 LTS `

Запускаю следующим образом : в `/etc/rc.local `прописана строка `/opt/transmission/MoniTorrent/start.sh &`
Содержимое файла start.sh

```
#!/bin/bash
cd /opt/transmission/MoniTorrent/
/usr/bin/python server.py &
```

**Comment by werwolfby** [comment]
gitter:
Короче очень прикольная бага оказалась, сейчас на rutracker старая кука может устареть.
Для проверки того что кука все ещё работает, мы посылаем реквест на профайл текущего пользователя, и если мы можем его просмотреть, тогда все ок, кука валидна.
Но по факту оказалось, что это не так, и либо рутрекер не проверят куку для этой страницы вовсе, либо не проверят, что она устарела.
Наверное профайл пользователя может просмотреть каждый, даже не залогиненный пользователь (раньше это было не так).
И как результат, по факту кука устарела, но узнаем мы об этом только при попытке скачать торрент, а не в шаге верификации. И при попытке скачать нас редиректит на логин.
Проверка на то что торрент умер, происходит при попытке скачать торрент, и если получаем редирект, то считается, что торрента нет больше. Что и происходит в нашем случае.
В общем было сложно понять, что проблема в нашем способе верификации. Потому он и работал 3 дня, а потом перестал. И поломанно это уже давно.
Всё подчинил, завтра проверю на юнит тестах и закомитаю ченджи, если успею.
Было дольше, чем я расчитывал.
