### ISSUE TITLE
Удаление предыдущей раздачи из клиента

### ISSUE THREAD

**Issue by Shooshka** [werwolfby/monitorrent#172]
Прошелся взглядом по issue, не нашёл такого wish'a ;)

Сэкономило бы кучку времени наличие такой галки у торрентов.
Для однотемных(обновляемых) раздач - удалять из списка предыдущую раздачу при успешном добавлении новой.
Для "посерийных" раздач - удалять из списка предыдущую серию при успешном добавлении новой.
Ну собственно как в ТМе реализовано.

**Comment by werwolfby** [comment]
Для однотемных(обновляемых) раздач оно и так работает.

**Comment by Shooshka** [comment]
Да, прошу прощения, чистил сегодня раздачи, которые рсс-загрузчиком тянутся с трекеров, которые пока не поддерживаются мониторрентом, спутал с мониторрентовыми в общем, глянул в логи, всё верно, обновляемые корректно удаляются. Тогда просто считать за пожелание удалять посерийные :)

**Comment by werwolfby** [comment]
Удалять торренты не удаляя скачанные файлы?
Вообще это можно конечно.

Есть нюансы, которые меня смущают, позже опишу.

P.S. А как же повисеть на раздаче? ;)

**Comment by Shooshka** [comment]
Верно.

P.S. Ну так примерно неделю ж висит до выхода следующей серии, новая серия вышла - на старой можно не висеть. Галка-то опциональная и тем у кого например клиент на дохленьком насе/роутере и т.п. - каждая активная раздача на счету. :)

**Comment by werwolfby** [comment]
В общем мои сомнения:

Как обычно для примера возьмём **lostfilm**, с остальными всё проще, но вот с **newstudio** будет тоже самое.

И так, добавляя какой-то сериал на закачку в **lostfilm**, плагин по умолчанию скачает только самую последнюю серию - и это будет всего лишь один торрент в клиенте. 
Но иногда мне охото скачать сериал с самого начала, с 1-го эпизода, 1-го сезона. Для этого я редактирую торрент в мониторренте и указываю последнюю скачанную серию (1-й сезо, нулевой эпизод). И после этого в клиент добавятся все серии данного сериала которые есть на лостфильме. Плагин не глуп и может качать сезонами если таковые выложены (по крайней мере так планировалось :)).
И как результат одна тема в мониторренте приводит к множеству торрентов в торрент клиенте.

Как теперь быть? При следующем запуске удалить всё что уже скачалось, с прошлого запуска? Или только последнюю серию :)

Если удалять всё, то и хранить придётся все добавленные хеши и апдейтать их.
В общем имплементация не оправданно сложна, но если сильно будет надо, то конечно сделаем, когда более приоритетные таски решим.

Поэтому когда у меня трансмишен запускался на роутере у меня был скриптик который, сортировал закачки ratio и удалял закачки с максимальным ratio, чтобы в трансмишене всегда было не больше 30 завершенных закачек. И скрипт ранался по крону. Попробуй найти.

**Comment by werwolfby** [comment]
Надо будет второй веник подключить, который раньше к роутеру был подключен, завтра подключу.

ИМХО, скрипт был удобнее чем галочка в мониторренте, потому что не только мониторрент добавляет что-то в закачки, но и я руками сам добавлял. 

А так же желательно подольше оставаться на раздачу, поэтому удалялось в первую очередь, то, что уже и так хорошо раздалось.

**Comment by Shooshka** [comment]
> Для этого я редактирую торрент в мониторренте и указываю последнюю скачанную серию (1-й сезо, нулевой эпизод).

Ого, не знал о такой фишке, надо опробовать, в таком случае да, не очень вяжется данная хотелка, хотя можно же и после того как скачав весь неполный сезон вышла новая серия - убирать всё предыдущее.

Но собственно это всего лишь хотелка, опциональная по галке, так что можно и закрывать issue, если не планируется делать ;)

**Comment by werwolfby** [comment]
Закрою когда скрипт откопаю :) 
Жаль что он только для трансмишена.

А закачивание сразу всех эпизодов будет доступно и для **newstudio**.

**Comment by werwolfby** [comment]
@Shooshka сомневаюсь, что ещё актуально, но скрипт я нашёл: https://gist.github.com/werwolfby/bea8a01c1928c6d79ebf86d621119da5
Дата создания скрипта: 26-05-2013
