### ISSUE TITLE
Символы в путях скачки

### ISSUE THREAD

**Issue by Shooshka** [werwolfby/monitorrent#175]
Win 10 x64
qBittorrent latest
monitorrent latest

Сегодня, добавляя It's Always Sunny in Philadelphia с путём сохранения Z:\lalalala\It's Always Sunny in Philadelphia\Season 12\ заметил, что кто-то "съедает" "'" видимо и скачка идёт по пути по умолчанию, а не в нужную директорию.

При ручном добавлении в qbittorrent с таким путём всё нормально, посему завожу issue ;)

**Comment by werwolfby** [comment]
Надо наверное всё перевести на python 3 и тогда все эти проблемы с символами исчезнут, оставить python 2 как поддерживаемый, но не основной язык. 
Потому что, слишком много у нас пробем с unicode символами

**Comment by werwolfby** [comment]
Фиксается переездом на 3-й питон.
