### ISSUE TITLE
rutracker error

### ISSUE THREAD

**Issue by impalex** [werwolfby/monitorrent#180]
Перестал работать rutracker.
Поменялось название куки bb_data на bb_session.
После быстрой замены bb_data->bb_session работает как раньше.

**Comment by werwolfby** [comment]
@impalex не могли бы оформить pull request?

**Comment by impalex** [comment]
Окей, сейчас сделаем.

**Comment by werwolfby** [comment]
Можно не спешить, всё равно только вечером смогу проверить и запушить

**Comment by werwolfby** [comment]
Fixed by #181
