### ISSUE TITLE
Сборка docker x86 для версии 1.1.0

### ISSUE THREAD

**Issue by huksley** [werwolfby/monitorrent#184]
Последняя доступная - v.1.1.0-rc.6 
Сделайте пожалуйста новую сборку для версии 1.1.0
но не для armhf а для x86

Или подскажите как собрать самому
я сделал вот так
https://github.com/huksley/alpine-monitorrent

но у меня не запускается 
```
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    from cherrypy import wsgiserver
ImportError: cannot import name 'wsgiserver'
```

**Comment by werwolfby** [comment]
Так есть же, версия 1.1.0

**Comment by werwolfby** [comment]
Только что проверил:
```
docker run -d -p 6687:6687 --name monitorrent werwolfby/alpine-monitorrent:1.1.0
```

**Comment by werwolfby** [comment]
И блин забыл x86 Dockerfile залить

**Comment by werwolfby** [comment]
Пошнул докер файл для x86, очень поход на ваш, я им образ собираю

**Comment by werwolfby** [comment]
@huksley ну что? можем ишью закрывать?

**Comment by werwolfby** [comment]
#185 - вот, ```cherrypy``` совсем недавно внесли эти изменения, поэтому всё ломается.
Мой образ собрался без проблем у меня на машине потому что переиспользовал слои из предыдущего релиза (1.1.0-rc.6, а может и более раннего), поэтому с ним всё хорошо

**Comment by huksley** [comment]
Да вижу, буду следить за #185

**Comment by huksley** [comment]
Спасибо!

**Comment by werwolfby** [comment]
@huksley а с докер хаба 1.1.0 установить смогли?

**Comment by huksley** [comment]
Да но только как  `docker pull werwolfby/alpine-monitorrent:1.1.0`
наверное потому что я билдил из своего проекта.

А кстати какую папку замаунтить через -v чтобы настройки не слетали??? Не вижу.

**Comment by huksley** [comment]
Помоему нашел /var/www/monitorrent/monitorrent.db

**Comment by werwolfby** [comment]
Да это он
