### ISSUE TITLE
lostfilm problem

### ISSUE THREAD

**Issue by Shooshka** [werwolfby/monitorrent#193]
Переехали на новую версию сайта.
Старая доступна по http://old.lostfilm.tv/

**Comment by werwolfby** [comment]
![image](https://cloud.githubusercontent.com/assets/705754/22622512/44d3eff4-eb4d-11e6-8512-ffcbf76c6d24.png)
Looks at least strange, very strange.
But I'm parsing **SD** string

**Comment by werwolfby** [comment]
![image](https://cloud.githubusercontent.com/assets/705754/22622527/9a6089f0-eb4d-11e6-9c1c-10f8e7937c03.png)
Bugs and bugs on new design... :(
And I'm afraid this is the same episode with different quality uploaded to different episodes.

**Comment by werwolfby** [comment]
![image](https://cloud.githubusercontent.com/assets/705754/22622551/1f5fbc2a-eb4e-11e6-8086-732db5035b96.png)
😄

**Comment by werwolfby** [comment]
Was fixed quite fast, we still has episode 2, but without any torrent files.

**Comment by werwolfby** [comment]
Urls with: **\_** in cat doesn't work, and is not redirected by lostfilm itself:
https://www.lostfilm.tv/browse.php?cat=_301 not redirect to right show
https://old.lostfilm.tv/browse.php?cat=_301 - works without any issues
