### ISSUE TITLE
add rutor mirrors

### ISSUE THREAD

**Issue by lodgnewt** [werwolfby/monitorrent#194]
please add .info .is mirrors to download torrent 
http://rutor.info/torrent/472

**Comment by werwolfby** [comment]
It has to work already

**Comment by lodgnewt** [comment]
меня все зеркала перенаправляют на vip-tor.org, тоже работает?

**Comment by werwolfby** [comment]
Нет, vip-tor.org не работает, он перенаправляет меня на rutor.org
Не могу найти официального подтверждения, что это настоящее зеркало

Как простой фикс, можете указать vip-tor.org в исходниках:
Файл ```/monitorrent/plugins/trackers/rutor.py``` строка 102,
поменять
```
tracker_domains = ['rutor.info', 'rutor.is', 'new-tor.org', 'maxi-tor.org']
```
на
```
tracker_domains = ['rutor.info', 'rutor.is', 'new-tor.org', 'maxi-tor.org', 'vip-tor.org']
```

И все заработает

**Comment by lodgnewt** [comment]
спасибо, и еще такой вопрос, а какой путь пробросить в докер для сохранения всего списка торрентов?

**Comment by werwolfby** [comment]
```
touch /path/on/host/monitorrent.dv
-v /path/on/host/monitorrent.db:/var/www/monitorrent/monitorrent.db
```
Писал по памяти (не могу сейчас проверить), но вроде все верно.

**Comment by lodgnewt** [comment]
файл базы данных бинарный?

**Comment by werwolfby** [comment]
да

**Comment by werwolfby** [comment]
Только что проверил, у меня запустилось всё вот так:
```
docker run -d -p 6687:6687 -v /path/to/monitorrent.db:/var/www/monitorrent/monitorrent.db werwolfby/alpine-monitorrent
```
Файл ```/path/to/monitorrent.db``` создал изначально пустым

**Comment by lodgnewt** [comment]
спасибо получилось, скопировал базу со старого и пробросил в новый контейнер ))

**Comment by werwolfby** [comment]
А ну это самый верный способ )
Ишью закрываем, я так понимаю?

И я как-то не хочу без официальной информации добавлять ```vip-tor.org``` в основной код

Но возможно нужно будет подумать над автоматическими редиректами с ```rutor.info```...

**Comment by lodgnewt** [comment]
закрывайте, но меня он только через впн не директет на вип-тор. а так со всех зеркал только на вип ((

**Comment by lodgnewt** [comment]
в группе публикуют информацию о новых зеркалах https://vk.com/newrutororg

**Comment by werwolfby** [comment]
Ну разводилово же :)

**Comment by werwolfby** [comment]
В общем ладно конечно, тут пароль не обязательно вставлять, но они явно вставляют свою рекламу. И если vip-tor.org еще похож на настоящий, то варианты с группы явный развод

**Comment by werwolfby** [comment]
https://vk.com/rutororg
Во эта группа уже похоже на официальную, но тут live-rutor.org рекламируют

**Comment by werwolfby** [comment]
Ну и вот: https://mobile.twitter.com/rutor_org/status/466659373193125888
