### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by maks123** [werwolfby/monitorrent#198]
На всех трекерах при проверке паролей выходит "Connection failed"
Интернет имеется ))
В чем проблема может быть?

OS ubuntu 16.04 64bit
python 2.7
monitorrent v.1.1.2

заранее спасибо

**Comment by werwolfby** [comment]
А подробнее логи есть?
должен быть стектрейс еще

**Comment by werwolfby** [comment]
и такие вопросы можно еще попытаться обсудить в гиттере: https://gitter.im/werwolfby/monitorrent?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by maks123** [comment]
а где трейсы искать? пробежался по директориям - пусто.
в консоле с параметром --debug тоже тихо.

**Comment by werwolfby** [comment]
Да прям в логах экзекьюта должно быть
Войдите в general, включите developer mode далее в логи, а там любой с ошибкой

**Comment by maks123** [comment]
извиняюсь, моя вина.
Там email надо было вбивать.

**Comment by werwolfby** [comment]
Ну я рад, что всё решилось, а где емэйл нужно было вводить?

**Comment by maks123** [comment]
В форме lostfilma по-молчанию username указан, а вводить надо емейл.

**Comment by werwolfby** [comment]
Вот блин, а я был уверен что переименовал Username в email
