### ISSUE TITLE
Download dir for deluge is retrieved incorrectly

### ISSUE THREAD

**Issue by DSilence** [werwolfby/monitorrent#200]
The correct settings name should be "move_completed_path" instead of "download_location". Download location only represents temp directory for current download

**Comment by werwolfby** [comment]
And `find_torrent` for deluge doesn't work as well 😞

**Comment by DSilence** [comment]
Will take a look at that.

**Comment by werwolfby** [comment]
Examples from gitter (thanks to @dein0s): 
```
{b'name': b'Big Little Lies (Season 01)', b'time_added': 1487623424.0}
```
