### ISSUE TITLE
Добавление нового торрента к списку поддерживаемых

### ISSUE THREAD

**Issue by EvolutionPixG** [werwolfby/monitorrent#201]
Еще бы добавить http://freerutor.org/ к списку. Так как сам сайт по торентам достаточно популярен.

**Comment by werwolfby** [comment]
Если он не требует регистрации, то добавить совсем не долго, вопрос в спросе этого трекера.

**Comment by EvolutionPixels** [comment]
Он требует регистрации.

**Comment by EvolutionPixels** [comment]
Но скачивать торрент файл можно и не регистрируясь.

**Comment by EvolutionPixels** [comment]
Вот тут указана позиция популярности freerutor.org по сравнению с другими http://toptracker.ru/details.php?id=4366
это инфа так для справки.
