### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by roma-sk3** [werwolfby/monitorrent#202]
Привет. Можно ли данное приложение (питоновский сервер) прикрутить к nginx? Чтоб не через шелл его запускать.

**Comment by werwolfby** [comment]
Это как? Я просто не понимаю, как вы планируете это запускать.
Приложение должно быть запущено для того чтобы скачивать новые серии.

А `nginx` я например использую как `reverse-proxy` для `monitorrent`'а.

Да и как по другому юзать `nginx`? Ну как лодбалансер, раздача статики, ну и вроде как всё.

**Comment by roma-sk3** [comment]
**werwolfby**, да, именно как `reverse-proxy` я и имел в виду. Чтобы, грубо говоря, не писать `python3.5 server.py` и не сочинять шелл скрипты, а прописать локейшен в `nginx`. Вроде этого:
```bash
server {
  listen  9000;

  location / {
	 proxy_pass http://127.0.0.1:6687;
  }
}
```

> я например использую как `reverse-proxy` для `monitorrent'а`.

Не поделитесь конфигом?

**Comment by werwolfby** [comment]
Вот мой sites/monitorrent
```
server {
    listen 80;
    server_name monitorrent.myhost;

    location / {
        proxy_pass  http://localhost:6687;
        proxy_redirect off;
        proxy_set_header        Host                $host;
        proxy_set_header        Origin              http://$host;
        include                 /etc/nginx/proxy_params;
    }
}
```

Только всё равно сначала старутется `мониторрент`, который и слушает на порту 6687, а потом `nginx` который редиректит всё запросты с `http://monitorrent.myhost` на `http://localhost:6687`

**Comment by werwolfby** [comment]
Это же вам не php, где на каждый урл он просто будет исполнять php файлы.
И если бы это был пхп вам нужен был бы крон для переодического запуска мониторрента для проверки новых серий

**Comment by werwolfby** [comment]
А у нас `monitorrent` приложение в себе, запустил и всё работает, ничего больше делать не надо, не надо настраивать крон

**Comment by roma-sk3** [comment]
**werwolfby**, все понял, спасибо!
