### ISSUE TITLE
rutracker not working?

### ISSUE THREAD

**Issue by MartinAyla** [werwolfby/monitorrent#207]
Hi

I have added my rutracker credentials and "Check" says: "Connection successfull".

But when I do "Add torrent" on the main page, and input this URL, nothing happens:
http://feed.rutracker.cc/atom/f/1997.atom

Any ideas?

**Comment by werwolfby** [comment]
It is not working with feed, it works with particular torrent like: https://rutracker.org/forum/viewtopic.php?t=5285924

**Comment by MartinAyla** [comment]
Thanks for the reply.

I would like to watch the feed and do automatic downloads.

If I have to manually download individual torrents, I will look for another solution :)

**Comment by werwolfby** [comment]
Monitorrent doesn't support feed, it can watch for particular torrent and download it automatically if torrent will change.

I don't understand, what do you want from monitorrent?

**Comment by MartinAyla** [comment]
Oh, I guess I misunderstood the purpose of Monitorrent.

I thought it could watch a feed from different sites and then filter and download the relevant files.

My usecase is to monitor the NBA forum feed from rutracker and automatically download the torrents from posts with "Condensed" in the name.

**Comment by werwolfby** [comment]
Ok, I got it. 😞 

Sorry, but monitorrent doesn't support such feature yet 😢.
You can watch only for particular torrent.

This is first request from all our users.
