### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Melov** [werwolfby/monitorrent#208]
За основу взят alpine,  используется python3, собирается из стабильной версии
репозиторий с Dockerfile лежит здесь: https://github.com/Melov/monitorrent-alpine
автоматическая сборка здесь: https://hub.docker.com/r/melov/monitorrent/

**Comment by werwolfby** [comment]
А может тогда пул реквест на [https://github.com/werwolfby-docker/armhf-alpine-monitorrent](https://github.com/werwolfby-docker/armhf-alpine-monitorrent)?
Просто зачем плодить образы?

**Comment by Melov** [comment]
хорошо, сделаю пулл реквест туда, просто приписка armhf немного смутила, образ я собирал под х64, по идее он должен работать под любой архитектурой

**Comment by Melov** [comment]
если у вас есть возможность, проверьте, возможна ли установка моего образа на armhf и x86, в таком случае можно будет просто настроить автоматическую сборку.

**Comment by werwolfby** [comment]
И как вы себе это представляете?
Это точно не будет работать на ARM, я конечно проверю (но только завтра получится), но даю 99.999% что он не заработает. Потому что бинарники `python` скомпилированны под `x86` архитектуру.

Именно по этому я и собирал 2 разных образа.

Когда-то у меня была попытка собрать один образ, но для `x86` использовался `qemu` для эмуляции `arm`, частично работало, но иногда падало с `segmentation fault` я не стал далеко копать потому что в любом случае эмуляция это зло.

А архитектуры `arm` и `x86` слишком разные, чтобы оно могла заработать. И именно поэтому у нас 2 разных докер файла, которые в принципе отличаются только базовым образом, но оба базируются на `alpine`

**Comment by Melov** [comment]
в моем Dockerfile в качестве базовой используется чистый alpine, на который уже ставятся нужные пакеты (python3, curl и wget) принцип по которому Docker выбирает разрядность окружения мне неизвестен, а протестировать сборку x86 и armhf не на чем.

**Comment by werwolfby** [comment]
А под что как вы думаете скомпилирован чистый alpine? Там же чистые бинарники скомпилированные под платформу, `docker` тут никак не помогает, совсем.
Как раз для уменьшения количества образов все и переделано на официальный образ самого `python`, который лучше знает как красиво установить питон на `alpine` и как за собой почистить. Образ `monitorrent` тоже когда-то был на чистом `alpine`. Хотя вот для `arm` он все еще на нем, но я уже ищу варианты не моего базового образа.
Я все еще не за компом и не могу проверить `arm` версию, сделаю утром.

**Comment by werwolfby** [comment]
К сожалению чуда не произошло 😞 
```bash
docker run --rm melov/monitorrent
Unable to find image 'melov/monitorrent:latest' locally
latest: Pulling from melov/monitorrent

627beaf3eaaf: Pull complete 
72ea44fbb809: Pull complete 
48e60af8165d: Pull complete 
f09382d36323: Pull complete 
b35d7b8534b3: Pull complete 
b506ea2c5c64: Pull complete 
a5c9969f743b: Pull complete 
f67b99c0950f: Pull complete 
bacc1c7568ee: Pull complete 
0dcdd61ba7c1: Pull complete 
10f6915225b5: Pull complete 
98b024471c4c: Pull complete 
Digest: sha256:e4001c3f7793c6581b646d7c3a462214ebbdfac95480c42d357e3e44ba6c4b55
Status: Downloaded newer image for melov/monitorrent:latest
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exec format error".
```

**Comment by Melov** [comment]
да, и правда жаль, хоть и собирался образ средствами Docker Hub

**Comment by werwolfby** [comment]
Ну докер хаб не умеет в `arm`. 
Поэтому и собираю все руками.

**Comment by werwolfby** [comment]
@Melov, так что делаем дальше?
Если есть предложения по улучшению образа то я только за, и с радостью приму пул реквесты.
Необходимости в вашем образе я не вижу.

**Comment by werwolfby** [comment]
@Melov, я закрываю эту ишью, и жду пулл реквестов на докерфайл.
