### ISSUE TITLE
[nnmclub.to] Credentials/Settings are not valid Try login.

### ISSUE THREAD

**Issue by eaxdev** [werwolfby/monitorrent#211]
Пытаюсь скачать с `nnmclub.to` раздачу. Вылазит ошибка, что некорректная пара логин/пароль:

    Credentials/Settings are not valid Try login.
    Can't login: Unknown
![logs](https://cloud.githubusercontent.com/assets/13472225/25053779/0f5446c6-2162-11e7-8dff-50ceeba3a499.PNG)
Логин и пароль правильный 100%. 
Использую `tor` и `privoxy`:
![proxy](https://cloud.githubusercontent.com/assets/13472225/25053757/e6163166-2161-11e7-834e-84ad84a6ac0d.PNG)
Если отключить прокси, все нормально скачивает. `rutracker` с прокси при этом работает корректно.

**Comment by werwolfby** [comment]
Я не могу вспомнить но какую-то похожую проблему с прокси мы уже решали :(

**Comment by dein0s** [comment]
Насколько я могу вспомнить из чятика - было что-то похожее из-за таймаута дефолтного.
Но желательно увидеть питоновские логи для уверенности.

**Comment by werwolfby** [comment]
для этого девелоп нужно ставить

**Comment by werwolfby** [comment]
@roma-sk3 если будете в гиттере, то сможем аккуратнее подебажить, сейчас сложно сказать в чём фигня

**Comment by max1666** [comment]
Решения так и не нашли? У меня тоже самое. Разве что прокси никаких не использу.  Две недели все работало четко а сейчас вот:

**Comment by werwolfby** [comment]
Я думаю, что там каптчу надо ввести просто, надо попробовать залогинится через сайт с того же компа где мониторрент или с того же NAT
И ввести капчу потом перепроверить

**Comment by max1666** [comment]
Залогинлся с того же компа - не помогло, все та же ошибка(( Капчи там походу нет в принципе.

**Comment by max1666** [comment]
Помогло поменять session id в monitorrent.db на id из кук браузера.
