### ISSUE TITLE
с qbittorent не хочет работать

### ISSUE THREAD

**Issue by ortop** [werwolfby/monitorrent#223]
C версией 3.3.13 почему-то не хочет работать сабж. С другими клиентами, например, utorrent всё нормально, как только настраиваю и проверяю соединение на qbittorent - пишет постоянно Connection failed и всё. Через адрес http://localhost:[port] в браузере прекрасно заходит на веб-интерфейс торрент-клиента. Даже не пойму куда копать. Подскажите пожалуйста, буду признателен за помощь.

**Comment by Shooshka** [comment]
Откатитесь на 3.3.12 или дождитесь выхода 3.3.14 и всё будет работать, там веб-запросы переделали в 3.3.13 чуток и поломалось всё.

**Comment by ortop** [comment]
Ок, сейчас попробую.

**Comment by ortop** [comment]
Действительно помогло. Спасибо!

**Comment by dein0s** [comment]
https://github.com/qbittorrent/qBittorrent/issues/6887 уже вмержено, ждите фикса в новой версии клиента в ближайшее время.
