### ISSUE TITLE
Не логинится на lostfilm.tv

### ISSUE THREAD

**Issue by ortop** [werwolfby/monitorrent#225]
Lostfilm.tv не работает из-за смены адреса сайта. Как исправить? Будет ли обновление?

**Comment by StarvingDeveloper** [comment]
I just edited lostfilm.py in /opt/monitorrent/monitorrent/plugins/trackers and changed www.lostfilm.tv to delta.lostfilm.tv and restarted monittorent.
Worked for me. Should work for everyone else.

**Comment by ortop** [comment]
Уже адрес сайта прежний. Не пришлось ничего исправлять )

**Comment by werwolfby** [comment]
Бля я как-то даже не заметил проблемы.

**Comment by werwolfby** [comment]
Хотя да, в логах проблема была. Ну сейчас всё ок, зарываю тикет.

**Comment by StarvingDeveloper** [comment]
Funny, but I dont paid attention it's back since it still works on that delta.lostfilm.tv. So maybe it's real implement some kind of easy address change if they will keep play with they address?

**Comment by werwolfby** [comment]
We have plans to do it for each tracker
