### ISSUE TITLE
Поддержка socks5 в docker 

### ISSUE THREAD

**Issue by aekv** [werwolfby/monitorrent#226]
Здравствуйте,

Не могли бы добавить поддержку socks5 прокси в docker образе?

Спасибо

**Comment by kolayuk** [comment]
+1, нужно просто добавить pysocks (pip install pysocks) и перезапустить докер-контейнер, но после каждого обновления это приходится делать руками

**Comment by werwolfby** [comment]
Докер файл находится [тут](https://github.com/werwolfby-docker/armhf-alpine-monitorrent), я совсем забыл про эту ишью, pull requests приветствуется :)
Ну либо со следующим релизом добавлю

**Comment by kolayuk** [comment]
Пытаюсь сделать pull request, make build фейлится на pip install requirments, подозреваю что из за FROM werwolfby/armhf-alpine-python (там походу pip нет), после замены базового image на  python:3.6.0-alpine все ОК. там точно нужен armhf-alpine-python (не нашел  gitрепозитория с образом)?

**Comment by werwolfby** [comment]
`werwolfby/armhf-alpine-python` - это для ARM девайсов (Raspberry PI и другие).
Для x86 там отдельный [докер файл](https://github.com/werwolfby-docker/armhf-alpine-monitorrent/blob/master/Dockerfile.x86).

**Comment by kolayuk** [comment]
А, то есть ARM образ видимо и не должен на x86 собираться (очевидно тогда что он не может запустить pip тк он под другую архитектуру). Вечером оформлю PR тогда

**Comment by werwolfby** [comment]
Угу, только желательно всё равно в АРМ добавлять, образ я сам проверю тогда вместе с PR

**Comment by kolayuk** [comment]
Можно пропушить еще сюда? https://hub.docker.com/r/werwolfby/alpine-monitorrent/ Или это устаревший image и нужно переключиться на обновленную https://hub.docker.com/r/werwolfby/armhf-alpine-monitorrent/ ? (Судя по названию мне кажется что второе это под ARM, но в репе есть докерфайл под x86, это смущает)

**Comment by werwolfby** [comment]
Нет это действительно 2 имеджа для разных платформ (х86 и АРМ), скоро проапдейчу образ

**Comment by werwolfby** [comment]
@kolayuk а это у нас ещё актуально? Я вроде socks уже закинул в докер.

**Comment by kolayuk** [comment]
@werwolfby спасибо, все есть, можно закрывать
