### ISSUE TITLE
lostfilm.tv changed system again

### ISSUE THREAD

**Issue by StarvingDeveloper** [werwolfby/monitorrent#227]
from: http://www.lostfilm.tv/browse.php?cat=145
to: http://www.lostfilm.tv/series/Game_of_Thrones
as result: Игра престолов / Game of Thrones status changed: Not Found

**Comment by werwolfby** [comment]
That means that there was not changed :)
You can edit this topic, end decrease the latest downloaded episode.
And rerun check.

**Comment by StarvingDeveloper** [comment]
oh, sorry, it's started worked after next check. Looks like you was expecting something like that from them and monittorent was prepared :)
