### ISSUE TITLE
Проблема с проверкой трекеров

### ISSUE THREAD

**Issue by V0v1kkk** [werwolfby/monitorrent#229]
Добрый день.

Раздачи в мониторинг добавляются, но при попытке проверить возникает ошибка.
(windows 2012, версия 1.1.5, проблема со всеми трекерами, ридонли флаг с папки с программой снимать пробовал)

> INFO
> Begin execute
> INFO
> Start checking for rutracker.org
> INFO
> Credentials/Settings are valid
> INFO
> Check for changes Судьба/Апокриф / Fate/Apocrypha [TV] [01-04 из 25] [Без хардсаба] [RUS(ext), JAP, SUB] [2017, Приключения, Фэнтези, Экшен, Исторический, Сверхъестественное, Драма, HDTVRip] [720p]
> FAILED
> Exception while execute
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 245, in execute
>     TopicSettings.from_topic(topic))
>   File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 315, in add_torrent
>     return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
>   File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 101, in add_torrent
>     raise Exception(u'Torrent {0} wasn\'t added'.format(filename))
> Exception: Torrent [rutracker.org].t5424372.torrent wasn't added
> 
> INFO
> Check for changes Доктор Кто / Doctor Who / Сезон: 10 / Серии: 1-12 из 12 + Рождественский эпизод (Стивен Моффат) [2017, Великобритания, Фантастика, приключения, комедия, WEB-DLRip] MVO (BaibaKo) + Original + Subs (Rus, Eng)
> FAILED
> Exception while execute
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 245, in execute
>     TopicSettings.from_topic(topic))
>   File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 315, in add_torrent
>     return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
>   File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 101, in add_torrent
>     raise Exception(u'Torrent {0} wasn\'t added'.format(filename))
> Exception: Torrent [rutracker.org].t5389519.torrent wasn't added
> 
> INFO
> End checking for rutracker.org
> INFO
> End execute

**Comment by werwolfby** [comment]
Похоже на ошибку с настройкой торрент клиента, у вас что? transmission, deluge, uTorrent или qtorrent?

**Comment by V0v1kkk** [comment]
Я вообще не настраивал клиент. Это обязательно?
Я пока просто хочу, чтобы приходили оповещения в Telegram.

**Comment by werwolfby** [comment]
Ну да обязательно, иначе мониторрент не сможет скачать торрент.
В телеграм приходят сообщения о успешном начале загрузки торрента.

**Comment by werwolfby** [comment]
Задача мониторрента в автоматической закачке новых торрентов.

**Comment by V0v1kkk** [comment]
Не очень удобно, если честно.
Мониторить и качать можно, а просто мониторить - нет.
Можно feature request оставить?

**Comment by werwolfby** [comment]
Можно оставить реквес, но вы первый кому это не удобно 😄

**Comment by V0v1kkk** [comment]
Кейс: monitorrent установлен на VDS рядом с VPN-сервером. Подключение к торрент-клиенту возможно только в случае если клиент подключён к VPN.
Хотелось бы, чтобы monitorrent не спамил в данном случае ошибками, а просто оповещал об изменение торрента, решение о старте загрузки торрента отставлял юзеру.

**Comment by werwolfby** [comment]
А закачивать вы их потом будете руками? Если так то вам лучше подойдёт http://litr.cc/.

**Comment by V0v1kkk** [comment]
Можно и руками.
Хотя бы поддержите кейс с тем, что нет связи с клиентом. Чтобы детект изменений не был завязан на коннекцию с клиентом. Вы вроде на хабре писали, что юзаете какую-то библиотеку для парсинга torrent-файлов...
Допустим изменился торрент - клиент получил сообщение, что торрент изменился, не удалось стартовать загрузку т.к. до клиента не достучаться. Как только коннект появился - стартовать загрузку, дополнительно уведомлять юзера.

**Comment by werwolfby** [comment]
Так как у нас нет постоянного коннекта с клиентом (и это логично), то для такой функуиональности нужно будет переодически проверять коннект с клиентом.
А если откладывать закачку, то нужно где-то хранить уже скачанные торренты, а потом ещё трекать, что для лостфильма например нужно хранить все скачанные торренты ибо за какое-то время пока появится коннект с клиентом может выйти несколько серий. А для некоторых раздач, хранить только последнию, а это снова новая логика.
Если вы так не хотите то можете настроить downloader клиент. Он будет просто скачивать torrent файлы в папку и забивать на них, это как раз решение для вас.

**Comment by werwolfby** [comment]
downloader - это тоже клиент, который просто кладёт скачанный торрент-файл в папку.

**Comment by V0v1kkk** [comment]
Да, за исключением неинформативных имён файлов, downloader отлично подходит.
_Спасибо за наводку._

**Comment by werwolfby** [comment]
Имена файлов не информативны потому что клиенту передаётся не файл, а его содержимое. А файл - это хеш торрента, по нему потом ищется уже добавленный торрент например.

**Comment by corpsee** [comment]
@werwolfby А я пытался для начала просто попробовать Monitorrent без скачивания и долго не мог понять в чем проблема, пока на эту тему не набрел.

Мне кажется, нужно как минимум, описать в этот момент в документации (Wiki). Что для того, чтобы все нормально работало, нужно настроить downloader или другой клиент. И что без какого-либо клиента проверки вообще не будут работать.

Еще, мне кажется, было бы логично выводить какую-то человекочитаемую ошибку, что ненастроен клиент, а не только стектрейс.

В любом случае, спасибо за программу и вашу работу!

**Comment by werwolfby** [comment]
@corpsee, да согласен или вместо ошибки варнинг выкидывать.
В общем документацию я писать не умею 😄 так что смогу это только в коде потом сделать, это я с большего умею
