### ISSUE TITLE
Выполнение скрипта после завершения загрузки

### ISSUE THREAD

**Issue by Impeck** [werwolfby/monitorrent#232]
Заранее извиняюсь если это уже было, но, к сожалению, поиск не дал результатов на этот вопрос.

Выполнение скрипта после завершения загрузки возможно?

**Comment by werwolfby** [comment]
Ну мониторрент совсем не трекает загрузку торрента, или вас интересует только загрука самого торрент файла?

**Comment by Impeck** [comment]
Спасибо, что не оставили без внимания.

Решили задачу при помощи Transmission. По завершении загрузки он может выполнять скрипт и передавать данные о том, что именно загрузилось.

**Comment by werwolfby** [comment]
Я именно также решаю эту задачу :)
