### ISSUE TITLE
Win 10 x64 "Connection failed"

### ISSUE THREAD

**Issue by avb1980** [werwolfby/monitorrent#233]
Установка версии под Windows,  не коннектиться ни к одному из трекеров. (фаерволы отрубал, сайты не режутся)
Логин и пароль - сохранен, ошибка возникает при нажатии на check

**Comment by werwolfby** [comment]
Очень и очень странно, а версия из релиза?

**Comment by avb1980** [comment]
MonitorrentInstaller-1.1.5.msi
Проверялось Windows 10 х64 (1703 15063.674) и 2х машинах с (1709 16299.19)
На двух был дефендер (с разными релизами ос) на одной eset.

**Comment by werwolfby** [comment]
Логин и пароль не на русском языке?

**Comment by avb1980** [comment]
Всё на английском

**Comment by werwolfby** [comment]
Да с логами небольшая беда, есть ишью на это
Но не понятно, что за проблема с трекерами, у меня всё работает, я ещё на выходных проверю дополнительно Windows версию, потому что у меня всё ранается на ARM Linux, но много у кого Windows.

**Comment by avb1980** [comment]
Продолжение, программу удалял (через стандартный виндозный), потом решил снова всё проверить. Сказал поставить, начала ругаться что типа она тут есть. Сказал тогда отрепайрить. Поставилась и заработала через прокси. Сказать что не понимаю - ничего не сказать :(
Операцию проделал на одной из win 10x64 (1709 16299.19)
Ну, тогда в любом случае, остаётся просьба о расширенном логировании.

**Comment by lonsdaleite** [comment]
Такая же проблема с Debian Jessie (на роутере ZyXEL Keenetic III) и на MacOS High Sierra. Не подключается ни к одному трекеру.
Один раз каким-то образом подключилось к Lostfilm. Но после перезапуска сервиса снова не работает. Релиз последний.
Логопассы правильные, с браузера без прокси нормально работает.

**Comment by Shooshka** [comment]
Сиё удивительно, но у меня внезапно тоже перестал коннектится к трекерам, до прокси доходит и всё =( В логе "Check for changes" и висит часами, точнее днями) Пошёл реинсталлить)

**Comment by Ovsyanka** [comment]
У меня аналогичная ситуация. Выяснил, что в моем случае не выполняется условие, так как uid и bb_data равны null. Покопался в коде - не нашел где они вообще устанавливаются при тесте соединения.

```python
# monitorrent\plugins\trackers\rutracker.py:179
if not username or not password or not cred.uid or not cred.bb_data:
```

Возможно, эта информация будет полезна.

**Comment by werwolfby** [comment]
Закрываю за давностью
