### ISSUE TITLE
Не стартует закачка с Kinozal

### ISSUE THREAD

**Issue by DmitryRibalka** [werwolfby/monitorrent#241]
Какие-то работают, какие-то нет
Например эта http://kinozal.tv/details.php?id=1591233. После запуска время обновления не меняется "Last update: not specified". Хотел продебажить, но видно невдаха.

**Comment by werwolfby** [comment]
@DmitryRibalka заработало?

**Comment by DmitryRibalka** [comment]
@werwolfby заработало само, что-то было с версткой. Если что-то вылезет, то буду уже дебажить.

**Comment by DmitryRibalka** [comment]
@werwolfby  Вроде понял почему, не у всех новых торрентов есть дата обновления
вот например http://kinozal.tv/details.php?id=1605266
