### ISSUE TITLE
Connection failed in utorrent

### ISSUE THREAD

**Issue by ihorpadalko** [werwolfby/monitorrent#242]
При старте сервера пишет такой ворнинг:
c:\Program Files (x86)\Python36\lib\site-packages\alembic\util\messaging.py:69:
UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy
.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object a
t 0x03ABC730>
  warnings.warn(msg)
Server started on 0.0.0.0:6687

Далее при проверке конекта с utorrent - connection failed. 

Сам utorrent висит на локалхосте на порту 8080, юайка работает без проблем. 

Система: Windows server 2008 R2 SP1. Фаервол отключен, антивируса нет. 

Ошибка имеется на виндовой инсталяции через msi и через распаковку архива с последующим ручным запуском с помощью python server.py

utorrent последней версии на данный момен (3.5.1), установлен из официального сайта
В чем может быть проблема? 

<img width="1179" alt="screen shot 2018-01-19 at 18 38 28" src="https://user-images.githubusercontent.com/24293571/35161164-0cc1a7a6-fd48-11e7-92b2-5ecf939c5c5d.png">

**Comment by werwolfby** [comment]
@ihorpadalko warning - это ничего страшного ни на что сейчас не влияет (надо будет посмотреть что sqlalchemy у себя поменяли, что варнинг начал валиться)

А можете попробовать в качестве хоста указать не *localhost* а *http://localhost*?

**Comment by ihorpadalko** [comment]
http://localhost
Так получилось. Странно, раньше не подключалось. Правда перед настройкой оновил программу до 1.1.6
Попробую добавить несколько торрентов на слежение, посмотрим. 
Спасибо :)

**Comment by werwolfby** [comment]
В общем http://localhost - это явно наша ошибка :)
Будем фиксать

**Comment by werwolfby** [comment]
В остальном @ihorpadalko могу закрывать ишью?

**Comment by ihorpadalko** [comment]
Да, можно закрывать. Спасибо )
