### ISSUE TITLE
lostfilm

### ISSUE THREAD

**Issue by tezdal** [werwolfby/monitorrent#246]
INFO
Begin execute

INFO
Start checking for lostfilm.tv

INFO
Credentials/Settings are not valid Try login.

FAILED
Can't login: Unknown

INFO
End checking for lostfilm.tv

INFO
End execute

Логин и пароль правильный.
Работало 2 дня назад, сейчас просто не понятно что оно хочет от меня)
Страницы сериалов парсятся, но скачать что либо невозможно
Прокся менялась, были попытки запуска без нее

**Comment by werwolfby** [comment]
Судя по всему #248 должен будет помочь

**Comment by tezdal** [comment]
[#248](https://github.com/werwolfby/monitorrent/pull/248) не помог.
Помогло ручное редактирование файлика monitorrent.db и добавление в поле session id из куков.
Иначе просто не отрабатывалась авторизация

**Comment by werwolfby** [comment]
@tezdal а логин/пароль русских символов не содержит?
меня сейчас логинит абсолютно без проблем

**Comment by tezdal** [comment]
нет. логин мыло пароль тоже без русских символов.
грешу на @ (dog) в мыле, но в принципе не критично.
Один раз подкинул session id в базу и дальше свободен.

**Comment by werwolfby** [comment]
Т.е. в почте есть ещё и @? Помимо раздилителя домена?

**Comment by tezdal** [comment]
нет.
почта вида example.dll@gmail.com

**Comment by werwolfby** [comment]
Ну прям как у меня :) И у меня работает как надо

А там точно именно пароль от lostfilm, а не от гуглового аккаунта?

**Comment by tezdal** [comment]
=) конечно

**Comment by MaksymBilenko** [comment]
Похоже проблема когда в пароле присутствуют `!@#$%^&*()`...

**Comment by werwolfby** [comment]
Похоже что нужно ввести капчу... :(

**Comment by amd838** [comment]
> нет. логин мыло пароль тоже без русских символов.
> грешу на @ (dog) в мыле, но в принципе не критично.
> Один раз подкинул session id в базу и дальше свободен.

Можно поподробнее, Откуда взять session id
