### ISSUE TITLE
lostfilm.tv ошибка закачки

### ISSUE THREAD

**Issue by greatbao** [werwolfby/monitorrent#247]
Сегодня перестала идти закачка с лостфильма по всем раздачам.
Debian 9, обновлений пакетов не производилось
лог ошибок:
```
FAILED
Exception while execute topic
Traceback (most recent call last):
  File "/opt/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/opt/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request
    show = self.tracker.parse_url(topic.url, True)
  File "/opt/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 515, in parse_url
    for season in self._parse_series(soup):
  File "/opt/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 544, in _parse_series
    episode_number = int(play_episode_match.group('episode'))
AttributeError: 'NoneType' object has no attribute 'group'
```
до этого все работало исправно

**Comment by omeshcheryakov** [comment]
Такая же проблема

**Comment by greatbao** [comment]
Лостфильм добавил функционал. Теперь во время закачки серий, можно поставить галку что-бы скаченная серия помечалась просмотренной.
Думаю все дело в некорректной работе парсера из за этого изменения.

**Comment by degorychev** [comment]
Инструкция для тех, кто использует docker-контейнер:
0) Подключаемся к серверу по ssh

1) Получаем список контейнеров:

> #docker ps
> 8a9ab19deb65 werwolfby/alpine-monitorrent:latest   "python server.py" 

2) Первый столбец - нужный нам container id, получаем не сокращенный вид:
> #docker ps -q --no-trunc | grep 8a9ab19deb65
> 8a9ab19deb650e7693c11452b2b0ac3b2fb1d8a0f5236b4b3f13cc780f76d058

3) Копируем этот id и подключаемся к командной строке внутри контейнера:
> #docker exec -it 8a9ab19deb650e7693c11452b2b0ac3b2fb1d8a0f5236b4b3f13cc780f76d058 sh
> /var/www/monitorrent # 

4) В нашем распоряжении имеется пакетный менеджер apk, Устанавливаем и запускам mc
>#apk update
>#apk add mc
>#mc

5) Переходим в папку /var/www/monitorrent/monitorrent/plugins/trackers, выделяем файл lostfilm.py и жмем f4, попадая в режим редактора файла

6)На 446 строке меняем регулярное выражение на 
`^PlayEpisode\('(?P<cat>\d{2,3})\s*(?P<season>\d\d\d)\s*(?P<episode>\d\d\d)'\)$`

7) Сохраняем клавишей f2, выходим из mc клавишей f10, выходим из консоли контейнера командой:
> #exit

8) Перезапускаем контейнер
> #docker restart 8a9ab19deb650e7693c11452b2b0ac3b2fb1d8a0f5236b4b3f13cc780f76d058

**Comment by n0rmed** [comment]
Почему то у меня после внесения изменений в контейнер, он зависает на статусе restarting...

**Comment by tezdal** [comment]
> UPD более правильная версия
> ^PlayEpisode\('(?P<cat>\d{2,3})\s*(?P<season>\d\d\d)\s*(?P<episode>\d\d\d)'\)$


Работает без проблем.

**Comment by werwolfby** [comment]
@greatbao @kolayuk @omeshcheryakov @degorychev @tezdal Всё новые контейнеры выпущены, можно пользоваться 😄 без воркэраундов

@kolayuk спасибо за ПР
@degorychev спасибо за воркэраунд

**Comment by hillout** [comment]
К сожалению на последней версии в docker'e не работает:

Exception while execute topic
Traceback (most recent call last):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request
    show = self.tracker.parse_url(topic.url, True)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 515, in parse_url
    for season in self._parse_series(soup):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 544, in _parse_series
    episode_number = int(play_episode_match.group('episode'))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by werwolfby** [comment]
@hillout а поделитесь ссылкой на сериал, потому что я не могу воспроизвести.

**Comment by hillout** [comment]
Да, конечно: https://www.lostfilm.tv/series/Homeland/seasons

**Comment by n0rmed** [comment]
У меня появилась такая же ошибка при первом запуске на сериале Counterpart. Но сейчас все ок, и даже ночью скачалась новая серия.

**Comment by hillout** [comment]
Очень странно, но сейчас всё заработало. Спасибо anyway.

**Comment by hillout** [comment]
А такой вопрос - если я выбрал сезон и эпизод определённый, то moniutorrent будет парсить только этот эпизод или дальше по списку пойдёт? Или же надо каждый раз выбирать следующую по порядковому номеру серию, чтобы он её скачивал?

**Comment by tezdal** [comment]
если был выбран сезон 3 серия 5
то будет качаться 
сезон 3 серии 6,7,8,9,10
сезон 4 серии 1,2,3,4,5,6,7,8,9,10

Если же выбран Сезон 1 Cерии 0 то будут скачаны все сезоны и серии доступные.
Автоматизация monitorrent как раз таки и построена на том что бы ручками не надо было выбирать следующую, все это автоматизированно проверяется и закачивается.

**Comment by hillout** [comment]
Понятно, спасибо!
