### ISSUE TITLE
просьба в реализации доступа по HTTPS

### ISSUE THREAD

**Issue by LVortex** [werwolfby/monitorrent#249]
сильно затруднит реализовать доступ по HTTPS?

**Comment by werwolfby** [comment]
Ну смотря, что в это вкладывать, я вот на nginx у себя настроил https, а сам по себе monitorrent работает без https.

Если хотите при старте ему указать сертификаты для https, ну и вообще cheroot (апп сервер для monitorrent) вроде как поддерживает ssl, так что добавить это будет не проблема если это так необходимо.

Но остаётся набор вопросов который нужно решить, кто будет поставлять сертификат? Или генерировать и использовать самоподписанный? Нужно ли это интегрировать в процесс инсталяции? и т.п.

В общем технически задача простая, и всё к этому вроде готово, но вот инфраструктурно, тут ещё надо смотреть, + на Windows и на Linux там все слегка подругому.

**Comment by LVortex** [comment]
спасибо. воспользуюсь nginx.
а так хотелось бы в следующих вариантах:
1. генерация самоподписанного и привязка к веб службам. 
2. использование указанного сертификата. в случае Докера - размещение на хостовой машине

**Comment by werwolfby** [comment]
@LVortex я пока это закрою, так как в ближайшее время это не планируется
