### ISSUE TITLE
снова Lostfilm

### ISSUE THREAD

**Issue by tezdal** [werwolfby/monitorrent#250]
INFO
Видоизмененный углерод / Altered Carbon status changed: Ok
FAILED
**Failed get quality "SD" for series: Видоизмененный углерод / Altered Carbon**
INFO
Check for changes МакМафия / McMafia
INFO
МакМафия / McMafia status changed: Ok
FAILED
**Failed get quality "SD" for series: МакМафия / McMafia**

опять что то в верстке у лостфильма?

**Comment by werwolfby** [comment]
@tezdal Я надеюсь, что все заработало?

**Comment by degorychev** [comment]
@werwolfby с stargate: origins такая же штука. На сайте где раньше написано было 1080р теперь написана просто "точка". Хотя с 720р ничего не поменялось. 
Только некоторые сериалы с таким багом, вчера вышли агенты щит, там все четко.

**Comment by werwolfby** [comment]
Понял, значит ещё качество нужно протестировать

**Comment by tezdal** [comment]
Да заработало, но так и не понял в чем была причина
