### ISSUE TITLE
[1.1.6] исключение при добавлении нового торрента

### ISSUE THREAD

**Issue by impalex** [werwolfby/monitorrent#251]
> FAILED
> 
> Exception while execute
> 
> Traceback (most recent call last):
>   File "/opt/monitorrent/service/monitorrent/plugins/trackers/__init__.py", line 245, in execute
>     TopicSettings.from_topic(topic))
>   File "/opt/monitorrent/service/monitorrent/engine.py", line 322, in add_torrent
>     return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
>   File "/opt/monitorrent/service/monitorrent/engine.py", line 88, in add_torrent
>     existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
>   File "/opt/monitorrent/service/monitorrent/plugin_managers.py", line 212, in find_torrent
>     result = self.default_client.find_torrent(torrent_hash)
>   File "/opt/monitorrent/service/monitorrent/plugins/clients/transmission.py", line 83, in find_torrent
>     torrent = client.get_torrent(torrent_hash.lower(), ['id', 'hashString', 'addedDate', 'name'])
>   File "/usr/local/lib/python3.5/dist-packages/transmissionrpc/client.py", line 573, in get_torrent
>     raise KeyError("Torrent not found in result")
> KeyError: 'Torrent not found in result'

По трейсу вроде понятно, что происходит.

**Comment by werwolfby** [comment]
Что-то такое я уже точно фиксал. Это точно не develop?

**Comment by impalex** [comment]
По определенным соображениям я ковыряюсь в develop, ага. Пардон, что не уточнил.
Сейчас нашел коммит, который сломал. Раз для мастера неактуально, можно забыть.
Но тогда вопрос - зачем его в девелопе поломали? :)

**Comment by werwolfby** [comment]
@impalex поломали чисто случайно, а подчинить никак не можем 😞
