### ISSUE TITLE
anidub tracker no longer working (Не работает tracker anidub)

### ISSUE THREAD

**Issue by ZChuckMoris** [werwolfby/monitorrent#260]
Ловлю "connection failed", когда пытаюсь проверить введённые логин и пароль на tr.anidub.com вне зависимости от того, используя я прокси или нет. Также не могут добавить ссылку с АниДаба. В то же время, всё прекрасно работает с трекером rutracker.org при использовании прокси.

I get "connection failed" when I try to check tr.anidub.com username and password, no matter do I use proxy or not. Also I can't add any links from tr.anidub.com. At the same time rutracker.org authorization works well with proxy.

**Comment by ZChuckMoris** [comment]
Нашёл решение в разделе "pull requests".

Found solution in "pull requests"

https://github.com/werwolfby/monitorrent/pull/254

**Comment by werwolfby** [comment]
Релиз 1.1.7 содержит фикс
