### ISSUE TITLE
Anilibria.TV Tracker

### ISSUE THREAD

**Issue by ZChuckMoris** [werwolfby/monitorrent#263]
Добрый день! Скажите, пожалуйста, могу ли попросить написать парсер торрентов с Anilibria.TV? На данный момент из парсеров аниме-сериалов есть только Anidub, но т.к. лично я смотрю аниме преимущественно в озвучке Анилибрии, мне бы очень хотелось, чтобы был парсер и с их сайта. Буду весьма признателен :)

**Comment by ZChuckMoris** [comment]
Я, конечно, много не надоначу, но на нормальную кружку пива я не зажмусь, если реализуешь :)

**Comment by impalex** [comment]
Я когда-то себе делал в форке... вроде работает. Посмотрю, может PR кину.

**Comment by werwolfby** [comment]
Будет доступна в 1.1.7 (выйдет завтра)
