### ISSUE TITLE
qbittorrent connection failed

### ISSUE THREAD

**Issue by DKGraf** [werwolfby/monitorrent#278]
Установил последнюю версию 1.1.8 для винды, имеется qbittorrent 4.1.4 (c 4.1.0 было так же) на том же компе, веб-интерфейс поднят на localhost:8888, установлен пароль, при попытке подключения получаю ошибку. Адрес пробовал прописывать и через http:// и без, и localhost и ip в локальной сети. Пробовал без пароля оставлять - итог такой же, никаких прокси не включено. Куда можно посмотреть? Спасибо

**Comment by werwolfby** [comment]
5 лет прошло почти: закрываю за давностью.
В 1.3.0 все должно будет быть окей.
