### ISSUE TITLE
lostfilm.tv капча на авторизации

### ISSUE THREAD

**Issue by greatbao** [werwolfby/monitorrent#282]
На lostfilm.tv изменился тип авторизации.
Теперь нужно авторизовываться по e-mail адресу вместо логина
плюс добавлена капча (при некорректной авторизации)
в итоге после переустановки сервера, не могу авторизоваться через monitorrent

**Comment by d1mf** [comment]
тоже самое(

**Comment by werwolfby** [comment]
Закрываю за давностью, вроде уже всё должно быть окей.
Для решения проблемы с капчей нужно сначала руками авторизоваться в lostfilm.tv через браузер.
После этого `monitorrent` сможет это сделать тоже.
