### ISSUE TITLE
Anilibria.TV resolution choice (возможность выбора разрешения видео на Анилибрии)

### ISSUE THREAD

**Issue by ZChuckMoris** [werwolfby/monitorrent#284]
С недавних пор на Анилибрии начали выкладывать релизы, помимо 720p, ещё и в 1080p ([пример](https://www.anilibria.tv/release/sword-art-online-alicization.html)) Ввиду того, что наличие подобного выбора не предусмотрено в парсере, он у меня то 720p качает, то 1080p. Т.е., никогда не знаешь, в каком разрешении скачается релиз при выходе следующей серии. Возможно ли внедрить фильтр по разрешению видео, как это реализовано с lostfilm.tv? 
С меня очередной донат на пивас если что, как было при [предудыщем моём запросе по АниЛибрии](https://github.com/werwolfby/monitorrent/issues/263) :)

Not a long time ago AniLibria.TV began to publish releases not just in 720p, but also in 1080p ([example](https://www.anilibria.tv/release/sword-art-online-alicization.html)). Because such kind of choice is not prescribed in parser, it automatically sometimes download 720p, and other times - 1080p. I mean, you never know, in which resolution it will download this release next time new episode appear. Is there any way to implement resolution choise, just like it's done in lostfilm.tv parser?
Of course, that's not request for free, just like [the previous time i asked for AniLibria.TV support](https://github.com/werwolfby/monitorrent/issues/263) :)

P.S. В курсе, что ты знаешь русский. Тут перевод на английский на тот случай, если найдётся чувак, могущий в корректировку питоновских парсеров среди зарубежных ребят :)

P.S.S. Я в курсе, что тогда мою проблему решил @impalex со своим форком, но не нашёл тогда, как ему задонатить, потому донатнул тебе.

**Comment by ZChuckMoris** [comment]
Печаль, ответов больше месяца нет :(

**Comment by ZChuckMoris** [comment]
Печаль, ни одного ответа за 2 месяца нет :(
А ведь почти каждый день мониторю эту ветку на наличие отзыва

**Comment by werwolfby** [comment]
@ZChuckMoris очень извиняюсь за это, но это не мой плагин, и мне его сложно поддерживать 😞. А вот то что я не влил фикс от @impalex которому уже 20 дней, вот это серьёзная проблема. В течении пару дней пофикшу, но как я вижу по фиксу выбора разрешения все ещё нет.

У меня даже аккаунта на anilibria.tv нет :). Так что мне сложно добавить поддержу разрешений туда, ну и времени к сожалению проектам заниматься сейчас тоже нет, но если будет ПРка я её конечно заведу, и не 20 дней спустя :)

**Comment by impalex** [comment]
Аккаунт на анилибрии не нужен, скачивание доступно без него.
С выбором разрешения не всё так просто там. Если несколько торрентов в раздаче, то не факт, что они просто разрешением различаются. Пример - https://www.anilibria.tv/release/persona-5-the-animation.html - два разных торрента, с разным контентом.
В общем, в своё время я не придумал ничего умного и забил на этот вопрос, в большинстве случаев работает и так.

**Comment by werwolfby** [comment]
Ну похоже на ту же проблему почему я до сих пор newstudio не прикрутил 😞 

Ну тогда даже не знаю, что посоветовать. Ишью пока можно не закрывать, вдруг появится решение 😄

**Comment by ZChuckMoris** [comment]
Могу тогда только предложить прикрутить пользовательский фильтр в виде обычной стринги, который будет отдавать предпочтение при обновлении тому критерию, который укажет пользователь в поле. Соответственно, если вышло обновление, которое добавило спэшл-эпизод, он тоже будет загружен, а если выйдет обновление, в котором сразу новая серия в 2 разрешениях, он отдаст предпочтение более высокому разрешению. Я только не знаю сам, как это реализовать в Питоне, так что сам это никак реализовать не могу. В любом случае спасибо, что откликнулись :)

**Comment by ZChuckMoris** [comment]
Могу тогда только предложить прикрутить пользовательский фильтр в виде обычной стринги, который будет отдавать приоритет при обновлении тому критерию, который укажет пользователь в поле. Соответственно, если вышло обновление, которое добавило спэшл-эпизод, он тоже будет загружен, а если выйдет обновление, в котором сразу новая серия в 2 разрешениях, он отдаст предпочтение более высокому разрешению. Я только не знаю сам, как это реализовать в Питоне, так что сам это никак реализовать не могу. В любом случае спасибо, что откликнулись :)

**Comment by werwolfby** [comment]
Правило "отдаст предпочтение" звучит странно и закодить не получится 😄
Есть вариант только если есть подстрока которую указал пользователь, то качать этот торрент, если нету, то игнорировать его.
Т.е. если пользователь ввёл: 720p
То будут качаться только те торренты в которых есть подстрока 720p в названии ссылки (думаю она отличается от имени файла).

И соответсвенно если кто догарается вместо П англиского (p) писать Р (эр) русское, то такой торрент качаться не будет. Ибо 2 буквы выглядят для пользователя одинаково, а по факту для кода они разные. И если думаете, что такого быть не может, то ошибаетесь, я вот когда с rutor развлекался, чтобы тоже информацию из торрентов искать, то там *ОЧЕНЬ* часто пишут 720р или 1080р (где р - это русская буква эр). А ещё часто вставляют пробелы.

Ну для конкретной раздачи скорее всего всё будет работать как надо, но 100% гарантий это не даёт, а очень хотелось бы нормального решения. И я всё никак не соберусь ML прикрутить, чтобы он лучше всё понимал и разбирал. Алгоритмов нормальных тоже не нашёл. Вот поэтому newstudio все ещё нет :(

В общем прикрутить поле не сложно, но я не знаю когда смогу этим заняться 😞. Так что на меня надежды нет в этом плане.

**Comment by ZChuckMoris** [comment]
Я имел в виду другое: думал, что получится внедрить анализатор изменений, который, в случае, если изменений больше, чем 1, будет отдавать приоритет только 1080, либо только 720. Можно было бы тогда это в виде интегера прописать, разрешив только цифры вбивать пользователю в критерий.

Ну, раз не получится, то печально :(
В любом случае спасибо за ответ

**Comment by werwolfby** [comment]
Ну тут все сложнее, не факт, что всегда выкладывают сразу несколько видео, что-то может быть добавлено позже. А значит ваше предложение будет работать не всегда.
И надо что-то более умное, типа если спустя 2 часа не появилось предочитаемого разрешения, то качать ближайшее минимальное.

Плюс за счет того что выходит не по одной серии, могут быть сразу несколько, то сложно понять что новое вышло. В общем не просто это. Нужно много чего парсить сразу.

**Comment by impalex** [comment]
Я, наверное, сделаю всё-таки простой разбор "разрешения" торрента. Самому не нравится возникающая иногда путаница. Но красивого решения для раздач вроде той, которую в пример приводил, у меня нет.
Справедливости ради, подобные раздачи всё-таки скорее исключение... они есть, но большей частью контент у торрентов всё-таки один.

Только не уверен, когда смогу этим заняться.

**Comment by werwolfby** [comment]
@impalex буду ждать, обещаю в этот раз отреагировать быстрее 😏

**Comment by impalex** [comment]
Вроде что-то сделал, вроде что-то работает... Пару дней послежу, как ведет себя, да на выходных закину в тот же PR, раз он все равно открыт.

**Comment by impalex** [comment]
Добавлено #290 
На тех раздачах, что у меня отслеживаются, все работают.
Возможны проблемы с раздачами, в которых торренты с разным контентом, но их черт знает как автоматом обрабатывать, слишком они различаются. Можно смириться, имхо.

**Comment by ZChuckMoris** [comment]
Большое спасибо! Это работает :)
Потестирую ещё в районе недели. Если проблем никаких не возникнет, закрою тему.
@impalex, напишите, куда свою благодарность кидать. Вы и парсер заделали, и выбор разрешения прикрутили, а я до сих пор не знаю, как Вас пивом угостить

**Comment by impalex** [comment]
@ZChuckMoris ну можно налить в https://money.yandex.ru/to/41001929670792. Много не пью. =)

**Comment by ZChuckMoris** [comment]
@impalex, поблагодарил. Сумма небольшая, но надеюсь, что хоть чуть-чуть да порадует :)

**Comment by impalex** [comment]
@ZChuckMoris 乾杯！　🍻
