### ISSUE TITLE
После добавления сериала вылетает ошибка

### ISSUE THREAD

**Issue by makar0nin** [werwolfby/monitorrent#285]
> INFO
> Check for changes Проект «Синяя книга» / Project Blue Book
> 
> FAILED
> Exception while execute
> Traceback (most recent call last):
>   File "/opt/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 785, in execute
>     TopicSettings.from_topic(topic))
>   File "/opt/monitorrent/monitorrent/engine.py", line 315, in add_torrent
>     return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
>   File "/opt/monitorrent/monitorrent/engine.py", line 86, in add_torrent
>     elif self.clients_manager.add_torrent(torrent.raw_content, topic_settings):
>   File "/opt/monitorrent/monitorrent/plugin_managers.py", line 214, in add_torrent
>     return self.default_client.add_torrent(torrent, topic_settings)
>   File "/opt/monitorrent/monitorrent/plugins/clients/transmission.py", line 119, in add_torrent
>     client.add_torrent(base64.b64encode(torrent).decode('utf-8'), **torrent_settings_dict)
>   File "/home/user/.local/lib/python2.7/site-packages/transmissionrpc/client.py", line 414, in add_torrent
>     (arg, val) = argument_value_convert('torrent-add', argument, value, self.rpc_version)
>   File "/home/user/.local/lib/python2.7/site-packages/transmissionrpc/utils.py", line 153, in argument_value_convert
>     return (argument, TR_TYPE_MAP[info[0]](value))
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 38: ordinal not in range(128)

И такое сообщение периодически появляется на других сериалах.

**Comment by werwolfby** [comment]
@makar0nin а по какому урлу добавляете?

У меня была похожая проблема когда я забыл вконце /seasons добавить. Т.е. урл должен быть вида: https://www.lostfilm.tv/series/The_Haunting_of_Hill_House/seasons

В любом случае это баг, но может поможет

**Comment by makar0nin** [comment]
Вроде бы именно такой адрес.

**Comment by werwolfby** [comment]
Тогда скорее всего в ковычках проблема, посмотрю, но не в ближайшие 2 недели 😞

**Comment by makar0nin** [comment]
Наверное стоит уточнить . |Что установка производилась самостоятельно (не docker) , и сделано было по инструкции. Однако сейчас прочитав еще раз Readme решил проверить версии pyton  и pip.
В итоге оказалось 2.7 . Решил попробовать на 3  и теперь 

> FAILED
> Exception while execute
> Traceback (most recent call last):
>   File "/opt/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 785, in execute
>     TopicSettings.from_topic(topic))
>   File "/opt/monitorrent/monitorrent/engine.py", line 315, in add_torrent
>     return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
>   File "/opt/monitorrent/monitorrent/engine.py", line 101, in add_torrent
>     raise Exception(u'Torrent {0} wasn\'t added'.format(filename))
> Exception: Torrent The.Good.Doctor.S02E13.rus.LostFilm.TV.avi.torrent wasn't added

И наверное стоит поправить инструкцию по установке если конкретно 3 версию python и pip к нему. Но думаю это отдельно надо рассматривать

**Comment by makar0nin** [comment]
В итоге ошибка из предыдущего поста возникла как я понял из за того , что после обновления на 3 python клиентом по умолчанию стал qbittorrent вместо настроенного ранее transmission.
