### ISSUE TITLE
Не получается добавить сериал: кнопка Add - не активна

### ISSUE THREAD

**Issue by jMurr** [werwolfby/monitorrent#287]
Появилась странная проблема.
При попытке добавить сериал кнопка Add - не активна.
Добавляю УРЛку например (http://www.lostfilm.tv/series/Curfew/seasons)
Выбираю разрешение (720)
Пишу путь, а кнопка Add не активна...
Cancel - работает...
Уже добавленные сериалы качаются...
![untitled](https://user-images.githubusercontent.com/13546034/53533029-de2ce100-3b01-11e9-9c9b-ba4ce81cb208.png)

**Comment by werwolfby** [comment]
![image](https://user-images.githubusercontent.com/705754/53533094-88a90200-3b0a-11e9-9b51-c0d52d9b24f3.png)
У меня без проблем, надо смотреть в чём проблема :(

**Comment by jMurr** [comment]
У меня были лаги с диском и бп, боюсь как бы БД не побилась, если её Вам выслать сможете глянуть всё ли так?
Или какое-то расширенное логирование могу включить (знать бы как).
Всё дело под десяткой крутится

**Comment by werwolfby** [comment]
Только пароли сначала проапдейтайте 😄, но вообще раз список сериалов виден, то с БД все окей

Ну и кнопка Add никак не связана с БД, это задача фронтенда, тут либо в консоль смотреть, либо в инкогнито сначала попробовать

**Comment by jMurr** [comment]
А бд должна быть200+ мб?
[monitorrent.zip](https://github.com/werwolfby/monitorrent/files/2912914/monitorrent.zip)

Подробнее можете рассказать, что мне надо сделать и что Вам выслать?

**Comment by jMurr** [comment]
Пошёл простым путём:
1. Сохранил старую базу.
2. Удалил приложение полностью.
3. Перезагрузился и удалил оставшиеся папки.
4. Установил заново.
5. Из старой базы экспортировал таблицы (меня только лостфильм интересовал):
- topics
- lostfilmtv_series
- lostfilmtv_credentials
- notifiers
- qbittorrent_credentials
6. Импортировал в новую.
7. Пробежался по настройкам.
Можно было обойтись вообще таблицами topics и lostfilmtv_series а те настройки руками забить...
