### ISSUE TITLE
Из под docker не получается достучаться до transmission на хосте

### ISSUE THREAD

**Issue by o-kos** [werwolfby/monitorrent#288]
Никак не могу подключиться к локальному transmission из под докера в linux. Username и Password гарантировано правильные из под браузера коннект к transmission нормальный. Куда посмотреть?

**Comment by ilya-fedin** [comment]
Проверь, что не стоит какого-нибудь firewalld или ufw. IP должен быть тот, что у тебя стоит на интерфейсе docker0 (по умолчанию 172.17.42.1). Ну и transmission должен на нем слушать (можешь проверить по `netstat -tulp`, если слушает на всех интерфейсах, то в колонке Local Address будет 0.0.0.0:порт).
И банально: у docker run есть аргумент `--net=host`, он позволяет контейнеру использовать тот же network namespace, что и самому хосту (проще говоря - все, что касается сети, будет работать так, как и без докера).

**Comment by o-kos** [comment]
Ok, в режиме --network host заработало по localhost

**Comment by o-kos** [comment]
И вот скорее всего проблема была в этом #240. Догадался поискать только после того, как уже настроил.
