### ISSUE TITLE
Таймаут трейсбека и копипаст URL

### ISSUE THREAD

**Issue by ilya-fedin** [werwolfby/monitorrent#289]
Заметил две напрягающие вещи в UI:
1. Если произошла ошибка, то трейсбек появляется чуть ли не на секунду - не прочитать. Хотелось бы секунд 5-10 хотя бы. Или вообще сделать возможность вручную выбирать, что делать после трейбека - отменять или дальше продолжать.
2. Иногда хочется зайти на страницу с торрентом. Захожу в диалог редактирования, URL там не просто read-only, так даже выделить нельзя. Приходится через инструменты разработчика выковыривать.

**Comment by impalex** [comment]
1. Трейс можно почитать в логе, кликнув там, где написано "Last executed".
![image](https://user-images.githubusercontent.com/13515747/55603689-52a01300-5785-11e9-93db-ff65663d0014.png)
2. Перейти на страницу с торрентом можно кликом по иконке трекера рядом с этим торрентом.
![image](https://user-images.githubusercontent.com/13515747/55603721-85e2a200-5785-11e9-896d-7b957c5313a1.png)

**Comment by ilya-fedin** [comment]
Спасибо! Правда, это как-то совсем неочевидно... Может стоит сделать в readme/wiki гайд по неочевидным функциям?

Кстати, за это время нашел еще один недочет по UX: почему-то сбился пароль от Deluge, однако я никак не мог это понять, потому что оно выдавал трейсбек с текстом "Torrent wasn't added", а инпут с паролем в настройках был заполнен. Несколько недель не мог понять, что же не так, пока не додумался нажать на Test в настройках соединения с Deluge...

По идее, если делать перед добавлением торрента проверку как по кнопке Test и выдавать более конкретную ошибку, то этого можно было бы избежать.

**Comment by werwolfby** [comment]
Да согласен
