### ISSUE TITLE
Не качает торренты ни с одним торрент-клиентом на macOS 10.14.3

### ISSUE THREAD

**Issue by ZChuckMoris** [werwolfby/monitorrent#291]
Обновил все зависимости через pip3 install -r requirements.txt, также установил npm и gulp, скачал последнюю версию с гитхаба и запустил. Вот такую ошибку выдаёт с любым торрент-клиентом (попробовал uTorrent, qbittorrent, Transmission). Не знаю, куда копать. 
На винде проблем нет, а вот на macOS у monitorrent ошибки вылезают.

`
FAILED
Exception while execute
Traceback (most recent call last):
  File "/Users/moris/Desktop/Scripts/monitorrent/monitorrent/plugins/trackers/__init__.py", line 245, in execute
    TopicSettings.from_topic(topic))
  File "/Users/moris/Desktop/Scripts/monitorrent/monitorrent/engine.py", line 322, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "/Users/moris/Desktop/Scripts/monitorrent/monitorrent/engine.py", line 88, in add_torrent
    existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
  File "/Users/moris/Desktop/Scripts/monitorrent/monitorrent/plugin_managers.py", line 212, in find_torrent
    result = self.default_client.find_torrent(torrent_hash)
  File "/Users/moris/Desktop/Scripts/monitorrent/monitorrent/plugins/clients/utorrent.py", line 115, in find_torrent
    torrent = next(torrent for torrent in array if torrent[0] == torrent_hash)
StopIteration`

**Comment by ZChuckMoris** [comment]
откатился на macOS до версии 1.1.6, накатил сверху трекер Анилибрии и внёс свою проксю в telegram.py. Всё работает без проблем. Походу, что-то скорячилось в версии 1.1.7/8/9.

**Comment by ZChuckMoris** [comment]
Заменил ещё плагины uTorrent, kinozal и anidub на новые, но ничего не изменилось: всё также хорошо работает. Не знаю, что именно в новых версиях вызвало такие неполадки.

**Comment by impalex** [comment]
Подтверждаю, что-то сломано в релизе. Ошибка при добавлении нового торрента.

> FAILED
> 
> Exception while execute
> 
> Traceback (most recent call last):
>   File "/opt/monitorrent/service/monitorrent/plugins/trackers/__init__.py", line 245, in execute
>     TopicSettings.from_topic(topic))
>   File "/opt/monitorrent/service/monitorrent/engine.py", line 322, in add_torrent
>     return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
>   File "/opt/monitorrent/service/monitorrent/engine.py", line 88, in add_torrent
>     existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
>   File "/opt/monitorrent/service/monitorrent/plugin_managers.py", line 212, in find_torrent
>     result = self.default_client.find_torrent(torrent_hash)
>   File "/opt/monitorrent/service/monitorrent/plugins/clients/transmission.py", line 83, in find_torrent
>     torrent = client.get_torrent(torrent_hash.lower(), ['id', 'hashString', 'addedDate', 'name'])
>   File "/usr/local/lib/python3.5/dist-packages/transmissionrpc/client.py", line 573, in get_torrent
>     raise KeyError("Torrent not found in result")
> KeyError: 'Torrent not found in result'



Ubuntu 16.04.6 LTS

**Comment by impalex** [comment]
Ясно. Раньше в плагинах клиентов в find_torrent исключения обрабатывались. Сейчас обработка убрана, соответственно find_torrent бросает исключение если торрент не найден, которое нигде дальше не обрабатывается.

**Comment by ZChuckMoris** [comment]
@impalex, вот это действительно без понятия, от чего в винде проблем нет. Я то ладно, накатил себе старую версию 1.1.6 и руками из коммитов файлы засейвил. Однако, в любом случае, нужен фикс, т.к. большинство пользователей не станет ничего пытаться делать (увидят, что не работает и забьют), а жаль, т.к. штука реально крутая.
В Питоне я не шарю, так с фиксом я ничем, к сожалению, не помогу :(

**Comment by ZChuckMoris** [comment]
@impalex, вот это действительно без понятия, от чего в винде проблем нет. Я то ладно, накатил себе старую версию 1.1.6 и руками из коммитов файлы засейвил. Однако, в любом случае, нужен фикс, т.к. большинство пользователей не станет ничего пытаться делать (увидят, что не работает и забьют), а жаль, т.к. штука реально крутая.
В Питоне я не шарю, так что с фиксом я ничем, к сожалению, помочь не смогу :(

**Comment by werwolfby** [comment]
Я вечерком проверю, может не с той ветки собрал 😞 

Ибо такая проблема есть в девелопе, но в релизе все было окей, я просто все во всё мерджил, так что мог случайно не с той ветки собрать 😞

**Comment by werwolfby** [comment]
Черт :) У меня дома тоже сломано :)
Так что соберу сегодня новую версию, сорри

**Comment by ZChuckMoris** [comment]
Спасибо! :)

**Comment by werwolfby** [comment]
https://github.com/werwolfby/monitorrent/releases/tag/1.1.10 вышел, проверяйте, если всё, то закройте плиз ишью

**Comment by ZChuckMoris** [comment]
Супер! Спасибо, теперь всё работает прекрасно с:
![image](https://user-images.githubusercontent.com/18584322/55588150-b3076400-5735-11e9-9c88-5d22391b49a2.png)
