### ISSUE TITLE
lostfilm stopped working

### ISSUE THREAD

**Issue by CooleRnax** [werwolfby/monitorrent#292]
no errors just red background

**Comment by CooleRnax** [comment]
INFO
Check for changes Миллиарды / Billions
FAILED
Миллиарды / Billions status changed: Error

**Comment by werwolfby** [comment]
Да, там теперь плохо, сам страдаю, надеюсь это у них временно, либо придумаю обходной вариант.

**Comment by werwolfby** [comment]
Вариант с рсской следующий на очереди

**Comment by werwolfby** [comment]
@CooleRnax, @Akior заработало таки у меня

**Comment by CooleRnax** [comment]
У меня тоже заработало

**Comment by jMurr** [comment]
А сейчас лост-фильм и ретрекер добавили защиту. 
CAPTCHA (просто кнопку нажать) и защита от DDoS (пауза и редирект).
Есть надежда, обойти это или теперь всё?

**Comment by Akior** [comment]
> А сейчас лост-фильм и ретрекер добавили защиту.
> CAPTCHA (просто кнопку нажать) и защита от DDoS (пауза и редирект).
> Есть надежда, обойти это или теперь всё?

Как я понимаю, это временно из-за игры престолов.
