### ISSUE TITLE
Lostfilm.tv сломался?

### ISSUE THREAD

**Issue by SergeyAnuchin** [werwolfby/monitorrent#293]
У меня одного перестало вчера работать?

INFO
Begin execute

INFO
Start checking for lostfilm.tv

INFO
Credentials/Settings are valid

INFO
Check for changes Любовь, смерть и роботы / Love, Death & Robots

FAILED
Exception while execute topic
Traceback (most recent call last):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 813, in _prepare_request
    download_infos = self.tracker.get_download_info(topic.url, topic.cat, episode.season, episode.number)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 579, in get_download_info
    meta_content = soup.find('meta').attrs['content']
KeyError: 'content'

INFO
End checking for lostfilm.tv

INFO
End execute

**Comment by utmcrow** [comment]
+1

**Comment by SergeyAnuchin** [comment]
Они повесили защиту от DDoS от Cloudflare, может это причина?

**Comment by werwolfby** [comment]
Да по любому причина именно в этом, в прошлый раз #292 повесели на весь сайт в этот раз на страницу с торрент файлами :(

Нормально это не пофиксать, само пройдёт. Все ринулись качать Игру Престолов :)

**Comment by Itzamna44** [comment]
У мне не только игра престолов - еще ОА и Американские боги. С такой же диагностикой не качаются.

**Comment by werwolfby** [comment]
Да, сломался весь lostfilm там на любой странице с торрентами DDOS защита. Т.е. по факту ничего с лоста качатся пока не будет :(
Но думаю через день два всё пофиксится

**Comment by liklaysh** [comment]
скачал что бы попробовать на лосте, а он сломался =) хахах удачно

**Comment by werwolfby** [comment]
@liklaysh работает уже, с четверга так точно.
@SergeyAnuchin я закрою ишью если все работает. Ибо больше проблем я уже давно не наблюдаю.

**Comment by SergeyAnuchin** [comment]
@werwolfby да, оно починилось само через день.

**Comment by MaximDementyev** [comment]
Эта ошибка по всем сериалам сейчас наблюдается

**Comment by werwolfby** [comment]
@MaximDementyev да и будет еще день-два :(

**Comment by werwolfby** [comment]
Но у Игры Престолов всего 3 серии осталось :) скоро закончатся мучения :)
