### ISSUE TITLE
LostFilm has an error with specific show

### ISSUE THREAD

**Issue by kekal** [werwolfby/monitorrent#294]
На LostFilm стабильно воспроизводится ошибка при скачивании со страницы [Американские боги](https://www.lostfilm.tv/series/American_Gods/seasons).

- INFO
Begin execute
- INFO
Start checking for lostfilm.tv
- INFO
Credentials/Settings are valid
- INFO
Check for changes Американские боги / American Gods
- FAILED
Exception while execute topic
`Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 813, in _prepare_request
    download_infos = self.tracker.get_download_info(topic.url, topic.cat, episode.season, episode.number)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 579, in get_download_info
    meta_content = soup.find('meta').attrs['content']
KeyError: 'content'`
- INFO
End checking for lostfilm.tv
- INFO
End execute

Формат 1080p
Место сохранения локальное.
Проблема проявляется только на этой странице и только в последнюю неделю.
Вручную добавление происходит успешно.

**Comment by werwolfby** [comment]
@kekal проблема на всем лосте из-за Игры Престолов. Подробнее в #292 и #293.
Завтро должно будет пройти. Сам страдаю 😞 

Я закрою эту ишью.

**Comment by kekal** [comment]
Проблема исчерпана. 
Спасибо.
