### ISSUE TITLE
Не пускает на сервер

### ISSUE THREAD

**Issue by ineggo** [werwolfby/monitorrent#298]
При установке пишет: 
```
# python3 server.py
/opt/lib/python3.7/site-packages/alembic/util/messaging.py:73: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x2892d98>
  warnings.warn(msg)
Server started on 0.0.0.0:6687
```
при попытке зайти на сервер:

```
TypeError('process_response() takes 4 positional arguments but 5 were given')
Traceback (most recent call last):
  File "/opt/lib/python3.7/site-packages/cheroot/server.py", line 1273, in communicate
    req.respond()
  File "/opt/lib/python3.7/site-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/opt/lib/python3.7/site-packages/cheroot/wsgi.py", line 143, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/opt/lib/python3.7/site-packages/falcon/api.py", line 286, in __call__
    process_response(req, resp, resource, req_succeeded)

```
Браузер возвращает Error 500, на страницу не пускает.
![image](https://user-images.githubusercontent.com/5715168/57365510-a0ea6c80-719e-11e9-923a-1fb8fd6cfcb6.png)

**Comment by ineggo** [comment]
Проблема в пакете falcon - если ручками установить версию 1.0.0 - вроде пускает. Функциональность не проверял пока.

**Comment by impalex** [comment]
При апгрейде сервера столкнулся с этой же проблемой. Откат на 1.0.0 помогает, подтвердить "на трансмишн не пускает, на трекеры тоже" не могу - у меня работает.

**Comment by greatbao** [comment]
Подтверждаю - откат falcon==1.0.0 решает проблему ТС
Других проблем после отката пока не выявлено.

**Comment by StarvingDeveloper** [comment]
На данный момент откат falcon==1.0.0 нехватает - надо еще  cheroot==5.1.0 откатит, и тогда хотя бы запускается. Неуверен что дальше будет, но суть что хорошо бы код пересмотреть или оставить только докер, а то ручками устанавливать уже трудаемко становится =(

**Comment by werwolfby** [comment]
Все привет, я зафризал зависимости в `master` (версия `1.1.11`) ну и смерджил это в `develop`, хотя он все ещё сломан
