### ISSUE TITLE
Anilibria issue.

### ISSUE THREAD

**Issue by kekal** [werwolfby/monitorrent#301]
There is new timeout issue with anilbria. Didn't find in exiting issues/PR
 v.1.1.10

Stack:

> FAILED
> 
> Exception while execute topic
> 
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
>     self._validate_conn(conn)
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
>     conn.connect()
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connection.py", line 344, in connect
>     ssl_context=context)
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
>     return context.wrap_socket(sock, server_hostname=server_hostname)
>   File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 412, in wrap_socket
>     session=session
>   File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 853, in _create
>     self.do_handshake()
>   File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 1117, in do_handshake
>     self._sslobj.do_handshake()
> socket.timeout: _ssl.c:1039: The handshake operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\adapters.py", line 449, in send
>     timeout=timeout
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\util\retry.py", line 367, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
>     raise value
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
>     self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 306, in _raise_timeout
>     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
> urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.anilibria.tv', port=443): Read timed out. (read timeout=10.0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 222, in execute
>     response, filename = download(prepared_request, **download_kwargs)
>   File "C:\Program Files (x86)\Monitorrent\monitorrent\utils\downloader.py", line 7, in download
>     response = requests.session().send(request, **kwargs)
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\adapters.py", line 529, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.anilibria.tv', port=443): Read timed out. (read timeout=10.0)
> 
>

**Comment by Akior** [comment]
Anilibria hoster was\now sometimes DDos'ed.
![Снимок экрана от 2019-08-23 14-23-57](https://user-images.githubusercontent.com/5903863/63589404-b51d7280-c5b1-11e9-82b3-a2bf3c6b876f.png)

**Comment by kekal** [comment]
It was the issue with one single title on site. So, I decided to remove from the list.
