### ISSUE TITLE
NewConnectionError

### ISSUE THREAD

**Issue by makar0nin** [werwolfby/monitorrent#302]
Exception while execute topic
HTTPConnectionPool(host='a.retre.org', port=80): Max retries exceeded with url: /v3/index.php?c=128&s=1&e=2&u=5020044&h=4083f5c4f0edcb9cf8c85ffc70303777&n=1&newbie= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xae890c0c>: Failed to establish a new connection: [Errno 101] Network is unreachable',)) 
И так переодически на lostfilmовских сериалах

**Comment by Akior** [comment]
Такое постоянно или периодически на любом трекере ?
По логам похоже, что сервер не смог подключиться, в рамках заданного timeout, к трекеру.

**Comment by makar0nin** [comment]
@Akior очень часто. На lostfilm только

**Comment by Akior** [comment]
Поставьте на пинг a.retre.org 
Пока что, похоже что сервер не может достучаться до трекера. Сетевые проблемы.

Сервер напрямую к трекеру бегает, прокси не используете ?

**Comment by makar0nin** [comment]
@Akior все на прямую. пару раз пробовал пинговать в момент ошибки, пинги  все норм. этот адрес кидает на страницу загрузки torrent файла.

**Comment by Akior** [comment]
Можно включить пинг на постоянку. 
В момент проблемы тормозните, и посмотрите что там будет. Все скрипты чувствительны к потерям соединения, даже кратковременным.
while [ true ] ; do echo $(date) >> /var/log/ping.txt ; ping a.retre.org -c 1  >> /var/log/ping.txt ; echo " " >> /var/log/ping.txt ;sleep 1; done
Главное не забудьте выключить, скрипт может и весь диск забить логами.

**Comment by makar0nin** [comment]
Больше кажется что это защита именно от ботов, он трекер вносит паузу для подтверждения , а наш скрипт сыпется по timeout

**Comment by Akior** [comment]
> Больше кажется что это защита именно от ботов, он трекер вносит паузу для подтверждения , а наш скрипт сыпется по timeout
Иногда на лосте включается проверка от ddos от cloudflare.
Возможно Вы правы, но я за последнее время такие exception не ловил, а чекается 66 сериалов на лосте. 
Слышал, что последнюю неделю некоторых хостеров ддосят (Анилибрия пример) может лост так же иногда попадает под раздачу и включается ddos проверка.

**Comment by makar0nin** [comment]
Проблема ушла вроде. Не вижу смысла держать данную проблему в обсуждении
