### ISSUE TITLE
При старте сервера в консоль сыпятся ошибки и не отображаются страницы в браузере.

### ISSUE THREAD

**Issue by jMurr** [werwolfby/monitorrent#303]
Версия monitorrent: 1.1.10
Устройство: D-Link NAS-325
Архитектура: ARMv6 (armel)
OS: Debian 10 (Buster)

**Python 3.7.3**
При запуске из консоли (не сервисом) немного думает и насыпает такие сообщения:
root@sc:/opt/monitorrent# **python3 server.py**
```
/opt/monitorrent/monitorrent/upgrade_manager.py:35: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0xb51747d0>
  migration_context = MigrationContext.configure(session)
Server started on 0.0.0.0:6687
```
А после попытки открыть URL в браузерах, страница пуста, а вконсоль сыпятся такие ошибки и при попытке открыть/обновить страницу, каждый раз появляются такие вот строки:
```
TypeError('process_response() takes 4 positional arguments but 5 were given')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1273, in communicate
    req.respond()
  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.7/dist-packages/cheroot/wsgi.py", line 143, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python3.7/dist-packages/falcon/api.py", line 286, in __call__
    process_response(req, resp, resource, req_succeeded)
TypeError: process_response() takes 4 positional arguments but 5 were given
TypeError('process_response() takes 4 positional arguments but 5 were given')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1273, in communicate
    req.respond()
  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.7/dist-packages/cheroot/wsgi.py", line 143, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python3.7/dist-packages/falcon/api.py", line 286, in __call__
    process_response(req, resp, resource, req_succeeded)
TypeError: process_response() takes 4 positional arguments but 5 were given
```
При использовании **Python 2.7.16** monitorrent даже не стартует:
root@sc:/opt/monitorrent#  **python ./server.py** 
```
Traceback (most recent call last):
  File "./server.py", line 2, in <module>
    from builtins import range
ImportError: No module named builtins
```
и вываливается в bash (шел).
Увы Docker-а под данную архитектуру нету...
Какие логи надо прислать или, что ещё можно/нужно сделать?

**Comment by Akior** [comment]
Попробуйте откатить falcon до falcon==1.0.0

**Comment by jMurr** [comment]
> Попробуйте откатить falcon
У меня такого вообще не установлено.
# **apt list --installed f***
_Listing... Done
fakeroot/stable,now 1.23-1 armel [installed]
fancontrol/stable,now 1:3.5.0-3 all [installed]
fdisk/stable,now 2.33.1-0.1 armel [installed]
file/stable,now 1:5.35-4 armel [installed]
findutils/stable,now 4.6.0+git+20190209-2 armel [installed]
firmware-linux-free/stable,now 3.4 all [installed,automatic]
fontconfig-config/stable,now 2.13.1-2 all [installed,automatic]
fonts-dejavu-core/stable,now 2.37-1 all [installed,automatic]
fonts-lato/stable,now 2.0-2 all [installed,automatic]_

**Comment by jMurr** [comment]
У меня такой пакет не установлен вообще:
$ apt list --installed python3*
_Listing... Done
python3-apt/stable,now 1.8.4 armel [installed,automatic]
python3-asn1crypto/stable,now 0.24.0-1 all [installed,automatic]
python3-cffi-backend/stable,now 1.12.2-1 armel [installed,automatic]
python3-crypto/stable,now 2.6.1-9+b1 armel [installed,automatic]
python3-cryptography/stable,now 2.6.1-3 armel [installed,automatic]
python3-dbus/stable,now 1.2.8-3 armel [installed,automatic]
python3-dev/stable,now 3.7.3-1 armel [installed,automatic]
python3-distro-info/stable,now 0.21 all [installed,automatic]
python3-distutils/stable,now 3.7.3-1 all [installed,automatic]
python3-entrypoints/stable,now 0.3-1 all [installed,automatic]
python3-gi/stable,now 3.30.4-1 armel [installed,automatic]
python3-keyring/stable,now 17.1.1-1 all [installed,automatic]
python3-keyrings.alt/stable,now 3.1.1-1 all [installed,automatic]
python3-lib2to3/stable,now 3.7.3-1 all [installed,automatic]
python3-minimal/stable,now 3.7.3-1 armel [installed,automatic]
python3-pip/stable,now 18.1-5 all [installed]
python3-pkg-resources/stable,now 40.8.0-1 all [installed,automatic]
python3-pycurl/stable,now 7.43.0.2-0.1 armel [installed,automatic]
python3-secretstorage/stable,now 2.3.1-2 all [installed,automatic]
python3-setuptools/stable,now 40.8.0-1 all [installed,automatic]
python3-six/stable,now 1.12.0-1 all [installed,automatic]
python3-software-properties/stable,now 0.96.20.2-2 all [installed,automatic]
python3-sqlalchemy-ext/stable,now 1.2.18+ds1-2 armel [installed,automatic]
python3-sqlalchemy/stable,now 1.2.18+ds1-2 all [installed]
python3-wheel/stable,now 0.32.3-2 all [installed,automatic]
python3-xdg/stable,now 0.25-5 all [installed,automatic]
python3.7-dev/stable,now 3.7.3-2 armel [installed,automatic]
python3.7-minimal/stable,now 3.7.3-2 armel [installed,automatic]
python3.7/stable,now 3.7.3-2 armel [installed,automatic]
python3/stable,now 3.7.3-1 armel [installed,automatic]_

**Comment by jMurr** [comment]
> Попробуйте откатить falcon до falcon==1.0.0

У меня такой пакет не установлен вообще:
$ apt list --installed python3*
_Listing... Done
python3-apt/stable,now 1.8.4 armel [installed,automatic]
python3-asn1crypto/stable,now 0.24.0-1 all [installed,automatic]
python3-cffi-backend/stable,now 1.12.2-1 armel [installed,automatic]
python3-crypto/stable,now 2.6.1-9+b1 armel [installed,automatic]
python3-cryptography/stable,now 2.6.1-3 armel [installed,automatic]
python3-dbus/stable,now 1.2.8-3 armel [installed,automatic]
python3-dev/stable,now 3.7.3-1 armel [installed,automatic]
python3-distro-info/stable,now 0.21 all [installed,automatic]
python3-distutils/stable,now 3.7.3-1 all [installed,automatic]
python3-entrypoints/stable,now 0.3-1 all [installed,automatic]
python3-gi/stable,now 3.30.4-1 armel [installed,automatic]
python3-keyring/stable,now 17.1.1-1 all [installed,automatic]
python3-keyrings.alt/stable,now 3.1.1-1 all [installed,automatic]
python3-lib2to3/stable,now 3.7.3-1 all [installed,automatic]
python3-minimal/stable,now 3.7.3-1 armel [installed,automatic]
python3-pip/stable,now 18.1-5 all [installed]
python3-pkg-resources/stable,now 40.8.0-1 all [installed,automatic]
python3-pycurl/stable,now 7.43.0.2-0.1 armel [installed,automatic]
python3-secretstorage/stable,now 2.3.1-2 all [installed,automatic]
python3-setuptools/stable,now 40.8.0-1 all [installed,automatic]
python3-six/stable,now 1.12.0-1 all [installed,automatic]
python3-software-properties/stable,now 0.96.20.2-2 all [installed,automatic]
python3-sqlalchemy-ext/stable,now 1.2.18+ds1-2 armel [installed,automatic]
python3-sqlalchemy/stable,now 1.2.18+ds1-2 all [installed]
python3-wheel/stable,now 0.32.3-2 all [installed,automatic]
python3-xdg/stable,now 0.25-5 all [installed,automatic]
python3.7-dev/stable,now 3.7.3-2 armel [installed,automatic]
python3.7-minimal/stable,now 3.7.3-2 armel [installed,automatic]
python3.7/stable,now 3.7.3-2 armel [installed,automatic]
python3/stable,now 3.7.3-1 armel [installed,automatic]_

**Comment by Akior** [comment]
Это пакет который Вы ставили из requirements.
Установка для python.

pip3 install falcon==1.0.0

> > Попробуйте откатить falcon до falcon==1.0.0
> 
> У меня такой пакет не установлен вообще:
> $ apt list --installed python3*
> _Listing... Done python3-apt/stable,now 1.8.4 armel [installed,automatic] python3-asn1crypto/stable,now 0.24.0-1 all [installed,automatic] python3-cffi-backend/stable,now 1.12.2-1 armel [installed,automatic] python3-crypto/stable,now 2.6.1-9+b1 armel [installed,automatic] python3-cryptography/stable,now 2.6.1-3 armel [installed,automatic] python3-dbus/stable,now 1.2.8-3 armel [installed,automatic] python3-dev/stable,now 3.7.3-1 armel [installed,automatic] python3-distro-info/stable,now 0.21 all [installed,automatic] python3-distutils/stable,now 3.7.3-1 all [installed,automatic] python3-entrypoints/stable,now 0.3-1 all [installed,automatic] python3-gi/stable,now 3.30.4-1 armel [installed,automatic] python3-keyring/stable,now 17.1.1-1 all [installed,automatic] python3-keyrings.alt/stable,now 3.1.1-1 all [installed,automatic] python3-lib2to3/stable,now 3.7.3-1 all [installed,automatic] python3-minimal/stable,now 3.7.3-1 armel [installed,automatic] python3-pip/stable,now 18.1-5 all [installed] python3-pkg-resources/stable,now 40.8.0-1 all [installed,automatic] python3-pycurl/stable,now 7.43.0.2-0.1 armel [installed,automatic] python3-secretstorage/stable,now 2.3.1-2 all [installed,automatic] python3-setuptools/stable,now 40.8.0-1 all [installed,automatic] python3-six/stable,now 1.12.0-1 all [installed,automatic] python3-software-properties/stable,now 0.96.20.2-2 all [installed,automatic] python3-sqlalchemy-ext/stable,now 1.2.18+ds1-2 armel [installed,automatic] python3-sqlalchemy/stable,now 1.2.18+ds1-2 all [installed] python3-wheel/stable,now 0.32.3-2 all [installed,automatic] python3-xdg/stable,now 0.25-5 all [installed,automatic] python3.7-dev/stable,now 3.7.3-2 armel [installed,automatic] python3.7-minimal/stable,now 3.7.3-2 armel [installed,automatic] python3.7/stable,now 3.7.3-2 armel [installed,automatic] python3/stable,now 3.7.3-1 armel [installed,automatic]_

**Comment by jMurr** [comment]
Спасибо!
Стоял фалкон 2.0.0. С этой версией хоть и выругался в консоль, но запустился!
Потестим, потянет ли его мой старичок д-линк.
Огромное Вам спасибо!
> pip3 install falcon==1.0.0

**Comment by Akior** [comment]
Для лоста фикс здесь:
https://github.com/werwolfby/monitorrent/issues/304

**Comment by jMurr** [comment]
> Для лоста фикс здесь:
> #304

спасибо, вроде получилось
