### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by makar0nin** [werwolfby/monitorrent#304]
При каждой проверке сыпет:

Traceback (most recent call last):
  File "/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request
    show = self.tracker.parse_url(topic.url, True)
  File "/monitorrent/plugins/trackers/lostfilm.py", line 510, in parse_url
    result = LostFilmShow(original_name=title_block.find('div', class_='title-en').text,
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by Akior** [comment]
У лоста сменилась структура div класса.
![image](https://user-images.githubusercontent.com/5903863/63490096-72c63980-c4bc-11e9-88b4-4a2a39a9a868.png)
@werwolfby Это корректная правка для лоста ?
![image](https://user-images.githubusercontent.com/5903863/63490124-8c678100-c4bc-11e9-8f6a-d54e8d7d3ed6.png)

**Comment by makar0nin** [comment]
@Akior может pull-request ускорит решение проблем)))

**Comment by Akior** [comment]
> @Akior может pull-request ускорит решение проблем)))

Вы можете так же у себя поменять эти параметры. (510 строка в файле /monitorrent/plugins/trackers/lostfilm.py ) 
За целый день exception у меня не возникли.

**Comment by makar0nin** [comment]
@Akior а разве пересобирать не надо? Там вроде рядом лежат pyc файлы. Я просто в питоне не соображаю.

**Comment by RuPF** [comment]
Я зашел в 510 строку в файле /monitorrent/plugins/trackers/lostfilm.py
Заменил
`result = LostFilmShow(original_name=title_block.find(**'div'**, class_='title-en').text,
                              russian_name=title_block.find(**'div'**, class_='title-ru').text,
на  
result = LostFilmShow(original_name=title_block.find(**'h2'**, class_='title-en').text,
                              russian_name=title_block.find(**'h1'**, class_='title-ru').text,
сохранил, перезапустил Monitorrent и все заработало.

**Comment by Akior** [comment]
Для тех кто в докере использует, тоже можно подправить:
docker exec monitorrent vi monitorrent/plugins/trackers/lostfilm.py

**Comment by makar0nin** [comment]
@Akior @RuPF  может еще и по этому #302 что подскажете

**Comment by 4ak1** [comment]
поменял дивы на заголовки как вы и писали) ошибка ушла для не обновленных торрентов. Но если же он обновился и нужно скачать серию то вылезает опять ошибка

> Traceback (most recent call last):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request
    show = self.tracker.parse_url(topic.url, True)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 515, in parse_url
    for season in self._parse_series(soup):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 524, in _parse_series
    serie_blocks = series_block.find_all('div', class_='serie-block')
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by abaistov** [comment]
У меня такая же проблема, как и у @4ak1

**Comment by abaistov** [comment]
> У меня такая же проблема, как и у @4ak1

Помогло удаление-добавление "проблемной" раздачи.

**Comment by Akior** [comment]
Мне такое не попадалось. Надо посмотреть див класс такой раздачи, может там тоже "h"
Попробуйте как сказали выше, пересоздать раздачу. 
> 
> 
> поменял дивы на заголовки как вы и писали) ошибка ушла для не обновленных торрентов. Но если же он обновился и нужно скачать серию то вылезает опять ошибка
> 
> > Traceback (most recent call last):
> > File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
> > episodes = self._prepare_request(topic)
> > File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request
> > show = self.tracker.parse_url(topic.url, True)
> > File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 515, in parse_url
> > for season in self._parse_series(soup):
> > File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 524, in _parse_series
> > serie_blocks = series_block.find_all('div', class_='serie-block')
> > AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by jMurr** [comment]
> поменял дивы на заголовки как вы и писали) ошибка ушла для не обновленных торрентов. Но если же он обновился и нужно скачать серию то вылезает опять ошибка

Всего более сотни сериалов с лоста, обновляемых около десятка, помог совет по исправлению 510 и 511 строки ./monitorrent/plugins/trackers/lostfilm.py
Более ничего не пересоздавал, не удалял, но всё работает.

**Comment by OleksiiShtangeii** [comment]
Так же помогло исправление 510 и 511 строчки 
я использую monitorrent в docker напишу сдесь как я исправил ету проблему, так как вот ета команда у меня не вишла :
> Для тех кто в докере использует, тоже можно подправить:
> docker exec monitorrent vi monitorrent/plugins/trackers/lostfilm.py

1. "docker exec -it id_контейнера /bin/sh"
1a. id контейнера можес узнать использовав ету команду "docker ps"
2. ну а дальше вот ета команда  "vi monitorrent/plugins/trackers/lostfilm.py +510"
3. рестарт контейнера "docker restart id_контейнера"

**Comment by degorychev** [comment]
Кто не может помириться с vi можете поставить другой редактор, nano или mcedit:
>#apk update
>#apk add mc
>#mc

**Comment by RazielMalah** [comment]
> поменял дивы на заголовки как вы и писали) ошибка ушла для не обновленных торрентов. Но если же он обновился и нужно скачать серию то вылезает опять ошибка
> 
> > Traceback (most recent call last):
> > File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
> > episodes = self._prepare_request(topic)
> > File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request
> > show = self.tracker.parse_url(topic.url, True)
> > File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 515, in parse_url
> > for season in self._parse_series(soup):
> > File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 524, in _parse_series
> > serie_blocks = series_block.find_all('div', class_='serie-block')
> > AttributeError: 'NoneType' object has no attribute 'find_all'

Укажи в свойствах раздачи с какой серии какого сезона качать.

**Comment by werwolfby** [comment]
А мне фикс не помог :)

**Comment by werwolfby** [comment]
Хотя нет, таки помог

**Comment by Akior** [comment]
Только docker не забудьте

**Comment by werwolfby** [comment]
@Akior не забуду, просто это было не быстро 😞 
Но появился общий контейнер `werwolfby/monitorrent` с обоими архитектурами

**Comment by makar0nin** [comment]
@werwolfby , вопрос не  в тему , но раз обновление вышло, есть инструкция как обновить? а то этот процес в прошлый раз сбросил все отслеживания и нас тройки .

**Comment by werwolfby** [comment]
@makar0nin а как ставишь?
Просто любой апдейт должен проходить без проблем. 
Для докера сохраняется база через волюм
Для Виндоус тоже просто, там сам апдейт должен мягко пройти

Если действительно есть проблемы, то нужна отдельная ишью с подробностями: как и куда ставишь, ось докер/инсталлер/сырцы

**Comment by makar0nin** [comment]
@werwolfby  на Ubuntu 18.04 ставил просто из релизного архива , как обычный процесс утсановки в то же место где и предыдущая была.

**Comment by Groznuy** [comment]
У меня например в докер контейнере и все настройки слетели.

**Comment by Akior** [comment]
Если база вынесена во внешнее хранилище, все должно сохраниться
-v /path/to/monitorrent.db:/var/www/monitorrent/monitorrent.db

Я обновился без проблем, путь указан такой:
-v /opt/monitorrent/monitorrent.db:/var/www/monitorrent/monitorrent.db

**Comment by makar0nin** [comment]
Обновился вроде норм .

**Comment by Groznuy** [comment]
у меня такое :

```
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 630, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by Groznuy** [comment]
ну пофиксил одним словом
почему то у меня была создана папка monitorrent.db а не файл.

**Comment by werwolfby** [comment]
@Groznuy именно по этому в ридми написано сначала сделать `touch monitorrent.db` Иначе по дефолту волюм будет папкой

**Comment by werwolfby** [comment]
@makar0nin если ставил с архива, то нужно было сохранить monitorrent.db

**Comment by Groznuy** [comment]
@werwolfby у меня в докера да и ещо под управлением portainer)

**Comment by makar0nin** [comment]
@werwolfby , уже понял. Обновил все нормально . Но думаю стоит внести краткую инструкцию по обновлению.

**Comment by Groznuy** [comment]
@makar0nin если monitorrent стоит в докер контейнере то я думаю стоит поставить контейнер watchtower он все делает автоматом(обновляет все докер контейнеры)ну ето у меня так

**Comment by makar0nin** [comment]
@Groznuy  , развернут тупо в ubuntu 18.04  никаких контейнеров . Как писал выше обновил нормально. ЗАбекапил перед обновлением db навсякий случай и накатил в туже локацию
