### ISSUE TITLE
AniLibria.TV parser not working after Cloudflare DDOS protection implementing on tracker.

### ISSUE THREAD

**Issue by Moris-Shalon** [werwolfby/monitorrent#306]
Всем добрый день! С тех пор, как AniLibria.TV ввела защиту от DDOS атак от Cloudflare, парсер перестал работать. Есть ли тут какое то решение? Может, обход этой DDOS-защиты был уже задействован в парсере какого-либо другого ресурса? 
Видел, что у LostFilm есть метод верификации, как раз основанный на user-agent и cookies. К слову, на AniLibria.TV сообщение с картинки ниже отображается только при открытии страницы в режиме инкогнито, т.е. при сохранении cookies следующее сообщение не выползает. Подойдёт ли метод от Lostfilm?

Hi and good day! Since AniLibria.TV enabled Cloudflare DDOS protection their parser unfortunately stopped working. Is there any possible solution? Is there any DDOS-protection bypass in any other tracker's parser plugin?
I have seen, than LostFilm have verification method, based on user-agent and cookies. Seems like AniLibria.TV sends DDOS-protection message only when your cookies are clear (like in incognito mode), cause when you already have their cookies, you won't get this message. Might it be, that Lostfilm's method can also fix AniLibria's issue?

![image](https://user-images.githubusercontent.com/18584322/64901799-1c58af00-d6a6-11e9-8195-e7a8745bc28b.png)

```
FAILED

Exception while execute topic

Traceback (most recent call last):
  File "/opt/monitorrent/monitorrent/plugins/trackers/__init__.py", line 222, in execute
    response, filename = download(prepared_request, **download_kwargs)
  File "/opt/monitorrent/monitorrent/utils/downloader.py", line 9, in download
    response = requests.get(request, **kwargs)
  File "/opt/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/opt/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/opt/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

![image](https://user-images.githubusercontent.com/18584322/64901703-1e6e3e00-d6a5-11e9-850c-b1dea4d04ff8.png)

**Comment by ZChuckMoris** [comment]
Может быть, это решение подойдёт. Я не уверен, т.к. у меня нет опыта в разработке на Python.

Maybe this solution will suit. I am not sure, cause i have no practice in Python development.


[Stackoverflow - How to bypass cloudflare bot/ddos protection in Scrapy?](https://stackoverflow.com/questions/33247662/how-to-bypass-cloudflare-bot-ddos-protection-in-scrapy)

**Comment by ZChuckMoris** [comment]
Похоже, что защиту от DDOS временно отключили на сайте AniLibria.TV, но было бы словно добавить возможность её обхода в парсер на будущее.

Seems like DDOS-protection has been disabled on AniLibria.TV site, but it would be nice to implement bypass option into monitorrent parser for such cases in future

**Comment by Akior** [comment]
Анилибрия местами лежит полностью
Пока не отобьются, нет смысла что-то делать.

Защита CF, как видно, особого эффекта не даёт.

**Comment by ZChuckMoris** [comment]
> Анилибрия местами лежит полностью
> Пока не отобьются, нет смысла что-то делать.
> 
> Защита CF, как видно, особого эффекта не даёт.

Да, я читал в их Telegram-канале новости про то, что после блокировки в РФ, некто, предположительно, лицензионщики Wakanin во Франции развернули против Либрии масштабные DDOS-атаки. Всё же, я думаю, что раз уж браузер проходит проверку Cloudflare, должна быть возможность пройти эту самую проверку и парсером, подставив свои cookies от браузера. 
Как я понял, Wakanim уже давно законными и незаконными методами борется с Анилибрией, так что повторение подобного не исключено в будущем и хотелось бы иметь заплатку на такой случай
