### ISSUE TITLE
Не работает rutor.info

### ISSUE THREAD

**Issue by Grosses84** [werwolfby/monitorrent#307]
Вообще никак не смог сделать, чтоб заработал rutor, может есть какая-то хитрость? Поделитесь полезным знанием. Как собственно ничто не заработало, кроме lostfilm, anidub, anilibria и kinozal

**Comment by werwolfby** [comment]
Только что проверил, все супер, взял и добавил. Что значит не заработал? Нельзя добавить для монитора? Или после добавления ничего не качает?

Нужно больше подробностей, потому что он должен просто взять и заработать.

**Comment by Grosses84** [comment]
![2019-10-29_104613](https://user-images.githubusercontent.com/26169643/67736217-67056f00-fa39-11e9-8c9f-2e65a92eb395.png)
Вот и вся музыка...

**Comment by werwolfby** [comment]
![image](https://user-images.githubusercontent.com/705754/67739837-04788880-f9d1-11e9-8698-751cdb2c9e38.png)

Странно, нужны логи тогда :(

Если докер, то ```docker logs <имя контейнера>```

**Comment by Grosses84** [comment]
А если не докер? Чёт не могу найти логов.

**Comment by Grosses84** [comment]
Я так понимаю всё сложно?:)

**Comment by Akior** [comment]
Вы из России подключаетесь ?

**Comment by Grosses84** [comment]
Да.

**Comment by Akior** [comment]
> Да. Возможно это фильтрация трафика мне не даёт?

А просто rutor открывается, или только через зеркало ?
Если так, то да, нужен обход блокировки

**Comment by werwolfby** [comment]
@Grosses84 не сложно, а некогда :)
Ну и да фильтрация трафика может не давать

**Comment by Grosses84** [comment]
Сейчас проверил rutor.info не работает, а вот new-rutor.org исправно работает. Уже попробовал в hosts прописать точное сопоставление ip и домена. Проблема в том, что new-rutor.org как-то с задержкой обновляется что ли... Самые свежие записи от 10 ноября.

**Comment by Grosses84** [comment]
И да, я выяснил, трафик у нас не фильтруется.

**Comment by Grosses84** [comment]
Блин, тапочки авторизоваться смог, но увидел, что есть обновление, всё сломал:) Не помешал бы мануал по обновлению:) Благо ещё не так много потерял:)

**Comment by Akior** [comment]
Так если rutor.info не открывается, значит всё таки фильтрация работает

**Comment by Grosses84** [comment]
Нет, там немного другая история, при открытии rutor.info вот у меня в браузере, если не включен frigate, то редиректит на страницу mega-film, а вот она не работает.

**Comment by Grosses84** [comment]
может быть я такой и у меня постоянно какие-то проблемы. Установил сейчас из докера (раз один хрен всё сломал), так вот теперь не могу авторизоваться налостфильме и в трансмишне своём...

**Comment by werwolfby** [comment]
Ну трансмишен из докера может быть и не виден, а вот что за беда с лостом не знаю :(

**Comment by degorychev** [comment]
> не могу авторизоваться на лостфильме и в трансмишне своём...

Ошибка большинства новичков: Не ввести данные в текстбоксы и проверять, а сначала сохранить, потом проверить. Кнопку Save нажали?

**Comment by Grosses84** [comment]
Обязательно. Установил на локальный ПК и всё заработало, возможно получил что-то типа бана после множественных проверок:)

**Comment by werwolfby** [comment]
Ну бан не должен быть, но капча могла быть. А с рутором не знаю чем помочь
