### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by alszaitsev** [werwolfby/monitorrent#308]
Как установить на Windows? При клике на https://github.com/werwolfby/monitorrent/releases/download/1.1.9/MonitorrentInstaller-1.1.9.msi выдает ошибку 404.

**Comment by werwolfby** [comment]
Блин... https://github.com/werwolfby/monitorrent/releases/download/1.1.10/MonitorrentInstaller.msi
Надо обновить урл на главной

**Comment by werwolfby** [comment]
Пофиксил, спасибо

**Comment by alszaitsev** [comment]
спасибо!
