### ISSUE TITLE
Проблемы с клиентами

### ISSUE THREAD

**Issue by alszaitsev** [werwolfby/monitorrent#309]
Установил последнюю версию на Windows 10. Локально стоят  utorrent и qbittorent. Веб интерфейсы включены у обоих - порты назначены вручную 9090 и 9091. Hosts пробовал и localhost, и 127.0.0.1 и локальный IP компьютера. Причем через браузер WEB Gui  открывается у обоих клиентов

**Comment by Akior** [comment]
Где установлен мониторрент, так же на этой машине ?

**Comment by alszaitsev** [comment]
Мониторрент стоит в на hyper-v машине Windows 10. Сетевой адапрет в режиме бридж (на машине IP (192.168.1.Х) из подсети хоста (192.168.1.Y). Порбовал коннектить сперва с клиентами на хосте (utorrent, qb, transmission). ни с одним не подружил, хотя из браузера машины внутри hyper-v (где стоит мониторрент) на гуи захожу. Попробовал установить локально на ту же машину что и мониторрент. Соединился только с трансмишн. Ютор и куби - failed.

**Comment by Akior** [comment]
Как добавляете qbit ? Ip, порт, логин и пасс ?

**Comment by alszaitsev** [comment]
конечно. Все что указано в настройка qb на вкладке Web GUI

**Comment by alszaitsev** [comment]
попробую видео сделать

**Comment by Akior** [comment]
> попробую видео сделать
Попробуйте с http
![image](https://user-images.githubusercontent.com/5903863/68074973-ad98f780-fdb2-11e9-8a6f-8506691f64c3.png)

**Comment by alszaitsev** [comment]
сработало. спасибо большое

**Comment by werwolfby** [comment]
Блин... когда я уже пофикшу этот баг с http
