### ISSUE TITLE
development mode не работает?

### ISSUE THREAD

**Issue by alszaitsev** [werwolfby/monitorrent#310]
Сейчас есть проблемы с образом Дев мод? развернул все по инструкции - не работает(

C:\monitorrent\monitorrent\upgrade_manager.py:35: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x000000000510C0C8>
  migration_context = MigrationContext.configure(session)
Server started on 0.0.0.0:6687
TypeError('process_response() takes exactly 4 arguments (5 given)',)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cheroot\server.py", line 970, in communicate
    req.respond()
  File "C:\Python27\lib\site-packages\cheroot\server.py", line 799, in respond
    self.server.gateway(self).respond()
  File "C:\Python27\lib\site-packages\cheroot\wsgi.py", line 101, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "C:\Python27\lib\site-packages\falcon\api.py", line 286, in __call__
    process_response(req, resp, resource, req_succeeded)
TypeError: process_response() takes exactly 4 arguments (5 given)

**Comment by werwolfby** [comment]
Что значит с образом?
Но вообще проблемы есть. 
Девелоп ветка не работает, только мастер. 
Плюс пакеты не зафризаны, что и чревато

**Comment by werwolfby** [comment]
Будет возможность чтото пофиксить сразу сделаю :)
Сначала зафрижу пакеты на те что в докер образах
