### ISSUE TITLE
Принципы работы Monitorrent

### ISSUE THREAD

**Issue by alszaitsev** [werwolfby/monitorrent#315]
Посвятите в принципы работы Monitorrent. по экспериментам Мониторрент просто с заданной периодичностью скачивает у добавленных сериалов с трекера торрент файл и отправляет его в клиента. Правильно ли я это понял?
Если это действительно как описано выше, то возникают проблемы с Kinozal.tv, так как каждое обновление «расходует» лимит на скачивание на кинозале и после 8 скачанных торрентов автоматически в эти сутки новые серии если вышли, то уже не скачаются . Было бы здорово э, если бы мониторрент не просто каждый раз качал торрент, а сначала проверял заголовок раздачи на изменения сравнивая с последним сохранённым заголовком и уже если такие изменения произошли, то качал торрент файл и отправлял его в клиента.

**Comment by werwolfby** [comment]
Нет, он проверяет если апдейты и если есть то только тогда и качает

**Comment by werwolfby** [comment]
В случае kinozal.tv там вообще проверяется дата обновления самой раздачи (там дата на странице есть). И если дата обновилась то скачивает торрент файл. Т.е. самы файлы качаются только в случае обновления.

**Comment by alszaitsev** [comment]
Спасибо за комментарии
