### ISSUE TITLE
[wishlist] Персональные иконки сериалов для LostFilm

### ISSUE THREAD

**Issue by DrMashine** [werwolfby/monitorrent#318]
Хотелось бы чтобы у каждого сериала была своя персональная иконка. У Лоста они на сайте есть. При поиске выводится именно она: https://i.imgur.com/qXjYHPq.png

Вот для примера, как выглядит сейчас и как будет выглядеть, если это реализовать:
![Pw8LGfw](https://user-images.githubusercontent.com/45767800/69237569-01735100-0ba7-11ea-9395-981f4ec9d637.png)

За каждым сайтом закреплен номер и часть графики находится на сервере под этим номером. Например за Ведьмаком закреплен номер 466. 
Иконка находится по адресу https://static.lostfilm.tv/Images/466/Posters/icon.jpg
Постер: https://static.lostfilm.tv/Images/466/Posters/poster.jpg

К сожалению, сопоставить как-то имя сериала (его прямую ссылку) с его номерным обозначением мне не удалось, но я мало в этом понимаю. Если прямой корреляции нет, то можно просто добавить возможность назначать вручную персональную иконку для раздачи, а по умолчанию использовать иконку трекера.

P.S. werwolfby и всем причастным к проекту огромное спасибо за ваш труд.

**Comment by werwolfby** [comment]
Скоро будет, в версии 1.1.12
