### ISSUE TITLE
qbittorrent api broken 

### ISSUE THREAD

**Issue by makar0nin** [werwolfby/monitorrent#322]
После обновления qbittorrent до 4.2.0 ошибка добавления torrent файла. Поидее поменяли api

**Comment by makar0nin** [comment]
Может форсировать включение #320

**Comment by werwolfby** [comment]
Да сделаю

**Comment by makar0nin** [comment]
@werwolfby я в #320 отписал тоже , но код почему-то не взлетел на моей машине. код [ошибки](https://github.com/werwolfby/monitorrent/pull/320#issuecomment-562301423) в ветке

**Comment by makar0nin** [comment]
@werwolfby  слил последний вариант #320 все заработало. Ждем версию здесь , и можно закрывать проблему )
