### ISSUE TITLE
Проблемы с LostFilm. 'NoneType' object has no attribute 'group'; KeyError: 'content'.

### ISSUE THREAD

**Issue by DrMashine** [werwolfby/monitorrent#323]
Добрый день.

2 дня назад все сломалось и начало выдавать ошибку

`FAILED
Exception while execute topic
Traceback (most recent call last):
  File "/volume2/@optware/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/volume2/@optware/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request
    show = self.tracker.parse_url(topic.url, True)
  File "/volume2/@optware/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 515, in parse_url
    for season in self._parse_series(soup):
  File "/volume2/@optware/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 544, in _parse_series
    episode_number = int(play_episode_match.group('episode'))
AttributeError: 'NoneType' object has no attribute 'group'`

LostFilm доступен.
Поиск по темам здесь выдал 2 старые темы за 2017-18 годы.

Подскажите, пожалуйста, куда копать.
Спасибо.

**Comment by werwolfby** [comment]
Что за сериал? Или на всех? Если на всех, то может верстка сменилась :(
Тогда быстро подчиню если на конкретном, то надо разбираться

**Comment by DrMashine** [comment]
@werwolfby был уверен, что на всех. Изучил логи подробней. Оказалось, что часть сериалов все же скачивается. Ошибка стабильно при каждом срабатывании возникает с Сверхъестественным и Синей книгой:
https://www.lostfilm.tv/series/Project_Blue_Book/seasons
https://www.lostfilm.tv/series/Supernatural/seasons

В настройках стоят последние эпизоды. 1.10 для книги и 15.8 для братьев Винчестеров.

**Скриншоты из логов**:
Вот так выглядит внезапное начало ошибок. Посыпался "Сверхъестественное".
https://i.imgur.com/a06X03O.png

**Так присоединилась и Синяя книга**:
https://i.imgur.com/fMVqyqL.png

Так выглядят **подробные логи** если удается скачать один из других сериалов, но эти 2 фейлятся каждый раз.:
https://i.imgur.com/8Ta1Zqu.png

Спасибо, за помощь.

**Comment by degorychev** [comment]
Аналогично, проблема со сверхъестественным тоже. Сервер спрятан за vpn и ничего ему мешать не должно.
Ошибка начала сыпаться до того, как вышла последняя серия

**Comment by degorychev** [comment]
Неужели мы единственные двое страдающих? ☹️

**Comment by DrMashine** [comment]
Оба сериала выйдут во второй половине января, поэтому пока можно поставить их на паузу (там есть такая возможность). Надеюсь до этого момента найдется у кого-то время разобраться в проблеме. А сейчас уж Новый Год на носу, поэтому вряд ли кому-то охота в этом копаться =)

@degorychev тоже поставьте на паузу эту раздачу и готовьтесь к Новому Году ;)

**Comment by StarvingDeveloper** [comment]
У меня тажа проблема уже недели 3, так как последние 3 серии качал ручками (http://www.lostfilm.tv/series/The_Mandalorian).
Ошибка таже самая.

**Comment by Akior** [comment]
Проверил все 3 сериала на v.1.1.11 - все вышедшие серии скачались

**Comment by Akior** [comment]
Похоже что это из-за защиты от ddos
https://github.com/werwolfby/monitorrent/issues/326

**Comment by mind-blowing** [comment]
На версии `v.1.1.11`, пару дней назад добавил 4 сериала `Дом с прислугой / Servant`, `Вампирские войны / V Wars`, `Затерянные в космосе / Lost in Space`, `Экспансия / The Expanse`. 

C 28 декабря примерно с ~22:00 на все кроме `Экспансия / The Expanse` начали сыпаться подобный ошибки:
```
Exception while execute topic
Traceback (most recent call last):
  File "/home/monitorrent/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/home/monitorrent/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 813, in _prepare_request
    download_infos = self.tracker.get_download_info(topic.url, topic.cat, episode.season, episode.number)
  File "/home/monitorrent/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 579, in get_download_info
    meta_content = soup.find('meta').attrs['content']
KeyError: 'content'
```

**Comment by StarvingDeveloper** [comment]
Пока нету новых серый все проверяеится без проблем. Как только сегодня вышла новая серия http://www.lostfilm.tv/series/The_Mandalorian так сразу:

`FAILED

Exception while execute topic

Traceback (most recent call last):
  File "/opt/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/opt/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 813, in _prepare_request
    download_infos = self.tracker.get_download_info(topic.url, topic.cat, episode.season, episode.number)
  File "/opt/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 579, in get_download_info
    meta_content = soup.find('meta').attrs['content']
KeyError: 'content'`

Недумаю что это связано с защитой от ddos, так как проблема только когда появлается новая серия.

**Comment by Akior** [comment]
Пока нет новых серий, попытка скачивать новые серии и не производится.

meta_content = soup.find('meta').attrs['content']
ищет данные в 
soup = get_soup(download_redirect.text)
которые берутся из
download_redirect = request.get(download_redirect_url, headers=self._headers, cookies=cookies,
                                         **self.tracker_settings.get_requests_kwargs())
где download_redirect_url и есть https://www.lostfilm.tv/v_search.php?c=465&s=1&e=01 указанные в проблеме 326. 
Первое открытие идёт через cloudflare ddos protection

**Comment by Akior** [comment]
Есть решение в теме 326
