### ISSUE TITLE
Lostfilm SSL timeout

### ISSUE THREAD

**Issue by kekal** [werwolfby/monitorrent#325]
С 24 декабря соединение с Lostfilm нарушено.
Все сериалы выдают одинаковую ошибку:

`FAILED`
`Exception while execute topic`
`Traceback (most recent call last):`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request`
`    self._validate_conn(conn)`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn`
`    conn.connect()`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connection.py", line 344, in connect`
`    ssl_context=context)`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\util\ssl_.py", line 345, in ssl_wrap_socket`
`    return context.wrap_socket(sock, server_hostname=server_hostname)`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 423, in wrap_socket`
`    session=session`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 870, in _create`
`    self.do_handshake()`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 1139, in do_handshake`
`    self._sslobj.do_handshake()`
`socket.timeout: _ssl.c:1059: The handshake operation timed out`
``
`During handling of the above exception, another exception occurred:`
``
`Traceback (most recent call last):`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\adapters.py", line 449, in send`
`    timeout=timeout`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen`
`    _stacktrace=sys.exc_info()[2])`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\util\retry.py", line 368, in increment`
`    raise six.reraise(type(error), error, _stacktrace)`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\packages\six.py", line 686, in reraise`
`    raise value`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen`
`    chunked=chunked)`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request`
`    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 306, in _raise_timeout`
`    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)`
`urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.lostfilm.tv', port=443): Read timed out. (read timeout=10.0)`
``
`During handling of the above exception, another exception occurred:`
``
`Traceback (most recent call last):`
`  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 736, in execute`
`    episodes = self._prepare_request(topic)`
`  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 799, in _prepare_request`
`    show = self.tracker.parse_url(topic.url, True)`
`  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 500, in parse_url`
`    **self.tracker_settings.get_requests_kwargs())`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\api.py", line 75, in get`
`    return request('get', url, params=params, **kwargs)`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\api.py", line 60, in request`
`    return session.request(method=method, url=url, **kwargs)`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\sessions.py", line 533, in request`
`    resp = self.send(prep, **send_kwargs)`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\sessions.py", line 646, in send`
`    r = adapter.send(request, **kwargs)`
`  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\adapters.py", line 529, in send`
`    raise ReadTimeout(e, request=request)`
`requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.lostfilm.tv', port=443): Read timed out. (read timeout=10.0)`

При этом проверка авторизации в `http://host:port/#/settings/trackers/lostfilm.tv` проходит успешно. И сайт в браузере работает более менее стабильно.

Заранее спасибо.

**Comment by Akior** [comment]
А может в браузере прокси ? 
Лостфильм в полном блоке от РКН

**Comment by kekal** [comment]
> А может в браузере прокси ?
> Лостфильм в полном блоке от РКН

В этой стране© нет РКН

**Comment by kekal** [comment]
Ситуация видоизменилась.
Теперь ошибка иная:
`FAILED`
``
`Exception while execute topic`
``
`Traceback (most recent call last):`
`  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 736, in execute`
`    episodes = self._prepare_request(topic)`
`  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 813, in _prepare_request`
`    download_infos = self.tracker.get_download_info(topic.url, topic.cat, episode.season, episode.number)`
`  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 579, in get_download_info`
`    meta_content = soup.find('meta').attrs['content']`
`KeyError: 'content'`

**Comment by Akior** [comment]
https://github.com/werwolfby/monitorrent/issues/326

**Comment by kekal** [comment]
> #326

Благодарю.
