### ISSUE TITLE
Lostfilm Can't login: Unknown

### ISSUE THREAD

**Issue by StarvingDeveloper** [werwolfby/monitorrent#329]
А больше нечего в логах и нету.

**Comment by makar0nin** [comment]
Можно глянуть #328

**Comment by kekal** [comment]
> Можно глянуть #328
FYI
ea6f407 работает.

**Comment by Groznuy** [comment]
Я не могу в контейнер поставить scraper

**Comment by syicidnic** [comment]
> Я не могу в контейнер поставить scraper

поставь сбоку shemanaev\monitorrent. все работает, все прекрасно.

**Comment by ValTer25** [comment]
такая же проблема, запущен в докере
