### ISSUE TITLE
Лостфильм новые раздачи!

### ISSUE THREAD

**Issue by MozzieMD** [werwolfby/monitorrent#331]
При попытке добавить новую раздачу

`{"title": "CantParse", "description": "Can't parse url: 'http://lostfilm.tv/series/Altered_Carbon/'"}`
`Request URL: http://localhost:6687/api/topics/parse?url=http:%2F%2Flostfilm.tv%2Fseries%2FAltered_Carbon%2F
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 127.0.0.1:6687
Referrer Policy: no-referrer-when-downgrade`

Можно как-то решить проблему или так у всех? На самом сайте вылетает на главную после входа и опять просит аккаунт!

**Comment by Akior** [comment]
Используйте прокси. Это похоже бан от лоста.

**Comment by MozzieMD** [comment]
Все заработало, скорее всего баг на сайте исправили
