### ISSUE TITLE
Вернись!

### ISSUE THREAD

**Issue by liklaysh** [werwolfby/monitorrent#332]
Чел вернись плиз =) у тебя отличный софт! ты нам нужен!
Докер репозитории удалены ((
Лост не работает ((

**Comment by werwolfby** [comment]
Всмысле докер удален?
И всмысле лост не работает?
Я же качаю с него 😄

**Comment by werwolfby** [comment]
Лост работает, проверил логи
Докер хаб на месте, докер репозиторий вот: https://github.com/werwolfby-docker/armhf-alpine-monitorrent

**Comment by liklaysh** [comment]
Я видимо заходил на сам саю докера )) там пусто просто )

**Comment by werwolfby** [comment]
В докер хабе репа показывается только если это автоматический билд. А у меня он полуавтоматический. Да и не поддерживают они ARM билды.

Можем закрыть ишью? Скоро закрою пару ПРов :)
