### ISSUE TITLE
Не могу авторизоваться на rutracker.org

### ISSUE THREAD

**Issue by LinFor** [werwolfby/monitorrent#333]
Добрый день.

Не получается авторизоваться из мониторрента на rutracker.org. Логин/пароль перепроверял/перевводил несколько раз - не спасает. В логах тоже никакого криминала:
`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rutracker.org:443
DEBUG:urllib3.connectionpool:https://rutracker.org:443 "POST /forum/login.php HTTP/1.1" 200 None
INFO:monitorrent.engine:{"time": "2020-03-16 13:20:06.696504", "event": "Ending execute", "logger": "monitorrent.engine", "level": "info", "timestamp": "2020-03-16T13:20:06.696535Z"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rutracker.org:443
DEBUG:urllib3.connectionpool:https://rutracker.org:443 "POST /forum/login.php HTTP/1.1" 200 None
`
При этом в мониторренте вот так:
`INFO
Begin execute

INFO
Start checking for rutracker.org

INFO
Credentials/Settings are not valid Try login.

FAILED
Can't login: Incorrent login/password

INFO
End checking for rutracker.org

INFO
End execute

`

Из браузера с той же самой подсети всё прекрасно заходит. Мониторрент (и его sqlite-база) свежепоставленный.

Окружение - docker (werwolfby/alpine-monitorrent), хожу на рутрекер по ipv6 (из браузера тоже).

PS: логин/пасс могу дать для тестирования

**Comment by werwolfby** [comment]
@LinFor да, можете написать в личку в [gitter.im](https://gitter.im/). Пароль лучше сменить перед тем как мне давать :), потом поменяете назад.

**Comment by LinFor** [comment]
Починилось само собой без внешнего вмешательства

**Comment by werwolfby** [comment]
Это странно :), но оно и должно было работать
