### ISSUE TITLE
Автозапуск server.py на ubuntu

### ISSUE THREAD

**Issue by burdeyniyua** [werwolfby/monitorrent#334]
Добрый день! Уже несколько дней не могу запустить скрипт Monitorrent при запуске системы.
При ручном запуске скрипта запускается и работает. Но при загрузке системы никак. Пробую и через systemd и через rc.local
Помогите пожалуйста прописать скрипт в автозапуск.
Сам скрипт:
```
#!/bin/bash
python3 /home/user/monitorrent/server.py
```
**Версия linux 4.15.0-91-generic (Ubuntu 7.4.0-1ubuntu1~18.04.1)**

**Comment by burdeyniyua** [comment]
Я так понимаю, что скрипт init.d еще не прописан в возможностях Monitorrent.

**Comment by werwolfby** [comment]
Ну да я ниразу этого не планировал.
Просто docker покрывает это ещё лучше чем init.d.

**Comment by Akior** [comment]
Systemd

    [Unit]
    Description=Monitorrent
    After=network.target
   
    [Service]
    ExecStart=/usr/bin/python3 /opt/monitorrent/server.py --db-path /opt/monitorrent/monitorrent.db
    Restart=always
    RestartSec=10
    WorkingDirectory=/opt/monitorrent/
    User=root
    Group=root
    KillMode=process

    [Install]
    WantedBy=multi-user.target
