### ISSUE TITLE
anilibria.tv

### ISSUE THREAD

**Issue by Grosses84** [werwolfby/monitorrent#339]
Обнаружил такую проблему. При добавлении раздач с ресурса 
![2020-04-06_075913](https://user-images.githubusercontent.com/26169643/78515281-76a29400-77df-11ea-9846-e0b22a7153b0.png)
2 строки одинаковые и ставится всегда первая, а серии добавляют уже во вторую.

**Comment by werwolfby** [comment]
Закрываю за давностью.
Если что переоткрывайте.
