### ISSUE TITLE
Не могу добавить торрент

### ISSUE THREAD

**Issue by uraaa** [werwolfby/monitorrent#340]
При добавлении торрента кнопка Add не активна
![Screenshot_4](https://user-images.githubusercontent.com/3144029/79005349-5405d780-7b5f-11ea-8571-d675ceb3b86a.png)
Установил на Windows 10 через msi.

**Comment by werwolfby** [comment]
А lostfilm.tv точно доступен?

**Comment by uraaa** [comment]
через браузер да, нужно добавить в настройки свои прокси перед этим, да?

**Comment by uraaa** [comment]
![image](https://user-images.githubusercontent.com/3144029/79048450-c214d200-7c25-11ea-9b38-64ba4626d857.png)
Добавил прокси, попробовал добавить торрент с Рутора - такая же история.
![image](https://user-images.githubusercontent.com/3144029/79048465-e1abfa80-7c25-11ea-94f8-53a04f54f213.png)

**Comment by uraaa** [comment]
Подскажите плиз как настроить доступ к заблокированным трекерам.

**Comment by liquidblasted** [comment]
Что-то тоже перестала становиться активной кнопка Add после вбивания ссылки на торрент - доступ к рутрекеру тестируется как ОК, в логах пусто, не могу понять пока, в чем причина.

**Comment by werwolfby** [comment]
А торрент клиент точно настроен?

**Comment by liquidblasted** [comment]
> А торрент клиент точно настроен?

да, transmission, при чеке в настройках - успешный коннект, да и не менял ничего давным-давно

**Comment by VitaliyS** [comment]
Возможно, причина в устаревших куках. Если обновлять уже добавленные торренты, то куки обновляются, если не удалось авторизироваться. При добавлении же нового торрента куки не обновляются
Обнаружил эту проблему в своем плагине, после того, как закрыли доступ к трекеру для незалогиненных пользователей
Попробуйте зайти в настройки трекера, нажать там Save, потом Check. Если после этого торрент добавится - это тот же случай

**Comment by werwolfby** [comment]
Закрываю за давностью
