### ISSUE TITLE
requirements build failed at brotli

### ISSUE THREAD

**Issue by ecLAllanon** [werwolfby/monitorrent#344]
> pip install -r requirements.txt
for few setups on FreeBSD 12 (in my case it's XigmaNAS) build failed at **brotli**

>   Building wheel for brotli (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w70crtv8/brotli/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w70crtv8/brotli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zb0yjfpm
       cwd: /tmp/pip-install-w70crtv8/brotli/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating bin
  creating bin/lib.freebsd-12.1-RELEASE-p3-amd64-3.7
  copying python/brotli.py -> bin/lib.freebsd-12.1-RELEASE-p3-amd64-3.7
  running build_ext
  building '_brotli' extension
  creating bin/temp.freebsd-12.1-RELEASE-p3-amd64-3.7
  creating bin/temp.freebsd-12.1-RELEASE-p3-amd64-3.7/c
  creating bin/temp.freebsd-12.1-RELEASE-p3-amd64-3.7/c/common
  creating bin/temp.freebsd-12.1-RELEASE-p3-amd64-3.7/c/dec
  creating bin/temp.freebsd-12.1-RELEASE-p3-amd64-3.7/c/enc
  cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -Ic/include -I/usr/local/include/python3.7m -c c/common/dictionary.c -o bin/temp.freebsd-12.1-RELEASE-p3-amd64-3.7/c/common/dictionary.o
  unable to execute 'cc': No such file or directory
  error: command 'cc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for brotli

**SOLUTION**
brotli must be installed from binary package:
> pkg install py37-brotli

Maybe must be included in readme?

**Comment by werwolfby** [comment]
Я надеюсь что фриз requirements.txt все пофиксил уже, спасибо.
