### ISSUE TITLE
Dark libria

### ISSUE THREAD

**Issue by Akior** [werwolfby/monitorrent#346]
Приветствую.

Похоже правообладатели контента начали действовать более решительно, поэтому аниме уходит на другую площадку

Можно ли интегрировать https://dark-libria.it/ ?

Код в какой-то мере должен быть схож с anilibria

Для многосерийных тайтлов с разбивкой на группы серий можно сделать проверку по дате, чтобы исключить неправильный парсинг торрент файла
![image](https://user-images.githubusercontent.com/5903863/86540293-bbd48000-bf0c-11ea-9a81-8330378d3fd2.png)
![image](https://user-images.githubusercontent.com/5903863/86540299-c3942480-bf0c-11ea-937f-a3d51bd2094d.png)

**Comment by Akior** [comment]
т.е. если в БД мониторрента выбрать BDRip 1080p, и чекать торренты по актуальной дате или большой дате, он сам возьмет с обновления строки 1 и перейдет на строку 4, ручное вмешательство будет не нужно

**Comment by ZChuckMoris** [comment]
Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий). Было бы очень полезно и для AniLibria.

**Comment by ZChuckMoris** [comment]
Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.

**Comment by Akior** [comment]
> Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.

Качаю с помощью RSS

**Comment by ZChuckMoris** [comment]
> > Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.
> 
> Качаю с помощью RSS

Как это реализовать? Есть гайд? Я просто RSS ни разу не пользовался

**Comment by Akior** [comment]
> > > Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.
> > 
> > 
> > Качаю с помощью RSS
> 
> Как это реализовать? Есть гайд? Я просто RSS ни разу не пользовался

Например в qbittorrent 
добавить источник rss (darklibria) и добавить правило скачивания 
![image](https://user-images.githubusercontent.com/5903863/113479630-e140eb00-9498-11eb-8d69-b7edef7b23c4.png)

**Comment by ZChuckMoris** [comment]
> > > > Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.
> > > 
> > > 
> > > Качаю с помощью RSS
> > 
> > 
> > Как это реализовать? Есть гайд? Я просто RSS ни разу не пользовался
> 
> Например в qbittorrent
> добавить источник rss (darklibria) и добавить правило скачивания
> ![image](https://user-images.githubusercontent.com/5903863/113479630-e140eb00-9498-11eb-8d69-b7edef7b23c4.png)

Спасибо, разобрался. Увидел у вас в списке RSS фидов также AniDub, но [в их RSS фиде](https://tr.anidub.com/rss.xml) отсутствуют magnet-ссылки, в отличие от [RSS фида DarkLibria](https://darklibria.it/rss.xml). Как Вы производите автоматическую загрузку аниме с анидаба по RSS?

**Comment by Akior** [comment]
> > > > > Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.
> > > > 
> > > > 
> > > > Качаю с помощью RSS
> > > 
> > > 
> > > Как это реализовать? Есть гайд? Я просто RSS ни разу не пользовался
> > 
> > 
> > Например в qbittorrent
> > добавить источник rss (darklibria) и добавить правило скачивания
> > ![image](https://user-images.githubusercontent.com/5903863/113479630-e140eb00-9498-11eb-8d69-b7edef7b23c4.png)
> 
> Спасибо, разобрался. Увидел у вас в списке RSS фидов также AniDub, но [в их RSS фиде](https://tr.anidub.com/rss.xml) отсутствуют magnet-ссылки, в отличие от [RSS фида DarkLibria](https://darklibria.it/rss.xml). Как Вы производите автоматическую загрузку аниме с анидаба по RSS?

Анидаб не использую, т.к. реклама (Вам поможет эта статья если хотите сделать свой rss с сслылками https://habr.com/ru/post/87166/)

**Comment by knestor999** [comment]
> > > > > > > Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.
> > > > > > 
> > > > > > 
> > > > > > Качаю с помощью RSS
> > > > > 
> > > > > 
> > > > > Как это реализовать? Есть гайд? Я просто RSS ни разу не пользовался
> > > > 
> > > > 
> > > > Например в qbittorrent
> > > > добавить источник rss (darklibria) и добавить правило скачивания
> > > > ![image](https://user-images.githubusercontent.com/5903863/113479630-e140eb00-9498-11eb-8d69-b7edef7b23c4.png)
> > > 
> > > 
> > > Спасибо, разобрался. Увидел у вас в списке RSS фидов также AniDub, но [в их RSS фиде](https://tr.anidub.com/rss.xml) отсутствуют magnet-ссылки, в отличие от [RSS фида DarkLibria](https://darklibria.it/rss.xml). Как Вы производите автоматическую загрузку аниме с анидаба по RSS?
> > 
> > 
> > Тоже сделал себе RSS от Darklibria, но qbittorrent выдаёт ошибку, мол darklibria оборвала запрос и запрос не был до конца обработан
> 
> Попробуйте тогда через jackett

А как именно это сделать через jackett? Ни разу не пользовался, а в интернете толком понятной информации нету.
в indexer Darklibria нету.

**Comment by knestor999** [comment]
> > > > > > > Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.
> > > > > > 
> > > > > > 
> > > > > > Качаю с помощью RSS
> > > > > 
> > > > > 
> > > > > Как это реализовать? Есть гайд? Я просто RSS ни разу не пользовался
> > > > 
> > > > 
> > > > Например в qbittorrent
> > > > добавить источник rss (darklibria) и добавить правило скачивания
> > > > ![image](https://user-images.githubusercontent.com/5903863/113479630-e140eb00-9498-11eb-8d69-b7edef7b23c4.png)
> > > 
> > > 
> > > Спасибо, разобрался. Увидел у вас в списке RSS фидов также AniDub, но [в их RSS фиде](https://tr.anidub.com/rss.xml) отсутствуют magnet-ссылки, в отличие от [RSS фида DarkLibria](https://darklibria.it/rss.xml). Как Вы производите автоматическую загрузку аниме с анидаба по RSS?
> > 
> > 
> > Тоже сделал себе RSS от Darklibria, но qbittorrent выдаёт ошибку, мол darklibria оборвала запрос и запрос не был до конца обработан
> 
> Попробуйте тогда через jackett

Попробовал через VPN, и qbittorrent перестал выдавать ошибку, что Darklibria оборвала запрос. Но как это можно сделать без VPN ?

**Comment by ZChuckMoris** [comment]
> > > > > > > > Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.
> > > > > > > 
> > > > > > > 
> > > > > > > Качаю с помощью RSS
> > > > > > 
> > > > > > 
> > > > > > Как это реализовать? Есть гайд? Я просто RSS ни разу не пользовался
> > > > > 
> > > > > 
> > > > > Например в qbittorrent
> > > > > добавить источник rss (darklibria) и добавить правило скачивания
> > > > > ![image](https://user-images.githubusercontent.com/5903863/113479630-e140eb00-9498-11eb-8d69-b7edef7b23c4.png)
> > > > 
> > > > 
> > > > Спасибо, разобрался. Увидел у вас в списке RSS фидов также AniDub, но [в их RSS фиде](https://tr.anidub.com/rss.xml) отсутствуют magnet-ссылки, в отличие от [RSS фида DarkLibria](https://darklibria.it/rss.xml). Как Вы производите автоматическую загрузку аниме с анидаба по RSS?
> > > 
> > > 
> > > Тоже сделал себе RSS от Darklibria, но qbittorrent выдаёт ошибку, мол darklibria оборвала запрос и запрос не был до конца обработан
> > 
> > Попробуйте тогда через jackett
> 
> Попробовал через VPN, и qbittorrent перестал выдавать ошибку, что Darklibria оборвала запрос. Но как это можно сделать без VPN ?

Тут несколько способов решения есть.
Для начала, в jackett нет Dark-Libria, там есть лишь AniLibria. Что делает jackett? Проходится по сайту, парсит инфу и пихает тебе в локальный RSS фид, который ты уже без проблем подрубаешь к своему торрент-клиенту (ну и через него автоматизируешь загрузку торрентов).
Зачем это делать с Dark-Libria, у которого и без того есть нормальный RSS фид?

А касательно альтернативы VPN: ну, ты можешь поднять службу tor у себя на компе или воспользоваться иностранным http/https/socks5 проки. 
По tor: твой компьютер будет соединяться с серверами tor через службу tor, и она же будет генерировать локальный socks5 прокси (127.0.0.1:9050), который ты сможешь использовать в qBittorrent для соединения с теми самыми серверами tor.

**Comment by knestor999** [comment]
> > > > > > > > > Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Качаю с помощью RSS
> > > > > > > 
> > > > > > > 
> > > > > > > Как это реализовать? Есть гайд? Я просто RSS ни разу не пользовался
> > > > > > 
> > > > > > 
> > > > > > Например в qbittorrent
> > > > > > добавить источник rss (darklibria) и добавить правило скачивания
> > > > > > ![image](https://user-images.githubusercontent.com/5903863/113479630-e140eb00-9498-11eb-8d69-b7edef7b23c4.png)
> > > > > 
> > > > > 
> > > > > Спасибо, разобрался. Увидел у вас в списке RSS фидов также AniDub, но [в их RSS фиде](https://tr.anidub.com/rss.xml) отсутствуют magnet-ссылки, в отличие от [RSS фида DarkLibria](https://darklibria.it/rss.xml). Как Вы производите автоматическую загрузку аниме с анидаба по RSS?
> > > > 
> > > > 
> > > > Тоже сделал себе RSS от Darklibria, но qbittorrent выдаёт ошибку, мол darklibria оборвала запрос и запрос не был до конца обработан
> > > 
> > > 
> > > Попробуйте тогда через jackett
> > 
> > 
> > Попробовал через VPN, и qbittorrent перестал выдавать ошибку, что Darklibria оборвала запрос. Но как это можно сделать без VPN ?
> 
> Тут несколько способов решения есть. Для начала, в jackett нет Dark-Libria, там есть лишь AniLibria. Что делает jackett? Проходится по сайту, парсит инфу и пихает тебе в локальный RSS фид, который ты уже без проблем подрубаешь к своему торрент-клиенту (ну и через него автоматизируешь загрузку торрентов). Зачем это делать с Dark-Libria, у которого и без того есть нормальный RSS фид?
> 
> А касательно альтернативы VPN: ну, ты можешь поднять службу tor у себя на компе или воспользоваться иностранным http/https/socks5 проки. По tor: твой компьютер будет соединяться с серверами tor через службу tor, и она же будет генерировать локальный socks5 прокси (127.0.0.1:9050), который ты сможешь использовать в qBittorrent для соединения с теми самыми серверами tor.

tor у меня не подключается без мостов, а как мосты подключить к именно службе tor я не нашёл, ты случайно не знаешь как это сделать?

**Comment by knestor999** [comment]
> > > > > > > > > Есть ли по итогу рабочее решение для нескольких торрентов в одной раздаче (например, как тут, когда разбивают торренты на несколько по Х серий)? Было бы очень полезно и для AniLibria.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Качаю с помощью RSS
> > > > > > > 
> > > > > > > 
> > > > > > > Как это реализовать? Есть гайд? Я просто RSS ни разу не пользовался
> > > > > > 
> > > > > > 
> > > > > > Например в qbittorrent
> > > > > > добавить источник rss (darklibria) и добавить правило скачивания
> > > > > > ![image](https://user-images.githubusercontent.com/5903863/113479630-e140eb00-9498-11eb-8d69-b7edef7b23c4.png)
> > > > > 
> > > > > 
> > > > > Спасибо, разобрался. Увидел у вас в списке RSS фидов также AniDub, но [в их RSS фиде](https://tr.anidub.com/rss.xml) отсутствуют magnet-ссылки, в отличие от [RSS фида DarkLibria](https://darklibria.it/rss.xml). Как Вы производите автоматическую загрузку аниме с анидаба по RSS?
> > > > 
> > > > 
> > > > Тоже сделал себе RSS от Darklibria, но qbittorrent выдаёт ошибку, мол darklibria оборвала запрос и запрос не был до конца обработан
> > > 
> > > 
> > > Попробуйте тогда через jackett
> > 
> > 
> > Попробовал через VPN, и qbittorrent перестал выдавать ошибку, что Darklibria оборвала запрос. Но как это можно сделать без VPN ?
> 
> Тут несколько способов решения есть. Для начала, в jackett нет Dark-Libria, там есть лишь AniLibria. Что делает jackett? Проходится по сайту, парсит инфу и пихает тебе в локальный RSS фид, который ты уже без проблем подрубаешь к своему торрент-клиенту (ну и через него автоматизируешь загрузку торрентов). Зачем это делать с Dark-Libria, у которого и без того есть нормальный RSS фид?
> 
> А касательно альтернативы VPN: ну, ты можешь поднять службу tor у себя на компе или воспользоваться иностранным http/https/socks5 проки. По tor: твой компьютер будет соединяться с серверами tor через службу tor, и она же будет генерировать локальный socks5 прокси (127.0.0.1:9050), который ты сможешь использовать в qBittorrent для соединения с теми самыми серверами tor.

Премного благодарен, поднял службу тор с мостами и теперь RSS лента не обрывается и всё скачивается.

**Comment by werwolfby** [comment]
Я не возьмусь за имплементацию, сорри.
