### ISSUE TITLE
Не работает соединение proxy для http

### ISSUE THREAD

**Issue by a-flash** [werwolfby/monitorrent#349]
Пару месяцев назад перестал подключаться к kinozal.tv через прокси. Выяснил что если у трекера защищенное соединение, то работает. Lostfilm, rutracker все отлично. Прокси мой за границей, где все открывается. Пробовал разные другие прокси сервера, итог тот же. Такое ощущение что по http он вообще не использует прокси. В чем может быть проблема?

**Comment by werwolfby** [comment]
С проксями сложно, да и проблеми 3 года.
Закрываю за давностью, если что переоткрывайте.
