### ISSUE TITLE
Не удаляет предыдущую раздачу из qbittorrent в обновляемых раздачах

### ISSUE THREAD

**Issue by Eng3lS** [werwolfby/monitorrent#350]
Машинка без графики, клиент:
`qbittorrent-nox                      1:4.2.5.99~202004250119-7015-2c65b79~ubuntu18.04.1 armhf`
monitorrent из релизного архива 1.1.12

При обновлении  сериальной раздачи, например на нонеймклубе, monitorrent обнаруживает обновление, пытается добавить, но пишет в логи ошибку. Следующая периодическая проверка обнаруживает, что раздача уже добавлена и всё зелёненькое. Но на самом деле в qbittorrent раздача добавляется с первой попытки, но старая не удаляется. И так они будут накапливаться, пока руками не удалишь старые.
_________________
log qbittorrent
"(N) 2020-09-14T12:37:55 - Загружать с первой и последней части: Откл., торрент: «The_Boys_(s02)_1080p»
(N) 2020-09-14T12:37:55 - «The_Boys_(s02)_1080p» добавлен в список загрузок.
"
log monitorrent
![2020-09-14_130027](https://user-images.githubusercontent.com/59923611/93072639-54fce100-f68a-11ea-882b-514d39a6a9d5.png)

**Comment by sun1ight** [comment]
Наблюдаю у себя точно такуюже проблему

**Comment by LinFor** [comment]
Да, такая же байда.
При более подробном рассмотрении оказалось, что qbittorrent api как-то странно работает поиск торрента по хэшу - то возвращает результаты, то нет. Свежедобавленный в закачку торрент повышает вероятность некорректного ответа.
Ну и в момент запроса в monitorrent'е возникает race condition.

**Comment by sun1ight** [comment]
Мне помогло простое обновление пакета qbittorrent-api

**Comment by werwolfby** [comment]
Блин..., да могу :)

**Comment by werwolfby** [comment]
Запланированно на 1.3.0
