### ISSUE TITLE
Телеграм бот спамит ошибкой о торренте, которого нет в базе.

### ISSUE THREAD

**Issue by pnsalnikov** [werwolfby/monitorrent#359]
В последнее время телеграм бот каждые два часа стал слать сообщения об ошибке по таймауту для торрента, который раньше был в базе, но потом был удален. Сообщение такого вида:
Torrent <...> was changed, but can't be added, error: Request failed. Original exception: HTTPHandlerError, "HTTPHandlerError 600: urllib2.URLError: timed out" 

Сделал беглый поиск по monitorrent.db - там нет упоминаний этого топика, кроме самих записей в логе.

Этот торрент с рутора. В базе есть также торренты с рутора и с ними все ок.

Подскажите, пожалуйста, в чем может быть проблема?

**Comment by werwolfby** [comment]
Очень странная ошибка с ходу не могу сказать.

Перезапускать пробовали?

**Comment by pnsalnikov** [comment]
> Очень странная ошибка с ходу не могу сказать.
> 
> Перезапускать пробовали?

Да, конечно. Безрезультатно.

**Comment by werwolfby** [comment]
Если поделитесь базой (сбросив перед этим пароли в что-то рандомное), то могу глянуть.
Проблема очень странная.
Пока закрываю за давностью.
