### ISSUE TITLE
We could create an installer for windows.

### ISSUE THREAD

**Issue by DSilence** [werwolfby/monitorrent#36]
I use the following windows setup:
1) Monitorrent is downloaded from github.
2) Monitorrent installed as windows service via NSSM (https://nssm.cc/)
We could come up with a similar approach via installer.

**Comment by werwolfby** [comment]
http://www.mikeobrien.net/blog/using-gulp-to-build-and-deploy-dotnet-apps-on-windows/
Cool article about using gulp for dotnet applications

**Comment by werwolfby** [comment]
Instead of delete *.pyc we can create use gulp task which creates dist folder without *.pyc
