### ISSUE TITLE
1.2.0 Docker doesn't start

### ISSUE THREAD

**Issue by Egorkat** [werwolfby/monitorrent#361]
Log contains this repeating:
Traceback (most recent call last):
  File "/var/www/monitorrent/server.py", line 13, in <module>
    import structlog
ModuleNotFoundError: No module named 'structlog'

**Comment by werwolfby** [comment]
Странно `structlog` должен быть только в `develop` ветке. А я собирал все с `master`, перепроверю.

**Comment by werwolfby** [comment]
@Egorkat  а командой для запуска поделитесь?

**Comment by Egorkat** [comment]
'python' 'server.py'

**Comment by werwolfby** [comment]
Для всего докера

**Comment by werwolfby** [comment]
Типа: `docker run -v … werwolfby/monitorrent:1.2.0`

**Comment by Egorkat** [comment]
я его через portainer запускаю, предыдущая версия работала с текущими настройками. Попробую вытащить лог запуска

**Comment by werwolfby** [comment]
Ну скриншот портейнера можно, с запуском приложения. Мне не нужно команда внутри контейнера мне нужно понять какие волумы замаунчены в контейнер.

Я проверил контейнер в файле `server.py` нет импорта `structlog`. Такое есть только в девелоп ветке. Так что вижу только вариант когда сырцы почему-то перемаунчены…

Хотя… есть шанс что `monitorrent-1.2.0.zip` почему-то с девелопера (и это я могу объяснить и пофиксить), сейчас проверю

**Comment by werwolfby** [comment]
Да, так и есть. Но это значит что вы что-то сами руками собираете, а не используете готовый образ.

**Comment by Egorkat** [comment]
куда мне своими руками, портэйнер тянет свежий образ с докерхаба

**Comment by werwolfby** [comment]
Блин ну я сейчас перепроверю еще раз. Но скриншот того как контейнер запускается сильно помог бы.

**Comment by Egorkat** [comment]
![Portainer](https://user-images.githubusercontent.com/10372472/160768415-69aa0373-2c9c-4266-83ad-7d649abf1dee.png)

**Comment by werwolfby** [comment]
Вон в самом низу видна проблема: вы моунтите всю папку `Monitorrent` в `/var/www/monitorrent`. Тем самым перетирая все сырцы что уже есть в контейнере. Вам либо в папку зобрать все сырцы из мастер ветки, либо маунтить только файл `monitorrent.db` вместо всей папке как и написано в ридми.

Попробуйте для начала поменять на файл только, уверен что все сразу заработает как надо.

**Comment by werwolfby** [comment]
Лидо если `Monitorrent` это докер volume. То можно извратнуться:

Сделать моунт вместо `/var/www/monitorrent` в `/var/www/old-monitorrent` (`old-monitorrent` просто имя для примера.

И выставить новую ENV переменную `MONITORRENT_DB_PATH=/var/www/old-monitorrent/monitorrent.db`. Тогда старый волюм будет задействован но мы из него только базу будем брать, а новый сырцы будут браться из контейнера.

**Comment by werwolfby** [comment]
У вас раньше конечно все работало, но правильно все было только если вместе с контейнером вы сырцы в волюме тоже апдейтали из правильного тега, который совпадает с тегом контейнера (но вы юзаете `latest` кстати)

**Comment by Egorkat** [comment]
да, это volume. С путем просто к базе не стартует. Попробую "извратнуться" :-)

**Comment by werwolfby** [comment]
Да волюм - это всегда «папка» так что так просто и не стартанет.

**Comment by Egorkat** [comment]
Завелось! в лог поругалоссь только:
/usr/local/lib/python3.9/site-packages/alembic/util/messaging.py:73: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x7fad7e49dd90>

**Comment by werwolfby** [comment]
Это стандартный варнинг можно игнорить :)
Закрывайте ишью, а то 100 - было хорошим числом :)

**Comment by werwolfby** [comment]
Ну и да, моунтить чисто файл не очень хорошая идея, надо пофиксить. И проапдейтить ридми, хотя это может сломать совместимость.

Надо было изначально правильно сделать, но мне казалось очень привлекательной идеей моунтить чисто файл с базой и не заморачиваться с папками.
