### ISSUE TITLE
Установка на Raspberry pi 4 в Docker

### ISSUE THREAD

**Issue by urtaevS** [werwolfby/monitorrent#362]
Какую версию нужно установить для RPI 4?
Поставил этой командой:
```
docker run -d \
    --name monitorrent \
    -p 6687:6687 \
    -v /path/to/monitorrent.db:/var/www/monitorrent/monitorrent.db werwolfby/monitorrent:latest
```
Другие варианты установки ругаются на несоответствие архитектуры(если я правильно понял).
Только ошибки
[_monitorrent_logs (1).txt](https://github.com/werwolfby/monitorrent/files/8377955/_monitorrent_logs.1.txt)

**Comment by werwolfby** [comment]
Нужно установить последнюю 64-х битную версию на малинкк

**Comment by werwolfby** [comment]
32-х битная не поддерживается :( но это проблема playwright. Проще перейти на последнюю версию raspbian

**Comment by werwolfby** [comment]
Чисто для уточнения, команда запуска верная, просто у вас версия малинки 32-х битная. А на нее нельзя установить playwright.

**Comment by urtaevS** [comment]
```
getconf LONG_BIT
64
```
Так же можно проверить?

**Comment by werwolfby** [comment]
Лучше так:

```
uname -a
Linux master-01 5.10.79-v8+ #1 SMP PREEMPT Fri Nov 19 16:15:00 UTC 2021 aarch64 GNU/Linux
```

aarch64 - главная часть

**Comment by werwolfby** [comment]
Да проц у 4-й малинки 64-х битный, но операционка может быть 32-х битной.

**Comment by urtaevS** [comment]
`uname -a
Linux rpi 5.4.0-1056-raspi #63-Ubuntu SMP PREEMPT Mon Mar 14 07:48:06 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by werwolfby** [comment]
Да похоже с битностью у вас все окей. А командля для запуска в точности как в первом сообщении? Если да тогда у вас первый запуск?

И для первого запуска надо создать файл базы, выбрать папку где он будет храниться и там создать, чтото типа:

```
touch /home/pi/monitorrent.db
docker run -d \
    --name monitorrent \
    -p 6687:6687 \
    -v /hone/pi/monitorrent.db:/var/www/monitorrent.db
```


Зы. Не удобно писать с телефона, может гдето ошибся, но убедитесь что путь к базе верный.

**Comment by urtaevS** [comment]
В том то и дело. Была установлена версия 1.1.12. Файл базы был создан. Я удалил контейнер. И запустил заново:
`
docker run -d \
    --name monitorrent \
    -p 6687:6687 \
    -v /hone/pi/monitorrent.db:/var/www/monitorrent/monitorrent.db
`

**Comment by urtaevS** [comment]
Простите меня за тормознутость))
Спасибо за отзывчивость.
Ошибка было в том, что не указал имя файла в пути до базы
