### ISSUE TITLE
не ставится зависимость playwright

### ISSUE THREAD

**Issue by LIMonRUS** [werwolfby/monitorrent#365]
ERROR: Could not find a version that satisfies the requirement playwright==1.20.0 (from versions: none)
ERROR: No matching distribution found for playwright==1.20.0

**Comment by makar0nin** [comment]
Аналогичная проблема.
Ubuntu20.04

**Comment by werwolfby** [comment]
@LIMonRUS  а можно больще подробностей? Какая операционная система, какая архитектура?
@makar0nin про архитектуру подскажете?

**Comment by werwolfby** [comment]
Не могу пока нигде толком проверить, но в `docker` для `ubuntu:20.04` образа всё работает без проблем.

Завтра попробую ещё в `wsl` прогнать.

**Comment by LIMonRUS** [comment]
> @LIMonRUS а можно больще подробностей? Какая операционная система, какая архитектура? @makar0nin про архитектуру подскажете?
Пытался поставить на keenetic 
uname -a 
4.9-ndm-4 #2 SMP Fri May 28 22:34:56 MSK 2021 mips GNU/Linux
opkg install python3 python3-pip wget unzip
pip3 install --upgrade setuptools
mkdir -p /opt/monitorrent/
cd /opt/monitorrent/
wget https://github.com/werwolfby/monitorrent/releases/download/1.2.0/monitorrent-1.2.0.zip
unzip monitorrent-1.2.0.zip
pip install -r requirements.txt
----
ERROR: Could not find a version that satisfies the requirement playwright==1.20.0 (from versions: none)
ERROR: No matching distribution found for playwright==1.20.0
----
дальше соответственно продолжать нет смысла

**Comment by werwolfby** [comment]
Ну да :(
Потому что
> SMP Fri May 28 22:34:56 MSK 2021 mips GNU/Linux
Говорит что архитектура процессора `mips`. А он не поддерживается `playwright`'ом. Только `arm64` и `amd64` так что вариантов я не вижу :(

Ну т.е. можно поискать вдруг можно поставить `firefox` и найти драйвер для него. И переписать код, но это очень сложный путь. Да и тестить негде :(

В общем без `playwright` оно может работать, но либо руками переодически сетать куку, либо надеятся что больше DDoS не будет. Как было и раньше, DDoS проверки появлялись не на долго обычно.

**Comment by makar0nin** [comment]
Прошу прощения что долго, но лучше поздно...

`Linux machine 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by werwolfby** [comment]
@makar0nin надеюсь проблемы больше нет, закрываю пока тикет
