### ISSUE TITLE
qbittorrent HTTPS

### ISSUE THREAD

**Issue by IgorKha** [werwolfby/monitorrent#367]
Если использовать qbittorrent (v4.2.5) с включенным HTTPS, то подключится к нему не получится

**Comment by werwolfby** [comment]
@IgorKha а домент и сертификат для qbittorrent валидные? Lets Encrypt хотя бы?

Если нет то надо проверку HTTPS убирать, что убивает всю идею безопасного соединения. Или сделать CA сертификат, подписать им qbittorrent сертификат и юзать его.  А CA сертификат установить в систему где стоит мониторрент как доверенный.

**Comment by IgorKha** [comment]
Использовал самоподписанный сертификат, сейчас http юзаю только из домашней сети, проблема не критичная, спасибо, буду иметь ввиду

**Comment by werwolfby** [comment]
Ну с самоподписанным советую таки сделать CA и им все остальные само подписанные подписать, а CA установить как доверенный, это реально решит большинство проблем. И даже браузер перестанет ругаться.

**Comment by IgorKha** [comment]
Понял, большое спасибо за ответ и за Ваш продукт :)
