### ISSUE TITLE
kinozal.tv перестал работать

### ISSUE THREAD

**Issue by RU2026** [werwolfby/monitorrent#374]
FAILED
Can't login: Unknown

С 8.11 не логинится

**Comment by RU2026** [comment]
> Похоже связанно с переходом трекера на HTTPS. Мне помогла замена http на https в plugins/trackers/kinozal.py в строках
> 
> ```
> login_url = "http://kinozal.tv/takelogin.php"
> profile_page = "http://kinozal.tv/inbox.php"
> ```

Спасибо! Помогло

**Comment by RU2026** [comment]
Пару дней поработал и сегодня вывалилось

`FAILED
Exception while execute topic
Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 214, in execute
    changed = self.check_changes(topic)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\kinozal.py", line 278, in check_changes
    last_torrent_update = self.tracker.get_last_torrent_update(topic.url)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\kinozal.py", line 202, in get_last_torrent_update
    last_update_text_element = content.find('b', text=self.last_update_text_re)
AttributeError: 'NoneType' object has no attribute 'find'`

**Comment by NeekOteen** [comment]
> Пару дней поработал и сегодня вывалилось

Подтверждаю, появились аналогичные ошибки. 
Подозреваю что в этот раз может быть связанно с “DDoS protection”. Ранее данной защиты не замечал.

**Comment by tops5** [comment]
> > Пару дней поработал и сегодня вывалилось
> 
> Подтверждаю, появились аналогичные ошибки. Подозреваю что в этот раз может быть связанно с “DDoS protection”. Ранее данной защиты не замечал.

Вчера пересобрал docker image, сначала кинозал работал, ночью начали вываливаться такие же ошибки. Насколько я понял трекер подключил cloudflare, поэтому ошибки и вываливаются. Хотя , когда вручную проверяю трекеры, ошибок нет.

**Comment by RU2026** [comment]
Заработало

**Comment by werwolfby** [comment]
Закрываю за давностью
