### ISSUE TITLE
Download dir

### ISSUE THREAD

**Issue by Leliil** [werwolfby/monitorrent#378]
Подскажите, как поменять место загрузки по умолчанию?
Чтобы Monitorrent тянул не от торрент-клиента, потому что там по умолчанию папка загрузок и каждый раз вручную менять путь приходится...

**Comment by werwolfby** [comment]
Не уверен что понял вопрос. Но в настройках торрент клиента можно менять папку. И кажется была такая фича при создании «закачки».

**Comment by werwolfby** [comment]
Но это зависит от торрент клиента. Не для всех реализовано. 
uTorrent и Transmission были точно. Остальные надо смотреть.

**Comment by Leliil** [comment]
> Но это зависит от торрент клиента. Не для всех реализовано. uTorrent и Transmission были точно. Остальные надо смотреть.

Я понимаю, что настройка тянется с торрент-клиента, там папка по умолчанию - загрузки, ручками при добавлении выбираю то, что нужно, но в monitorrent каждый раз приходится путь менять, вручную его не ввести, приходится через winscp копировать путь и вставлять, дописывать название папки для сериала.
Подумал, может где-то в файлах можно поменять этот путь, чтобы не тянуть с клиента, а вручную выставить, а потом только название папки для сериала вставить

**Comment by werwolfby** [comment]
Немного не так.
В настройках торрент клиента в мониторренте можно указать папку по усолчанию. Если это не делать, то в клиент она не передается. И сам клиент использует папку по умолчанию. Т.е. мониторрент ничего не тенят с клиента. 

И мне казалось что после того как выставить в насройках мониторрента выставить папку, то потом при настройке сериала этот путь и покажется, и к нему легко добавить июпапку сериала.

**Comment by Leliil** [comment]
> Немного не так. В настройках торрент клиента в мониторренте можно указать папку по усолчанию. Если это не делать, то в клиент она не передается. И сам клиент использует папку по умолчанию. Т.е. мониторрент ничего не тенят с клиента.
> 
> И мне казалось что после того как выставить в насройках мониторрента выставить папку, то потом при настройке сериала этот путь и покажется, и к нему легко добавить июпапку сериала.

Хм, видимо упустил этот момент, спасибо за оперативный ответ, посмотрю. Почему-то всегда считал, что он по умолчанию ставит путь к папке с торрент клиента и уже пару лет руками меняю...

**Comment by werwolfby** [comment]
Я уже года 4 не трогал этот код… так что могу ошибаться, но задумка была именно такая 😏

**Comment by Leliil** [comment]
> Я уже года 4 не трогал этот код… так что могу ошибаться, но задумка была именно такая 😏

Понятно) Я порой думаю, что вы совсем проект забросили, но все работает исправно, как говорится: работает - не чини) ещё на wd mycloud ставил, в которой OMV 2 крутился, мне помогали все это не в докере собрать и чтобы можно было через system.d старт/стоп/рестарт делать)
Не знаю уже сколько лет прошло и всё исправно работает, спасибо

**Comment by Leliil** [comment]
> Я уже года 4 не трогал этот код… так что могу ошибаться, но задумка была именно такая 😏

Посмотрел, только ip, port, login\passwd можно ввести, путь берется только из торрент-клиента, который там указан по умолчанию.

**Comment by werwolfby** [comment]
А что за клиент?

**Comment by Leliil** [comment]
transmission

**Comment by Leliil** [comment]
> А что за клиент?
Transmission

**Comment by werwolfby** [comment]
Странно, как будет возможность, гляну. 
и перепрове как оно реализовано. Постараюсь на следующей неделе.

**Comment by werwolfby** [comment]
Хмм… [действительно](https://github.com/werwolfby/monitorrent/blob/develop/monitorrent/plugins/clients/transmission.py#L92) ничего подобного я не заимплементил. Но ничего в версии 2.0 все будет лучше :)

**Comment by Leliil** [comment]
Спасибо за обратную связь)
