### ISSUE TITLE
nnmclub.to не добавляет

### ISSUE THREAD

**Issue by RU2026** [werwolfby/monitorrent#386]
Добрый день,
не добавляет nnmclub.to, не находит "name"
проверил вход - "Connection successful"

v1.3.0
windows 7 64

**Comment by werwolfby** [comment]
Гляну

**Comment by werwolfby** [comment]
Только что у себя на распбери проверил, все хорошо добавилось и докинулось в трансмишен.
Есть ли прокси? Попробуйте залогинится руками в ннм, у меня сработало только указав почту.
Может торрент какой-то особенный? Если поделитесь, попробую его.

**Comment by RU2026** [comment]
https://nnmclub.to/forum/viewtopic.php?p=11898245

вообще разные пробовал

**Comment by RU2026** [comment]
Vpn есть
Ручками залогинился

**Comment by werwolfby** [comment]
![Monitorrent](https://user-images.githubusercontent.com/705754/230702593-42816bfc-c4b3-463f-8255-97c023d6c587.png)

**Comment by RU2026** [comment]
![Безымянный](https://user-images.githubusercontent.com/117902921/230702607-27b69b71-5048-4135-be1d-683094534de6.png)

**Comment by werwolfby** [comment]
5 минут назад скачался: Бюро магических услуг.
Попробуйте заново креды в ввести в мониторрент с сохранением и еще раз проверкой.
Я просто заново влогинивался и востанавливал учетку, 3 года не был на ннм.

Если не поможет, то надо пробовать `1.4.0-alpha.1` версию и смотреть в логи.

**Comment by RU2026** [comment]
Креды не помогло
Попробую альфу и отпишу
Спасибо

**Comment by RU2026** [comment]
https://github.com/werwolfby/monitorrent/releases/download/1.4.0-alpha.1/MonitorrentInstaller-1.4.0-alpha.1.msi  page not found

**Comment by werwolfby** [comment]
https://github.com/werwolfby/monitorrent/releases/download/1.4.0-alpha.1/MonitorrentInstaller-1.4.0-alpha.1.exe

Черт, поменяю на exe :)

**Comment by werwolfby** [comment]
Пофиксил урл в доке

**Comment by werwolfby** [comment]
Нужно будет руками запустить через cmd: `RunApp.bat > C:\path\to\log.txt`
Стандартного места логов пока нет

**Comment by RU2026** [comment]
![Безымянный](https://user-images.githubusercontent.com/117902921/230703491-36df5798-23fb-4cef-9a5d-ed7ee0429593.png)
на 1.4.0 всё добавилось без проблем, вопрос снимаю. Спасибо

**Comment by werwolfby** [comment]
Просто с 1.3.0 по сравнению с 1.4.0 в ннм плагине ничего не менялось, так что сам по себе 1.4.0 не должен был помочь :)

**Comment by RU2026** [comment]
Тем не менее, на альфе всё заработало, больше ничего не менял

**Comment by RU2026** [comment]
Если это как то поможет, механизм был такой, сегодня обновился с 1.2.1 на 1.3, перестало работать, на 1.4 все заработало. Обновлялся с exe

**Comment by werwolfby** [comment]
Спасибо за детали, без логов плохо конечно :(

**Comment by RU2026** [comment]
Кнопка "поддержать" не рабоает [https://money.yandex.ru/to/410012638435097](url) есть другой спосооб?

**Comment by werwolfby** [comment]
@RU2026 спасибо. Не парьтесь. 
Я уберу ссылку. У меня были деньги на яндексе, но яндекс их забрал. Так что больше не надо 😃
