### ISSUE TITLE
Логи от Lostfilm Challenge Logs

### ISSUE THREAD

**Issue by degorychev** [werwolfby/monitorrent#387]
По глупости включил Lostfilm Challenge Logs да еще и с записью видео... Итого я вижу что иногда парсинг об чтото спотыкается и просто смотрит на стартовую страницу. 
Что более глупо, попытался скачать эти видео от логов и увидел что у меня их на данный момент 5 штук по 15-20 гигов, которые длятся неизвестно сколько, потому что в плеере эти ролики почему то не перематываются (Кстати возможно что парсинг зависает от того, что ему не хватает пространства на диске, так как еще наблюдаются ошибки в духе "база данных заблокирована" и место у контейнера действительно подошло к концу)
Сейчас выключил эту запись роликов и добавил еще чуть-чуть места, Но я бы хотел эти ролики удалить, а как это сделать - не пойму.

**Comment by werwolfby** [comment]
Ну да, удаления роликов как такового нету :(
Надо кнопочку добавить там же, а так же инфу о том сколько места занято.
Но по умолчанию там 3 последних видио сохраняется только остальные удаляются. 
Ну и размер конечно удивляет :( Там же таймаут на 30 секунд, т.е. больше 30 секунд не должно записываться, если не удалось пройти челендж, то просто падаем.

**Comment by werwolfby** [comment]
Уточнил, таймаут 2 минуты (120000 мс), 3 последних видео хранить.

**Comment by werwolfby** [comment]
Ну и все видео можно удалить простой командой доя докера:

```bash
docker exec monitorrent rm -rf /var/www/monitorrent/webapp/challenges/*
```

Команду не проверял :)
Так что сначала стоит сделать `ls` чтобы убедится что там ща файлы:
```bash
docker exec monitorrent ls -la var/www/monitorrent/webapp/challenges/*
```

**Comment by werwolfby** [comment]
@degorychev есть апдейты?

**Comment by degorychev** [comment]
> @degorychev есть апдейты?
Ну да, правда из портейнера выполнил команду, сработало.
![image](https://user-images.githubusercontent.com/32064103/232836499-7eb75420-a00d-4c8b-b68e-21cdb24ec2f1.png)
