### ISSUE TITLE
Extends parameters to start monitorrent

### ISSUE THREAD

**Issue by werwolfby** [werwolfby/monitorrent#76]
Add parameters and env variables:
**ip** / **MONITORRENT_IP** - Bind interface. Default is *0.0.0.0*
**port** / **MONITORRENT_PORT** - Port for web ui. Default is *5000*
**db** / **MONITORRENT_DB** - Path to monitorrent database. Default is current folder.

**Comment by DSilence** [comment]
I think this could be added in a form of config.py (or config.json).

**Comment by werwolfby** [comment]
In XXI centry where containers controls the world noone should use configs, only env variables and execute parameters.
