### ISSUE TITLE
qbittorent api extend

### ISSUE THREAD

**Issue by werwolfby** [werwolfby/monitorrent#83]
According to webapi documentation **find_torrent** can be reimplemented with this api call: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#get-torrent-generic-properties
which has **addition_date** property.

**Comment by DSilence** [comment]
It doesn't have name property, that's why I used list since it has both.

**Comment by werwolfby** [comment]
Why wontfix?

**Comment by DSilence** [comment]
Closing since the **name** property necessary for the implementation is missing in https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#get-torrent-generic-properties
