### ISSUE TITLE
Change the port of installed application from 5000

### ISSUE THREAD

**Issue by DSilence** [werwolfby/monitorrent#84]
5000 is a common dev port (along with 8080), so changing it to something with 5 digits makes sense for default installation.

**Comment by werwolfby** [comment]
If we look at phone keyboard then I suggest next:
**moni** -> *6664*
**mttr** -> *6887*
Some other suggestions?

**Comment by werwolfby** [comment]
All ports are absolutely free and not assigned: http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=6664
http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=6887

**Comment by werwolfby** [comment]
mntr - 6687
