### ISSUE TITLE
There is an extra scrollbar in edge on login screen

### ISSUE THREAD

**Issue by DSilence** [werwolfby/monitorrent#85]
Steps to reproduce:
1) Go to https://{monitorrent_url}/login.
2) Click on password textbox.
Actual result:
![image](https://cloud.githubusercontent.com/assets/3896043/14451044/53aea25a-008c-11e6-916a-fcdeb4edb03b.png)

**Comment by kijojo** [comment]
Can't reproduce. Latest develop branch revision. Edge v20.10240.16384.0

**Comment by werwolfby** [comment]
Are you sure? I think it was fixed by migrating to Angular Material 1.1 RC4

**Comment by DSilence** [comment]
Can confirm that the issue was fixed by an update.
